### ISSUE TITLE
field_file javascript displays the first file multiple times 

### ISSUE THREAD

**Issue by ryanbarrows** [django-crispy-forms/django-crispy-forms#1010]
* Package version: 1.9.0

### Description:

The list of filenames is generated with a bug in the code such that the first filename gets repeated rather than taking each filename.  The correct code just needs to change a '0' (zero) to 'i' like this:
```
filenames+=(i>0?", ":"")+e.target.files[i].name;
```

which is taken from **crispy_forms/templates/bootstrap4/layout/field_file.html.**  

```
    <script type="text/javascript" id="script-{{ field.id_for_label }}">        
        document.getElementById("script-{{ field.id_for_label }}").parentNode.querySelector('.custom-file-input').onchange =  function (e){
            var filenames = "";
            for (let i=0;i<e.target.files.length;i++){
                filenames+=(i>0?", ":"")+e.target.files[0].name;
            }
            e.target.parentNode.querySelector('.custom-file-label').innerHTML=filenames;    
        }        
    </script>
```
Thanks!

**Comment by bryan-brancotte** [comment]
Hi @ryanbarrows 
Thanks for raising the issue ! Your fixe have been commited.
Best wishes
