### ISSUE TITLE
override the form html tags without using layout

### ISSUE THREAD

**Issue by 0xenAlpha** [django-crispy-forms/django-crispy-forms#1012]
* Package version: 1.9.0
* Django version: 2.2.7
* Python version: 3.7
* Template pack: (Optional)

### Description:

There is anyway to override the form html tags without using layout ? (i'm getting punch of divs that i don't need, i just want the input field) 
thanks

**Comment by smithdc1** [comment]
Hi you can use the `as_crispy_field` filter to render individual fields.

Here is a worked example.

https://simpleisbetterthancomplex.com/tutorial/2018/11/28/advanced-form-rendering-with-django-crispy-forms.html#custom-fields-placement-with-crispy-forms

**Comment by 0xenAlpha** [comment]
That's exactly what I'm using and i followed that same tutorial, it stills wrap it by divs

**Comment by smithdc1** [comment]
Hi @0xenAlpha in that case you probably just want `crispy_field`.  The templates are a good example of this. 

e.g. just render a field (i.e. `<input>` only)
https://github.com/django-crispy-forms/django-crispy-forms/blob/ba53410f752402436d84dc8ab00e2b6e1e67a74c/crispy_forms/templates/bootstrap4/field.html#L42

You can also pass in attributes like so. This will add `custom-control-input` to the class of the `<input>`.
https://github.com/django-crispy-forms/django-crispy-forms/blob/ba53410f752402436d84dc8ab00e2b6e1e67a74c/crispy_forms/templates/bootstrap4/field.html#L30

Good luck.
