### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by shivenmian** [django-crispy-forms/django-crispy-forms#1013]
* Package version: 1.9.0
* Django version: 3.0.5
* Python version: 3.7.6
* Template pack: (Optional)

### Description:

I wanted to allow textboxes in my form to accept / render Markdown input rather than plaintext. Is there a workaround / an alternative? @smithdc1

**Comment by smithdc1** [comment]
Hi @shivenmian 

Interesting question. My first thought is that this sounds like a general Django question, rather than a crispy-forms specifically. Crispy-forms 'only'™️  adds css classes to your inputs. More specifically, there isn't a Markdown field under the bootstrap form [docs.](https://getbootstrap.com/docs/4.4/components/forms/) which we would look to replicate. 

Do you have example html layout / css required? Or even better a small working example which works with standard django styling but not with one of the crispy-form template packs.

**Comment by shivenmian** [comment]
Hi @smithdc1 I just saw this.

So I was trying to use [Markdown Deux](https://github.com/trentm/django-markdown-deux) and I was adding the filter with the crispy forms filter (i.e {{ form|crispy|markdown }}), but I've not had much success there. 

I'm a bit new to Django myself and still learning - do you have any suggestions?

**Comment by smithdc1** [comment]
I must admit Ive looked at the library linked and now I'm slightly confused as to what you are trying to achieve. (I'm new also)


From what I can tell the library you linked to turns markdown into html.

How does this work with your form?

**Comment by shivenmian** [comment]
So what I want is for my form to accept Markdown input in the textboxes. The rationale for this is because my application can have input which may have code blocks in them, which I'd ideally want formatted. This is why I thought of using Markdown, since it can handle both normal, unformatted input (which is what currently crispy forms supports) and can also handle cases like code blocks.

As an example, consider [your example gist](https://gist.github.com/maraujop/1838193) on your README. Ideally, I'd want textarea to be Markdown compatible (eg: if I add code in ```backticks``` then it should appear like the codeblock). Something like the GitHub comment area on which I'm typing this, for example. This is what I want.

**Comment by smithdc1** [comment]
Hi I think I understand a bit more now.

It sounds like the input in the form is 'just':TM: a text area.

The output is then rendered to html when that content is displayed. 

If you wanted extra buttons then this sounds like extra js with the widget (maybe using form media?) 

Alternatively something like this may help? (I've not used it so it's not a recommendation but I think something like this is what you are after) 

https://github.com/agusmakmun/django-markdown-editor
