### ISSUE TITLE
Specify Python version requirement (>=3.x)

### ISSUE THREAD

**Issue by gchazot** [django-crispy-forms/django-crispy-forms#1014]
https://github.com/django-crispy-forms/django-crispy-forms/blob/ba53410f752402436d84dc8ab00e2b6e1e67a74c/setup.py#L22

The drop of Python 2 support in release 1.9.0 has broken installation of the package for users of Python 2 because it does not specify that Python 3 is required.

The recommendation is specified here, including instructions for `setup.py`: 
https://packaging.python.org/guides/dropping-older-python-versions/

Would you mind adding the specification to the package?
This would also mean either re-releasing 1.9.0 :see_no_evil:  or update 1.9.0 directly in Pypi with that information (is it possible?) or releasing something like 1.9.0.1 or 1.9.1 and removing 1.9.0 from Pypi...

**Comment by carltongibson** [comment]
Happy to take a PR adding it for the next release. TBH not prepared to pull a release from PyPI that folks could/should have pinned to. 

If you're still on Python 2, just pin to 1.8.x.

**Comment by gchazot** [comment]
I submitted a PR with the change.

The harm is done on Pypi though.

I mean even after merging and releasing the PR, anyone on Python <3.5  doing `pip install django-crispy-forms` will get `1.9.0`.

I don't know Pypi enough to know if it's possible to add "python_requires" to an existing release... Or maybe to flag a release in a way that `pip` will not consider it any more when resolving a dependency. As a last measure, maybe it is possible to re-release 1.9.0 with just this change?

**Comment by gchazot** [comment]
> The harm is done on Pypi though.

No offense intended.

I just mean that the release is out there on pypi.

**Comment by carltongibson** [comment]
Yeah... sorry but dependencies should be pinned. All the more so if you're using an EOL Python.

Thanks for the PR.

**Comment by gchazot** [comment]
Hey @carltongibson I just realised there's [a PEP for this](https://www.python.org/dev/peps/pep-0592/) and `pypi.org` has a feature to use it.

It's the "Yank" option under "Manage" of your project:

![image](https://user-images.githubusercontent.com/8948373/80866919-4a1c5380-8c89-11ea-85c1-237787819df6.png)
