### ISSUE TITLE
Buttons Render Strangely

### ISSUE THREAD

**Issue by OmenApps** [django-crispy-forms/django-crispy-forms#1016]
* Package version: 1.9.0
* Django version: 3.0.4
* Python version: 3.8
* Template pack: bootstrap4

### Description:

My buttons are rendering really weird, and I'm not sure why.

Here's the form code I'm using:

```
class MyModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Accordion(
                AccordionGroup(
                    'First Group',
                    "name",
                    "description",
                ),
                AccordionGroup(
                    'Second Group',
                    "purchase_date",
                    "purchase_price",
                    "disposal_date",
                    "disposal_company",
                    "disposal_cost",
                    "disposal_verification_number",
                ),
            ),
            Submit('save', 'Save changes', css_class='btn btn-success'),
            Button('cancel', 'Cancel')
        )

    class Meta:
        model = MyModel
        fields = [
            "name",
            "description",
            "purchase_date",
            "purchase_price",
            "disposal_date",
            "disposal_company",
            "disposal_cost",
            "disposal_verification_number",
```

In my template:

```
<form method="post">
    {% crispy form form.helper "bootstrap4" %}
    {% csrf_token %}
</form>
```

The resulting rendered html:

```
<i class="btn btn-primary btn btn-success waves-input-wrapper waves-effect waves-themed" style="color:rgb(0, 0, 0);background:rgb(221, 221, 221)">
  <input type="submit" name="save" value="Save changes" class="waves-button-input" id="submit-id-save" style="background-color:rgba(0,0,0,0);">
</i>
<i class="btn waves-input-wrapper waves-effect waves-themed" style="color:rgb(0, 0, 0);background:rgb(221, 221, 221)">
  <input type="button" name="cancel" value="Cancel" class="waves-button-input" id="button-id-cancel" style="background-color:rgba(0,0,0,0);">
</i>
```

This looks horrible. Basically a button-on-button effect.

[Screenshot of buttons](https://imgur.com/msApSfe)

I'm not sure where the `<i>` tags are coming from, or where the `waves-*` classes are coming from. Those don't seem to be in any of the code within the crispy forms project.

Any idea how to correct this? Searching online has not brought up any relevant results.

**Comment by smithdc1** [comment]
Hi!

https://github.com/mdbootstrap/bootstrap-material-design/issues/8

Are you using this by any chance?

**Comment by OmenApps** [comment]
No, but I wonder if the theme I'm using utilizes that. I've always used `<button>` rather than `<input>` on my form submits, so I never noticed the issue before.

Like in the linked issue, if I use the `<input>` tag manually, I get the same issue.

Should I just override the template to use button instead? Or is there a better way of approaching this?

**Comment by smithdc1** [comment]
It looks to me like some JS is changing this as you are getting completely different tags and css classes to what the templates render. I therefore don't _think_ that a manual template will fix this?

Can you disable the JS and see what HTML you get?
Or try `render_crispy_form(MyModelForm)` in a debuger session to see what HTML crispy-forms is rendering? 

https://github.com/django-crispy-forms/django-crispy-forms/blob/71490e7329c14915b3c8cb5216351145d8fa900a/crispy_forms/utils.py#L154

**Comment by OmenApps** [comment]
@smithdc1 Thanks for the help. Was able to verify that the code my template uses does indeed incorporate those lines from mdbootstrap. Commenting them out resolved the issue.
