### ISSUE TITLE
Django Tabs issue Crispy forms

### ISSUE THREAD

**Issue by Miracle619** [django-crispy-forms/django-crispy-forms#1019]
* Package version:
* Django version:  2.2.6
* Python version:  3.8.1
* Template pack: bootstrap4

i want to design tabs with crispy form in which every tabs field should be from different model. but i am unable to do

Below is form.py code:
from django import forms
from crispy_forms.helper import FormHelper,Layout
from crispy_forms.layout import Submit,Row,Column
from crispy_forms.bootstrap import TabHolder,Tab
from .models import Lead,LeadDetail
from apps.Accounts.models import Accounts
from apps.Contacts.models import Contacts
from apps.common.models import AllMaster
from apps.Product.models import Product
from django.contrib.auth.models import User

class CommonFormHelper(FormHelper):
    def __init__(self):
        super(CommonFormHelper, self).__init__()
        self.disable_csrf = True
        self.form_tag = False

class Leadform(forms.ModelForm):

    LeadNo              =  forms.CharField(label="Lead No",required=False)
    Lead_Date           =  forms.DateField(label="Lead Date", widget=forms.TextInput(
                           attrs={'type': 'date'}))
    Account_Id          =  forms.ModelChoiceField(label="Account Name", queryset=Accounts.objects.filter(isActive=1))
    Contact_Id          =  forms.ModelChoiceField(label="Contact Name", queryset=Contacts.objects.filter(isActive=1))
    Lead_Source         =  forms.ChoiceField(choices=[],widget=forms.Select,)
    Lead_Type           =  forms.ChoiceField(choices=[],widget=forms.Select,)
    Lead_Status         =  forms.ChoiceField(choices=[], widget=forms.Select, )
    Probablity          =  forms.ChoiceField(choices=[],widget=forms.Select,)
    Lead_Description    =  forms.CharField(widget=forms.Textarea(attrs={'cols':300,'rows':5}))
    GST_No              =  forms.CharField(label="GST No",max_length=50)
    Lead_Assigned_To    =  forms.ChoiceField(choices=[],widget=forms.Select,)

    def __init__(self, *args, **kwargs):
        a = LeadDetail

        super(Leadform, self).__init__(*args, **kwargs)

        self.fields['Lead_Source'].choices = AllMaster.objects.values_list('Field_Value', 'Field_Value').filter(
            catid=6).distinct()
        self.fields['Probablity'].choices = AllMaster.objects.values_list('Field_Value', 'Field_Value').filter(
            catid=5).distinct().order_by('id')
        self.fields['Lead_Assigned_To'].choices = User.objects.values_list('username','username').distinct()
        self.fields['LeadNo'].widget.attrs['readonly'] = True

        self.helper = CommonFormHelper()
        # self.helper_Lead_Info.form_tag = False
        self.helper.layout = Layout(
            TabHolder(
                Tab('Lead Info',
                    Row(

                        Column('LeadNo', css_class='form-group col-md-6 mb-0'),
                        Column('Lead_Date', css_class='form-group col-md-6 mb-0'),
                        Column('Account_Id', css_class='form-group col-md-6 mb-0'),
                        Column('Contact_Id', css_class='form-group col-md-6 mb-0'),
                        Column('Lead_Source', css_class='form-group col-md-6 mb-0'),
                        Column('Lead_Status', css_class='form-group col-md-6 mb-0'),
                        Column('Lead_Type', css_class='form-group col-md-6 mb-0'),
                        Column('Probablity', css_class='form-group col-md-6 mb-0'),
                        Column('GST_No', css_class='form-group col-md-6 mb-0'),
                        Column('Lead_Assigned_To', css_class='form-group col-md-6 mb-0'),
                        css_class='form-row',
                    ),
                    'Lead_Description',

                    ),
                Tab('Product info',

                    )

            ),

        )

                # self.helper.add_input(Submit('submit', 'save'))
        # self.helper.form_method = 'POST'

    class Meta:
        model= Lead
        fields = "__all__"
            # ('LeadNo','Lead_Date','Account_Id','Contact_Id','Lead_Source','Lead_Type','Lead_Status','Lead_Description','GST_No')
        exclude =('Lead_Date', 'assigned_to','modifiedBy','createdBy')

class LeadDetailForm(forms.ModelForm):

    class Meta:
        model = LeadDetail
        fields ="__all__"
        exclude=('LeadId','modifiedBy','createdBy')

    Product             = forms.ChoiceField(choices=[],widget=forms.Select)
    Quantity            = forms.IntegerField()
    Rate                = forms.IntegerField()
    Amount              = forms.IntegerField()

    def __init__(self, *args, **kwargs):

        super(LeadDetailForm, self).__init__(*args, **kwargs)

        self.fields['Product'].choices =   Product.objects.values_list('Product_Name', 'Product_Name').distinct()

        self.helper_Leaddetail = CommonFormHelper()
        # self.helper_Lead_Info.form_tag = False
        self.helper_Leaddetail.layout = Layout(

                Tab('Product Info',
                        Row(

                            Column('LeadNo', css_class='form-group col-md-6 mb-0'),
                        )
                    ),

        )

from the above code i want t display tab product info from LeadDetailForm class

Can anyone help me???

**Comment by Miracle619** [comment]
Even when i am design tab in LeadDetailForm class it is not displaying

**Comment by patagoniapy** [comment]
Could you post your `views.py` and also your HTML?

**Comment by patagoniapy** [comment]
Also, could you reformat your code snippets above to make a little bit easier to read? Especially your `forms.py` file. Do so by including including the code between "```python" and "```"

**Comment by Miracle619** [comment]
view.py

from django.shortcuts import render
from django.views.generic import TemplateView,CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.common.models import Menu
from apps.Accounts.models import Accounts
from .models import Lead,LeadDetail
from apps.Product.models import Product
from .forms import Leadform,LeadDetailForm
from django.contrib.auth.models import User,Group
from apps.common.models import AllMaster
# Create your views here.

class LeadView(TemplateView):
    # model = Lead
    # template_name = "Lead/Lead.html"
    # form_class = Leadform

    # fields = ('Account_Id','Contact_Id','Lead_Source','Lead_Type','Probablity','Lead_Status','Lead_Description','Lead_Assigned_To')

    def get(self, request, *args, **kwargs):
        form = Leadform()
        form2 = LeadDetailForm()
        template_name = 'Lead/Lead.html'
        context = {
            'form': form,
            'form2': form2,
        }

        if form2.is_valid():
            print("1")
            return render(request, 'Lead/Lead.html', context)
        return render(request, 'Accounts/accounts_form.html', context)
        # return render(request,'common/dashboard.html')

    # slug_field = 'account_slug'
    # fields = ['AccountName','address_line1','address_line2','industry','businesscategory','area','city','state','country','pincode','landline','email','website',]
    # def get_success_url(self, request, *args, **kwargs):
    #     print(LeadDetailForm.errors)
    #     context = {'form': Leadform(),
    #
    #                }
    #     return render(request, 'Lead/Lead.html')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        print(self.request.user.id)
        context['book_list'] = User.objects.all()
        context['menu'] = Menu.objects.all()
        context['product'] = Product.objects.all()    #Product.objects.values_list('Product_Name').values()
        # context['IndustryType'] = AllMaster.objects.filter(Field_Name='IndustryType')
        # context['BusinessCategory'] = AllMaster.objects.filter(Field_Name='BusinessCategory')

        return context

    # def post(self, request, *args, **kwargs):
    #     view_all = Lead.objects.all()
    #     if request.method == 'POST':
    #         form = Leadform(request.POST or request.FILES)
    #         if form.is_valid():
    #             temp = form.save(commit=False)
    #             temp.

--------------------------------------------------------------------------------------------------------------
Lead.html
--------------------------------------------------------------------------------------------------------------
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}


<script>
    function myFunction() {
                          var x = document.getElementsByName("Qty").value * document.getElementsByName("Rate").value;
                          $("#amount").text(x.toFixed(2));
                        }
</script>

{% block content1 %}
    
    <div class="container-fluid">
		<p>{{ form.fieldname.errors.as_text }}</p>


        <div class="d-sm-flex align-items-center justify-content-between mb-4 mt-4">
            <h1 class="h3 mb-0 text-gray-800">Leads</h1>
        </div>
		<form action="" method="post" id="leadform" enctype="multipart/form-data" role="form">
		    {% csrf_token %}

            <div class="card o-hidden border-0 shadow-lg my-9">
                <div class="card-body p-4">

{#                    <ul class="nav nav-tabs">#}
{#                      <li class="nav-item">#}
{#                        <a class="nav-link active" data-toggle="tab" href="#home">Lead Info</a>#}
{#                      </li>#}
{#                      <li class="nav-item">#}
{#                        <a class="nav-link" data-toggle="tab" href="#menu1">Product details</a>#}
{#                      </li>#}
{#                      <li class="nav-item">#}
{#                        <a class="nav-link" data-toggle="tab" href="#menu2">Extra details</a>#}
{#                      </li>#}
{#                       <li class="nav-item">#}
{#                          <a class="nav-link" data-toggle="tab" href="#menu3">Extra details</a> #}
{#                       </li> #}
{#                    </ul>#}
{#                    <br/>#}

                    
                    <div class="tab-content">
                      <div class="tab-pane container active" id="home">
                          {% crispy form2  %}
                      </div>

                      <div class="tab-pane container fade" id="menu1">

{#                            <div class="container">#}
{#                                <input type="button" class="btn-primary" id="addrow" value="Add Product" onClick="addRow('dataTable')" />#}
{#                                <b><label id="Gtotal" style="float: right;color: #be2617;  ">  </label></b>#}
{#                                <b><label style="float: right">Grand Total : </label></b>#}
{##}
{#                                <table id="dataTable" class=" table order-list"  style="margin-top:10px ;">#}
{#                                    <div></div>#}
{#                                <tbody>#}
{#                                <tr id='row_0'>#}
{#                                    <p>#}
{##}
{#                                        <td>#}
{#                                            <label>Product</label>#}
{#                                            <select class="form-control" style="width:400px;" name="dropdown">#}
{#                                                    {% for data in product %}#}
{#                                                        <option value="volvo">{{ data.Product_Name }}</option>#}
{#                                                    {% endfor %}#}
{##}
{#                                            </select>#}
{#                                        </td>#}
{#                                        <td>#}
{#                                            <label>Quantity</label>#}
{#                                            <input type="text" required="required" name="qty" class="form-control" oninput="calculate('row_0')">#}
{#                                        </td>#}
{#                                        <td>#}
{#                                            <label for="price">Price</label>#}
{#                                            <input type="text" required="required" class="form-control"  name="price" oninput="calculate('row_0')">#}
{#                                        </td>#}
{#                                        <td>#}
{#                                            <label for="total">Total</label>#}
{#                                            <input type="text"  class="form-control" name="total" id="amount">#}
{#                                        </td>#}
{##}
{#                                        <td>#}
{#                                        <label for="action">Action </label>#}
{#                                        <input type="button" id="del" class="ibtnDel btn btn-md btn-danger" name="del"  onclick="delRow(this)" value="Delete">#}
{#                                        </td>#}
{#                                    </p>#}
{#                                </tr>#}
{#                            </tbody>{#                                <tfoot>#}
{##}
{#                            </table>#}
{#                            </div>#}
                          {% crispy form2 form2.helper_Leaddetail %}
                      </div>
{#                      <div class="tab-pane container fade" id="menu2">#}
{#                        <form>#}
{#                            <div class="form-group">#}
{#                                <label for="action">Lead Assigned </label>#}
{#                                <select class="form-control" style="width:400px;" name="dropdown">#}
{#                                        {% for data in book_list %}#}
{#                                            <option value="volvo">{{ data.username}}</option>#}
{#                                        {% endfor %}#}
{#                                </select>#}
{#                            </div>#}
{#                        </form>#}
{##}
{##}
{#                      </div>#}
                    </div>
                <hr class="sidebar-divider">
                <button type="submit" class="btn btn-success" style="margin-left: 15px;" value="Submit">Save</button>
                <button type="button" class="btn btn-primary" style="margin-left: 15px;" value="Cancel">Cancel</button>
                 </div>




            </div>


        </form>
    </div>
{% endblock content1 %}

**Comment by Miracle619** [comment]
[Leadhtml.txt](https://github.com/django-crispy-forms/django-crispy-forms/files/4514130/Leadhtml.txt)
[leadview.txt](https://github.com/django-crispy-forms/django-crispy-forms/files/4514135/leadview.txt)
[form.txt](https://github.com/django-crispy-forms/django-crispy-forms/files/4514141/form.txt)

**Comment by patagoniapy** [comment]
So what is the issue? Are the forms not appearing at all? Or just not working?

**Comment by Miracle619** [comment]
Form is appearing but if you see the attached screenshot in which i have 2 tab, in 2 tab (i.e 
Product Info) i have to display LeadDetailForm which you can see in form,txt which i have sended you earlier
![gitscreenshot](https://user-images.githubusercontent.com/45958697/80065214-9da2da80-84ee-11ea-858c-f8ad043bf634.png)

**Comment by smithdc1** [comment]
I've had a couple of reads of this and I'm slightly unclear what the issue is and therefore am unable to reproduce. If a minimal example can be provided I'll be more than happy to have a look.
