### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by Salem-Abderaouf** [django-crispy-forms/django-crispy-forms#1025]
Error : Syntax Error 
Reason : an Extra comma **,**
there are more in **bootstrap.py** file and **layout_slice.py file**
https://github.com/django-crispy-forms/django-crispy-forms/blob/38841045b5f72147d38dc3447eb9c9c4fecd260f/crispy_forms/layout.py#L465

**Comment by smithdc1** [comment]
I thought a trailing comma in this case is accepted practice? It's compliant with black code style which this project is using.
