### ISSUE TITLE
Disabled FileField doesn't make ClearableFileInput disable the widget

### ISSUE THREAD

**Issue by cpina** [django-crispy-forms/django-crispy-forms#1027]
* Package version: 2ec7b692f948c25917482f0f723b0332acbd809d
* Django version: 3.0.5
* Python version: 2.7.16
* Template pack: (Optional)

### Description:

I'm creating a form with different disabled fields. One is a FileField and using the new ClearableFileField the field is enabled (both the "Browse" button and the "Clear" checkbox)

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [x] Screenshots
- [x] Actual HTML generated
- [x] Expected HTML
(actual and expected differ by `disabled`)

(Ignore the multi-line link, this will go to another ticket)
It generates:
![file-field](https://user-images.githubusercontent.com/489071/81474938-09808500-9209-11ea-895b-bf1922201ad2.png)

I expected:
![Screenshot_20200509_152357](https://user-images.githubusercontent.com/489071/81474944-2321cc80-9209-11ea-8bb2-c1d15a346d38.png)

This is possible if both the checkbox and the file input had the attribute `disabled=""` (or just `disabled`):
`<input type="checkbox" id="invoices_form-0-file-clear_id" class="custom-control-input" disabled="" name="invoices_form-0-file-clear">`
`<input type="file" class="custom-file-input" name="invoices_form-0-file" disabled="">`

To disable a field in Django:
`                self.fields[field_name].disabled = True`

**Comment by cpina** [comment]
A bit of investigation on where the `disabled` is lost:
https://github.com/django-crispy-forms/django-crispy-forms/pull/1004#issuecomment-626140881
In case that it helps.

**Comment by smithdc1** [comment]
Thanks for raising this.

Note for future self. 

Should be able to access disabled via the widgets attrs. BoundField (build attrs method?!) should add `disabled: true` to the widgets attrs. FileField already tries to render the attrs of the widget...?

**Comment by smithdc1** [comment]
@cpina 

Does this work for you? The button gets disabled but the box isn't greyed out?

https://github.com/django-crispy-forms/django-crispy-forms/pull/1029

Needs a tidy up - there's two changes here. 1 is changing where the `attrs` dict is being picked up from, the other is to add the disabled attribute from the field.

**Comment by cpina** [comment]
@smithdc1 :
Using fd840abea52d8cdeb7ea0004b828e7f6bbbace72:
The "Browse" button is disabled and the box is disabled as well so it looks good (both are "greyed out").

The "Clear" checkbox is not disabled (it should be).

Any time happy to check this here! Thanks very much

**Comment by smithdc1** [comment]
@cpina hey - thanks for the comment. I've now added disabled to the checkbox as well. Can you give it a try? 🤞 

If so I'll then look at the tests.

Thanks

David

**Comment by cpina** [comment]
@smithdc1 - I've used now 31e662630f108309befcd213794ba220650ac34e - Yes, FileField is correctly disabled! :-) (and enabled when it needs to be).

Cheers!
Carles

**Comment by smithdc1** [comment]
Fixed by #1029
