### ISSUE TITLE
FileField Clear Checkbox Alignment

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/django-crispy-forms#1043]
Below is copied from #1041 by @cpina 

I've been using the new, fixed FileField all the time the last days and I really like it.

I wonder only one thing and it's if the "Clear" checkbox should be centered or not when there are multiple lines. Currently in master we have:
![current-01](https://user-images.githubusercontent.com/489071/85211815-17b7da00-b34d-11ea-9db3-d5228e673efe.png)
![current-02](https://user-images.githubusercontent.com/489071/85211817-19819d80-b34d-11ea-9144-9d089e520836.png)

When I saw it (in my application but it's the same case) I wondered if it should look like:
![current-03](https://user-images.githubusercontent.com/489071/85211822-243c3280-b34d-11ea-87b0-257cdf9a7d0b.png)
![current-04](https://user-images.githubusercontent.com/489071/85211823-256d5f80-b34d-11ea-9c89-0c0eb83d8c67.png)

I have no strong opinion... perhaps I'm slightly inclined for the centered one. I've done (having in mind, again, backend dev playing with CSS here!):
![current-05](https://user-images.githubusercontent.com/489071/85211829-3b7b2000-b34d-11ea-84d0-3d49703d18df.png)
I haven't checked if the normal case (shorter current file) keeps working fine.
(I've only added `align-self-center`)

Any opinion on this one?

**Comment by cpina** [comment]
Another question to discuss: would it make sense to have a bit padding on the left of the "clear" checkbox?

In a way the same padding as the one between the vertical line after "Currently" and the first character.

**Comment by smithdc1** [comment]
Hi @cpina 

Firstly I thoroughly enjoyed your talk last night, really fascinating so thanks for sharing your story. 

>  (having in mind, again, backend dev playing with CSS here!)

You are much more experienced than me, this is something I have an interest in and do in my spare time; my day job isn't in IT. :-)

Both of these sound like good ideas.... PR incoming... 🚀
