### ISSUE TITLE
Upgrade To Bootstrap 5

### ISSUE THREAD

**Issue by 9mido** [django-crispy-forms/django-crispy-forms#1048]
https://v5.getbootstrap.com/

In alpha now but better to start early than to wait till the last minute.

**Comment by smithdc1** [comment]
Thanks for the interest

It's coming.... :-) I'll publish what I've got later so others can contribute if there is a strong interest.


But it will be a separate package so I'm closing it as an issue here.

**Comment by 9mido** [comment]
Great to hear thanks!

**Comment by epicserve** [comment]
@smithdc1,

Is there any sort of an ETA on when bootstrap 5 support will be available or any issue to follow so we can know when it's been added?

**Comment by smithdc1** [comment]
Yes! There's a repo here with an early version also available on PyPI  https://github.com/django-crispy-forms/crispy-bootstrap5

Any help testing and reporting of bugs would be appreciated. I did this work on one of the early alpha versions and so I suspect it'll need updating for the beta release. (I think some of the more radical form changes didn't make the beta so hopefully not too much; also any news when a final release is coming?).

**Comment by josh7weaver** [comment]
Regarding Bootstrap final release: I don't think theres any roadmap for moving through the beta process but Bootstrap has said since its beta now there will not be any breaking changes or new features added at this point: https://blog.getbootstrap.com/2020/12/07/bootstrap-5-beta-1/
