### ISSUE TITLE
form_class = 'form-inline' seems doesn't working as expected

### ISSUE THREAD

**Issue by jerinpetergeorge** [django-crispy-forms/django-crispy-forms#1054]
* Package version: `django-crispy-forms==1.9.1`
* Django version: `Django==3.0.6`
* Python version: `Python 3.6.9`
* Template pack: (Optional) `CRISPY_TEMPLATE_PACK = 'bootstrap4'`

### Description:
I have followed the [crispy forms docs](https://django-crispy-forms.readthedocs.io/en/latest/crispy_tag_forms.html#bootstrap3-inline-forms) to create a simple inline form using *bootstarp4*. But it seems the form is not becoming a *"inline"* but a *"horizontal"*.

Here is the code snippet that I have so far along with the screenshot of the rendered web view,

    # models.py
    from django.db import models
    
    
    class InlineTestModel(models.Model):
        name = models.CharField(max_length=20)
        age = models.IntegerField()
        email = models.EmailField()
    
    
    # form_helper.py
    from crispy_forms.helper import FormHelper
    from crispy_forms.layout import Submit
    
    
    class FormHelperBase(FormHelper):
        form_inputs = []
    
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.set_inputs()
    
        def set_inputs(self):
            for form_input in self.form_inputs:
                self.add_input(form_input)
    
    
    class TestInlineFormHelper(FormHelperBase):
        form_class = 'form-inline'
        field_template = 'bootstrap4/layout/inline_field.html'
        layout = Layout(
            'name', 'age', 'email'
        )
        form_inputs = [
            Submit('Save', 'Save', css_class='button white')
        ]
    
    
    # forms.py
    from django import forms
    
    
    class TestInlineForm(forms.ModelForm):
        helper = TestInlineFormHelper()
    
        class Meta:
            model = InlineTestModel
            fields = '__all__'
    
    
    # views.py
    from django.views import generic
    from django.urls import reverse
    
    
    class TestInlineAddView(generic.CreateView):
        model = InlineTestModel
        form_class = TestInlineForm
        template_name = 'app_name/test_inline_add.html'
    
        def get_success_url(self):
            return reverse('app_name:success_url')
```
# template
{% extends 'expenses/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block form_body %}
    <form method="post">{% csrf_token %}
        {% crispy form %}
    </form>
{% endblock %}
```

**Rendered web view**

[![Rendered web view][1]][1]

  [1]: https://i.stack.imgur.com/05ckJ.png

**Comment by smithdc1** [comment]
I've made a custom `crispy-test-project` to test this. This 'works for me'.

I think you need to remove the `<form>` tags from your template to enable crispy-forms to generate them and to add the `form-inline` class via `helper.form_class = 'form-inline'`. Otherwise add `form-inline` manually to your template. 

p.s. may want to use `InlineField` to add spacing. 

https://github.com/smithdc1/crispy-test-project/tree/bs4-inline

![image](https://user-images.githubusercontent.com/39445562/86561406-7342b400-bf58-11ea-82e8-d661c4cc9270.png)

``` python
    helper = FormHelper()
    helper.layout = Layout(
        'text_input_a',
        'text_input_b',
        'text_input_c',
    )
    helper.use_custom_control = True
    helper.form_class = 'form-inline'
    helper.field_template = 'bootstrap4/layout/inline_field.html'
```

**Comment by jerinpetergeorge** [comment]
Removing the **`<form>...</form>`** tags did the trick.

final template will be as (useful for anyone like me :smile: )
<pre><code>{% extends 'expenses/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block form_body %}
    <b>{% crispy form %}</b>
{% endblock %}</code></pre>

@smithdc1 
BTW, did this mentioned anywhere in the doc?, should not use the **_form_** tags? Can I have the reference?

**Comment by smithdc1** [comment]
Hey, yes could be worth a short note in the docs.

**Comment by smithdc1** [comment]
@jerinpetergeorge Opened a PR for this. Appreciate your review if you are able to do so.

**Comment by jerinpetergeorge** [comment]
Thanks.

The **`InlineField(...)`** didn't render the form with the _"element spacing"_ (not sure the term is correct :wink: ), for me. I will create a new issue and PR once I am sure about that...

**Comment by cpina** [comment]
Side note: It seems that `form-inline` is removed from Bootstrap5 (see https://getbootstrap.com/docs/5.0/getting-started/download/ section "Class Updates")
