### ISSUE TITLE
Support attributes with underscores '_'

### ISSUE THREAD

**Issue by vmsp** [django-crispy-forms/django-crispy-forms#1058]
Underscores in the `FormHelper.attrs` are unconditionally converted to dashes (see [here](https://github.com/django-crispy-forms/django-crispy-forms/blob/master/crispy_forms/utils.py#L144)). Could a way be added of supporting underscores, without conversion, as well? Maybe by escaping the character, for example:

```
hello_there -> hello-there
hello__there -> hello_there
```

**Comment by smithdc1** [comment]
Hi @vmsp - Thank you for your comment. 

I'll have a go at giving my thoughts on this. 

I'm _not sure_ about introducing this change, I'd suggest trying to explore overriding this function. This function is fairly old within `crispy-forms` and so personally I'd be apprehensive about changing it. At this point, the changes are all in the templates, I am not sure the last time we changed any of the API.
