### ISSUE TITLE
Bootstrap 4 Radio Validation

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [django-crispy-forms/django-crispy-forms#1083]
* Package version: 1.9.2
* Django version: 3.0.2
* Python version: 3.7.3
* Template pack: (Optional)

### Description:

I feel like I'm missing something, after reading through the various commits and issues related to #794 . It seems that line 8 of `crispy_forms/templates/bootstrap4/layout/radioselect.html` is still missing the `{% if field.field.required %}required {% endif %}` line that allows Bootstrap's JS validation popup to appear. 

Am I going about this wrong? Thanks for any suggestions!

**Comment by smithdc1** [comment]
What happens if you render it with standard Django (that is without crispy-forms)? Does the `required` attribute get rendered?

I'm expecting that the attrs (which is in the template) to render the `required` attribute. That is, we don't need to manually add it.

**Comment by geoffrey-eisenbarth** [comment]
Thanks for the quick response! Great idea, I removed the crispy tag and rendered it normally, and it did include the "required" attribute.

Previously, I had the field defined as:
```
referral = forms.ChoiceField(
 choices=REFERRAL_CHOICES,
 required=True,
 widget=forms.RadioSelect()
)
```

This works for vanilla Django forms (i.e., has the "required" attribute), but not for crispy forms (at least, in my testing). However, if I add ``attrs={'required': 'required'}`` to ``forms.RadioSelect()`` everything works as it should with crispy-forms.

Not sure if this is really a bug, or what. I have an innocent enough workaround for now, so feel free to close this issue if you don't think it needs addressing, or if somehow this is the desired functionality. 

Thanks!

**Comment by smithdc1** [comment]
Thanks. The only thing we need to be careful with is having valid HTML. I think for multiple checkbox we can't have required iirc. Should be fine for radio.

I'll have a deeper look when I get time.

**Comment by smithdc1** [comment]
This came up in #1155. The fix for grouped inputs will also add the `required` attribute for radio's. 

@geoffrey-eisenbarth did you want to take a look at that patch to confirm it works for you?

**Comment by geoffrey-eisenbarth** [comment]
@smithdc1 awesome, thanks for your work towards this! Looks great!

**Comment by smithdc1** [comment]
Thanks for checking 👍
