### ISSUE TITLE
Fix class input-group for Prepended_appended_text.html (Bootstrap4)

### ISSUE THREAD

**Issue by gkieninger** [django-crispy-forms/django-crispy-forms#1094]
* Package version: 1.10.0
* Django version: 3.1.4
* Python version: 3.8
* Template pack: (Optional)

### Description:

I want to make the input smaller, so I need 'input-group input-group-sm' for the prepended/appended input, but as far as I can see the class 'input-group' is fixed in prepended_appended_text.html line 15.
Is there any easy way to make this work without my javascript ($('.input-group').addClass('input-group-sm')?

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [ ] Screenshots
- [x ] Actual HTML generated

`<div id="div_id_vat_id" class="form-group col-12"> <label for="id_vat_id" class="">
                UID-Nummer
            </label> <div class=""> <div class="input-group"> <input type="text" name="vat_id" value="" maxlength="15" class="textinput textInput form-control" id="id_vat_id"> <div class="input-group-append"> <span class="input-group-text"><i class="fas fa-search mr-2" aria-hidden="true"></i><span>Keine Prüfung : </span></span> </div> </div> </div> </div>`
- [x] Expected HTML
`<div id="div_id_vat_id" class="form-group col-12"> <label for="id_vat_id" class="">
                UID-Nummer
            </label> <div class=""> <div class="input-group input-group-sm"> <input type="text" name="vat_id" value="" maxlength="15" class="textinput textInput form-control" id="id_vat_id"> <div class="input-group-append"> <span class="input-group-text"><i class="fas fa-search mr-2" aria-hidden="true"></i><span>Keine Prüfung : </span></span> </div> </div> </div> </div>`

**Comment by smithdc1** [comment]
Hi @gkieninger.

This issue was opened recently with #1071. There are some comments on a work arround there. 

#1080 is looking to fix this issue. I think we're nearly there with it. :crossed_fingers:

**Comment by smithdc1** [comment]
Hi @gkieninger https://github.com/django-crispy-forms/django-crispy-forms/pull/1114 should fix your issue. The patch has been trimmed down to just the prepended and appended inputs and is now waiting for review. If you could confirm it fixes your issue that would be super helpful.
