### ISSUE TITLE
Fix a11y errors for bootstrap 4

### ISSUE THREAD

**Issue by yuqiuw** [django-crispy-forms/django-crispy-forms#1095]
* Package version:
* Django version:
* Python version:
* Template pack: (Optional)

### Description:

This tracks testing Django form components in use by Incubator for accessibility issues and remedying these issues. 

Reference requirements for Django form: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/form.html

### Expected results:

The code should solve all a11y problems detected by Axe and Wave

**Comment by yuqiuw** [comment]
Fixed in https://github.com/django-crispy-forms/django-crispy-forms/pull/1096

**Comment by smithdc1** [comment]
I'm keen to improve accessibility issues in the template packs.

I'll close this for now as this is a generic accessibility request. I'd prefer to have issues targeting specific issues (e.g. https://github.com/django-crispy-forms/crispy-bootstrap5/issues/152) that can be improved. That'll allow easier judgement of when an issue is resolved.
