### ISSUE TITLE
[Possible bug] Unexpected HTML rendering of help text.

### ISSUE THREAD

**Issue by abaza738** [django-crispy-forms/django-crispy-forms#1100]
* Package version: 1.9.2
* Django version: 2.2.14
* Python version: 3.8.3

### Description

When rendering a `help_text` field that is an unordered list `<ul>`, the whole list is rendered between two `<p>` tags.  
The first of which has the expected ID and class  `<p id="hint-id-password1" class="help-block"></p>` but is closed before the actual list is rendered; while the second is an empty paragraph tag `<p></p>`.  
I would assume that the expected behaviour is rendering it inside the helper block (first tag).  
The difference is visible when trying to customise the CSS for class `help-block`, as shown in the screenshot below.

### Details

- [x] Example Django Crispy Forms code
    ```html
    <div class="row">
        <div class="col-md">{{ form.password1|as_crispy_field }}</div>
    </div>
- [x] Screenshots
  
![3](https://user-images.githubusercontent.com/50132270/102495500-d3e52980-407e-11eb-935c-8c1ec223decd.png)

- [x] Actual HTML generated
  ```html
    <p id="hint_id_password1" class="help-block"></p>
    <ul>
      <li>Your password can't be too similar to your other personal information.</li>
      <li>Your password must contain at least 8 characters.</li>
      <li>Your password can't be a commonly used password.</li>
      <li>Your password can't be entirely numeric.</li>
    </ul>
    <p></p>
- [x] Expected HTML
   ```html
    <p id="hint_id_password1" class="help-block">
      <ul>
        <li>Your password can't be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can't be a commonly used password.</li>
        <li>Your password can't be entirely numeric.</li>
      </ul>
    </p>

**Comment by smithdc1** [comment]
Hi there hope you are well. I have a couple of questions. 

Which template pack are you using?

Can you confirm you have `CRISPY_TEMPLATE_PACK` in your settings file setup correctly?

**Comment by abaza738** [comment]
> 
> 
> Hi there hope you are well. I have a couple of questions.
> 
> Which template pack are you using?
> 
> Can you confirm you have `CRISPY_TEMPLATE_PACK` in your settings file setup correctly?

I do not have it explicitly defined, so I'm guessing it defaults to Bootstrap 4, which is what I'm using with my project.  
Sorry, I overlooked mentioning that in the main post.

**Comment by smithdc1** [comment]
I think it defaults to the bootstrap template pack (that's bootstrap version 2).

Could you try updating the setting to `bootstrap4` and see if that helps?

**Comment by abaza738** [comment]
That helped. Many thanks David!
Again, this probably did not need an issue opened, so apologies for the inconvenience. I better read more carefully!

**Comment by smithdc1** [comment]
Glad that worked. 👍
