### ISSUE TITLE
New template pack for forms (MDB)

### ISSUE THREAD

**Issue by MrWormHole** [django-crispy-forms/django-crispy-forms#1102]
Are there any plans to add a new template pack like Material Design for Bootstrap? https://v1.mdbootstrap.com/docs/b4/jquery/forms/basic/

It is actually bootstrap 4 compatible in some cases, but pro version(it provides different looks for the form) requires a bit of work since it is not included in bootstrap 4. They have their own form builder as well on their website so i don't know if it is a good idea to bring this up here.

**Comment by smithdc1** [comment]
@MrWormHole I'm afraid I've not got any plans to look at this, as I've got a few other things I want to work on during 2021. (One of them being improving the BS5 template pack).

If it's mostly the same I'd encourage you to have a look at building a template pack yourself it's not 'too' hard. There's some documentation on it on RTD and also have a look at the crispy-bootstrap5 repo for inspiration. Happy to try and answer questions if you run into difficulty.

**Comment by carltongibson** [comment]
Yes, this would be out of scope for the main package. 

But as @smithdc1 says, you're welcome and encouraged to create the template pack yourself. If you put it on GitHub you're likely to find others using it to, which can help maintaining it.

**Comment by shawnngtq** [comment]
Understand it's out of scope, commenting to follow if anyone is building MDB template pack.

@MrWormHole , do ping me if you already found a solution, thanks 😁
