### ISSUE TITLE
Not able to overwrite Submit button default css_class

### ISSUE THREAD

**Issue by iGoosiatin** [django-crispy-forms/django-crispy-forms#1103]
* Package version: 1.10.0
* Django version: 3.0.5
* Python version: 3.9.0

### Description:

Not able to overwrite Submit button default css_class. By default it always equal to "btn btn-primary" plus what you specified.

Trying:
```python
Submit('submit', 'Upload & Process', css_class="btn btn-outline-dark btn-block btn-lg")
```

Result:
```html
  <input type="submit" name="submit" value="Upload & Process" class="btn btn-primary btn btn-outline-dark btn-block btn-lg" id="submit-id-submit" />
```

Expected HTML:
```html
<input type="submit" name="submit" value="Upload & Process" class=" btn btn-outline-dark btn-block btn-lg" id="submit-id-submit"/>
```

**Comment by smithdc1** [comment]
Can you use `Button` in place of `Submit` here? The difference is that `Button` only comes with the `btn` class. 

https://github.com/django-crispy-forms/django-crispy-forms/blob/master/crispy_forms/layout.py#L217

**Comment by iGoosiatin** [comment]
Tried using `Button`:

```python
Button('submit', 'Upload & Process', css_class="btn-outline-dark btn-block btn-lg", type='submit')
```

In that case I get HTML:
```html
 <input type="button" name="submit" value="Upload & Process" class="btn btn-outline-dark btn-block btn-lg" id="button-id-submit" type="submit" />
```

CSS classes are fine, however `type` turns `"button"`, and I can't change it.

**Comment by smithdc1** [comment]
Ah I see. In that case, there are a few options. You could create your own button class or you could adjust the css classes (or type) manually on the field. Here's an example of changing the css classes on the Submit button. 

1. Create an instance of the Submit Button, and manually change the css classes (in `field_classes`) once it's been initiated. 
``` python
submit = Submit('submit', 'Upload & Process')
submit.field_classes = "btn btn-outline-dark btn-block btn-lg"
```

2. Add the instance to the `Layout`
``` python
helper = FormHelper()
helper.layout = Layout(
        [...] # form fields here
        submit,
   
)
```

3. Output HTML 
``` html
<input type="submit" name="submit" value="Upload &amp; Process" class="btn btn-outline-dark btn-block btn-lg" id="submit-id-submit">
```

**Comment by iGoosiatin** [comment]
> Ah I see. In that case, there are a few options. You could create your own button class or you could adjust the css classes (or type) manually on the field. Here's an example of changing the css classes on the Submit button.
> 
> 1. Create an instance of the Submit Button, and manually change the css classes (in `field_classes`) once it's been initiated.
> 
> ```python
> submit = Submit('submit', 'Upload & Process')
> submit.field_classes = "btn btn-outline-dark btn-block btn-lg"
> ```
> 
> 1. Add the instance to the `Layout`
> 
> ```python
> helper = FormHelper()
> helper.layout = Layout(
>         [...] # form fields here
>         submit,
>    
> )
> ```
> 
> 1. Output HTML
> 
> ```
> <input type="submit" name="submit" value="Upload &amp; Process" class="btn btn-outline-dark btn-block btn-lg" id="submit-id-submit">
> ```

That solves my problem. We can close the issue.
Just a question - why do we need to hardcore `btn-primary` class for `Submit` button?

**Comment by smithdc1** [comment]
Glad that helped. 

Not too sure on this history here. I think its an opinionated element. It helps get setup quickly with an ok looking form, covering the most likely use case. If you want more customisation then that's available too.
