### ISSUE TITLE
Support for Halfmoon

### ISSUE THREAD

**Issue by Karam-DEV** [django-crispy-forms/django-crispy-forms#1104]
Hi, Can you add support for [halfmoon](https://www.gethalfmoon.com/) framework

**Comment by smithdc1** [comment]
Hi @Karam-DEV 

A new template pack is out of scope for this package, see a recent discussion at #1102.

I'd encourage you to create your own crispy-template pack and put it on GitHub, it will let folk come along and help you. 

Good luck :-)
