### ISSUE TITLE
Multi-selection widgets inheriting SelectMultiple vice MultiWidget do not display correctly for bs4

### ISSUE THREAD

**Issue by OmenApps** [django-crispy-forms/django-crispy-forms#1105]
* Package version: 1.10.0
* Django version: 3.1
* Python version: 3.9
* Template pack: bs4

### Description:

Not sure if this warrants a PR, since it's so specific to a 3rd party widget, but would love feedback.

When rendering a multi select using [django-autocomplete-light's](https://github.com/yourlabs/django-autocomplete-light/) ModelSelect2Multiple widget (which inherits forms.SelectMultiple among other classes, but NOT from forms.MultiWidget), the 'form-control' css-class is appended, causing the field to display incorrectly when the number of selected items overflows the controls bounds. Instead of expanding to fit the content, the additional selections start appearing outside of the field.

I propose that templatetags.crispy_forms_field should be modified as follows:

Currently
```
@register.filter
def is_multivalue(field):
    return isinstance(field.field.widget, forms.MultiWidget)
```

![With_form-control](https://user-images.githubusercontent.com/37490393/103310827-91104380-49e6-11eb-9cb1-dcb267f347cc.png)

Modified
```
@register.filter
def is_multivalue(field):
    return isinstance(field.field.widget, forms.MultiWidget) or isinstance(field.field.widget, forms.SelectMultiple)
```

![Without_form-control](https://user-images.githubusercontent.com/37490393/103310836-966d8e00-49e6-11eb-8019-93740a59b071.png)

This will prevent the render method in class CrispyFieldNode in that same file from appending the css_class "form-control" if the widget is any type of multiple-selection.

Are there other known cases that this would impact negatively?

**Comment by smithdc1** [comment]
I think we want to add `form-control` to select multiple inputs? See [docs](https://getbootstrap.com/docs/4.0/components/forms/#form-controls).

I think if you have a custom widget then the guidance here should be to have a custom template for it. See [docs](https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-layout-objects-templates).

Hope this helps.

**Comment by OmenApps** [comment]
Sounds good.
