### ISSUE TITLE
Bootstrap 5 support and errors for custom floatfield

### ISSUE THREAD

**Issue by millerthegorilla** [django-crispy-forms/django-crispy-forms#1109]
* Package version: 1.110
* Django version: 3.1.5
* Python version: 3.9
* Template pack: (Optional)

### Description:
Hi, will you be introducing a template for bootstrap5.   I would like to use a floatfield for my forms.  So far I have created a custom floatfield following the documentation for custom fields.   I have a floatfield.html with : 
```
{% load crispy_forms_field %}
<div class="form-floating mb-3">
    {% crispy_field field %}
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
</div>
```
It works fine (with fields.py defined as per docs).   However, I can't get validation errors to show.   In the form with this field in, I validate the email using a clean_email function, which is:
```
   def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
        except User.DoesNotExist:
            return email          
        self.add_error('email', 'Error! That email already exists!')
        self.valid = False
        return email
```
So the error is added, and shows ok if I use a standard form field.   Is there a way to include the field error by editing the custom floating field's html template?

I have tried the following:
```
{% load crispy_forms_field %}
<div class="form-floating mb-3">
    {% crispy_field field %}
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% if field.errors %}
	    {% for error in field.errors %}
	        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="invalid-feedback"><strong>{{ error }}</strong></span>
	    {% endfor %}
	{% endif %}
	{% if field.help_text %}
	    {% if help_text_inline %}
	        <span id="hint_{{ field.auto_id }}" class="text-muted">{{ field.help_text|safe }}</span>
	    {% else %}
	        <small id="hint_{{ field.auto_id }}" class="form-text text-muted">{{ field.help_text|safe }}</small>
	    {% endif %}
	{% endif %}
</div>
```
but in either case the same html is generated:
```
<div class="form-floating mb-3"> 
    <input type="email" name="email" value="bob@bob.com" class="emailinput form-control is-invalid" required="" id="id_email">       
    <label for="id_email">Email</label>
</div>
```
when I want to have the following after the field:
```
<span id="error_1_id_email" class="invalid-feedback"><strong>Error! That email already exists!</strong></span>
```
screenshot of floatfields here...    https://ibb.co/FbQS9n7

Many thanks in advance...

### Preferably also include:

- [x ] Example Django Crispy Forms code
- [ x] Screenshots
- [ x] Actual HTML generated
- [ x] Expected HTML

**Comment by millerthegorilla** [comment]
I know I need to rename the floatfield to something else as not to clash with django's numeric FloatField

**Comment by millerthegorilla** [comment]
My mistake, I had a floatfield.html defined in another app, and django was selecting that one instead.  It works fine now.
```
{% load crispy_forms_field %}
<div class="form-floating mb-3 has-validation">
    {% crispy_field field required %}
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    <div class="invalid-feedback">
	    {% if field.errors %}
		    {% for error in field.errors %}
		        <span id="error_{{ forloop.counter }}_{{ field.auto_id }}"><strong>{{ error }}</strong></span>
		    {% endfor %}
		{% endif %}
    </div>
</div>
```

**Comment by millerthegorilla** [comment]
Do you have any plans for a Bootstrap 5 Template pack?

**Comment by smithdc1** [comment]
Support for bootstrap 5 will be in a separate package. Heres the repo and there is also a version on PyPI.

https://github.com/django-crispy-forms/crispy-bootstrap5

I've opened an issue for floating labels but not quite sure what the solution looks like. Any thoughts there would be welcomed.

**Comment by millerthegorilla** [comment]
Thanks, I have added a comment to your opened issue at https://github.com/django-crispy-forms/crispy-bootstrap5/issues/14
