### ISSUE TITLE
Documentation for latest and stable in readthedocs is not updated

### ISSUE THREAD

**Issue by cpina** [django-crispy-forms/django-crispy-forms#1115]
I usually end up in the Read the Docs django-crispy-forms documentation for "latest": https://django-crispy-forms.readthedocs.io/en/latest/

For example: https://django-crispy-forms.readthedocs.io/en/latest/install.html

The last changes in the documentation (before 1.11.0) are not available there. Easy to see checking the copyright year (see the footer) or the branch in the `pip install` command (it should be `master` not `dev`).

I see that the changes are available via (changing the branch on the bottom-left of read the docs):
https://django-crispy-forms.readthedocs.io/en/1.11.0/install.html

But not available on stable:
https://django-crispy-forms.readthedocs.io/en/stable/install.html

Or latest:
https://django-crispy-forms.readthedocs.io/en/latest/install.html

**Comment by smithdc1** [comment]
hmm :thinking: 

![image](https://user-images.githubusercontent.com/39445562/107854983-93ecb980-6e17-11eb-8e38-d4d3136a2534.png)

Odd that the [layouts](https://django-crispy-forms.readthedocs.io/en/stable/layouts.html) page is showing the correct commit/version but as you say the install page is still showing the old version. 

Could this be some kind of caching issue at RTD?

**Comment by smithdc1** [comment]
@cpina -- I looked again this morning and it looks ok to me now. Can you confirm?

**Comment by cpina** [comment]
Ha, now https://django-crispy-forms.readthedocs.io/en/stable/install.html is ok (it wasn't yesterday) and https://django-crispy-forms.readthedocs.io/en/latest/install.html is still old.

Strange because they are not recent changes... but it looks like something on RTD side.

**Comment by smithdc1** [comment]
🤷‍♀️

**Comment by cpina** [comment]
Looked again now and latest is still old for me. Checking the commit (or just copyright year) in: https://django-crispy-forms.readthedocs.io/en/latest/install.html using different browsers and even different connections from different countries.

Does the "latest" look good to you?

**Comment by smithdc1** [comment]
Let's see what happens after #1117

**Comment by smithdc1** [comment]
I've just had a look and stable / latest and 1.11.1 are all showing the same version.

We could probably drop one (or more) of stable / latest / 1.11.1 as they are all the same version. 

Shall we hide the latest as we don't really push docs versions between releases?

**Comment by cpina** [comment]
Ha! For me they are all good now (latest version).

If we drop one of them: do you know if Read the Docs is going to do a redirect to another one? My second entry if I Google for "django crispy forms" is https://django-crispy-forms.readthedocs.io/en/latest/install.html - it would be good if they redirected it to stable. If I go to https://django-crispy-forms.readthedocs.io/en/something_does_not_exist/install.html it shows an error... I don't know which options are in RTD for handling this... or if Google will just stop showing the latest in a few days.

**Comment by sambler** [comment]
The content on Read The Docs continues to fall behind.
 Current release is 1.14.0, RTD has up to 1.11.1

Reading the installation page I followed the Uni-form link to see "Uni-form no longer lives here". This url fix was committed over 12 months ago #1161 .

I am guessing that the RTD config may need updating or that RTD needs to be re-authorized to access the github repo so that it can update on commits.

**Comment by smithdc1** [comment]
https://readthedocs.org/projects/django-crispy-forms/builds/

Thanks for the report. Builds are working again now.
