### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ghost** [django-crispy-forms/django-crispy-forms#112]
Hello

Is it possible to use permissions with django-crispy-forms?

I know you can put template style permissions {% if user.is_staff %} in HTML() but the {% endif %} has to close in the same HTML().

Ideally I would like to choose whether to display something like this in my views.py:

if not user.is_staff:
  form.helper.layout.pop(0)

This should remove a field that I wish to be hidden. Or better still a way to remove a nested field inside a layout.

Thank you for any assistance

**Comment by claytondaley** [comment]
Did you successfully implement this?  Is it publicly accessible?
