### ISSUE TITLE
Add __init__ docstrings to FormHelper

### ISSUE THREAD

**Issue by NBajanca** [django-crispy-forms/django-crispy-forms#1125]
* Package version: 1.11.1
* Django version: 3.1.7
* Python version: 3.8
* Template pack: bootstrap 4

### Description:

I'm new to django-crispy-forms, and doing ``FormHelper()`` in an IDE suggested that I add the ``form`` argument, which I did (after all, I had the object). There is no docs for the ``form`` field in ``__init__ `` so I had no way of knowing the ramifications. 

I ended up lost while trying to add a field programmatically ([SO question](https://stackoverflow.com/q/66615506/4470542)) and when I went to the ``FormField`` code, I understood that the ``form`` field is used to generate the ``Layout``. I don't think this is very intuitive because it is an effect you are not expecting (because it is not documented).

I suggest adding ``__init__`` docstrings to FormHelper, for the ``form`` field. I don't know if I would have read them, but if they were, I wouldn't complain ;)

Taking into account that this is Django, it would also be awesome to have some docs (or at least an example) on how to use FormHelper with Django's class-based views. There is no mention of it, but CreateView and UpdateView automatically generate forms from the object’s model class (unless a form is specified). I guess this is a feature used by several developers.

It goes without saying, thank you for your work with this package!

**Comment by smithdc1** [comment]
@carltongibson -- could I ask for your view here. 

This first part of this request is to add some docs to the `__init__` of  `FormHelper`.

There is copious documentation on the class itself and guidance I have read (Google's style guide) says to document the class or the `__init__` but not both. 

Having said that I can understand folk using `FormHelper()` in their code and IDE would miss the docs on the class itself. 

My inclination would be to say "wontfix". 

The second part of the ask to give some guidance for class based views seems reasonable. (I think we should be able to point to the relavent section of the Django docs).

**Comment by smithdc1** [comment]
In #1210 I added more documentation to the class doc string. VSCode now shows that when creating a new instance of the class.  It therefore seems that VSCode (atleast) can pick up doc strings from either `__init__` or the class itself. 

On the basis, I'll therefore close this issue.
