### ISSUE TITLE
how to use bootstrap5

### ISSUE THREAD

**Issue by withrvr** [django-crispy-forms/django-crispy-forms#1133]
https://django-crispy-forms.readthedocs.io/en/latest/

because there is no info here in the doc
how to use bootstrap5

**Comment by smithdc1** [comment]
Yes. I think a note pointing folk at the crispy-bootstrap5 repo would be useful. 

Would you be up for a PR with the doc changes? Would a small note on the readme suffice or do you think we need to put it on rtd as well?

**Comment by withrvr** [comment]
Ya there should be some thing in the documentations ..... and the main GitHub readme also
that "crispy_bootstrap5" has been released
