### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/django-crispy-forms#1139]
Hi @carltongibson -- I think you've got more experience here. Do I just edit the name of the branch on the main `code` tab? (I was expecting to find something in "settings" but I couldn't see anything there)

**Comment by carltongibson** [comment]
Go here: https://github.com/django-crispy-forms/django-crispy-forms/settings/branches 
Click the little pencil. 
GH is quite good at retargeting PRs and such.

**Comment by justinmayer** [comment]
Also useful: https://docs.github.com/en/github/administering-a-repository/renaming-a-branch

Once the change has been made, [local clones need to be updated to the new branch name](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes).

**Comment by smithdc1** [comment]
I've made the change. Thanks Both :-)
