### ISSUE TITLE
[suggestion] "django-crispy" package on Pypi is outdated and should be removed from Pypi

### ISSUE THREAD

**Issue by gustavklopp** [django-crispy-forms/django-crispy-forms#1145]
It's already happened to me that I install one instead of the other since there are 2 versions on Pypi:
- **django-crispy-forms**: it's the updated version, on **1.11.2** currently. https://pypi.org/project/django-crispy-forms/
- **django-crispy**: it's the outdated version (same maintainer) but on **1.8.1**. https://pypi.org/project/django-crispy/

I've already seen other people got confused by these 2 versions. The outdated doesn't work with the current version of Django anymore.

**Comment by smithdc1** [comment]
Hey @gustavklopp -- Thank for the heads-up here. 👍 

**Django-crispy** wasn't owned by us (even though it looked identical(!)); however, we've claimed the name and "yanked" the package that was uploaded. I'm hoping this should avoid folk getting the wrong package for now.

We'll look at publishing a stub pacakage refering folk to the correct one in due course.

**Comment by gustavklopp** [comment]
Thanks a lot for the answer! Great to have clarified this.
Keep up the good work!
