### ISSUE TITLE
Missing documentation for Bootstrap-4 inline forms.

### ISSUE THREAD

**Issue by TareqMonwer** [django-crispy-forms/django-crispy-forms#1148]
* Package version: 1.11.1
* Django version: 3.1
* Python version: 3.9
* Template pack: Bootstrap4

### Description:

I was trying to implement inline forms with bootstrap4. I  found documentation only for bootstrap3. But, the package has support for bootstrap4 as well, which IMHO should be mentioned in the docs.

### Preferably also include:
[Docs URL for Bootstrap3](https://django-crispy-forms.readthedocs.io/en/1.11.1/crispy_tag_forms.html?highlight=inline#bootstrap3-inline-forms)
![image](https://user-images.githubusercontent.com/33314452/116620319-7b466700-a963-11eb-8f0e-6cbb73b423f4.png)

**Comment by smithdc1** [comment]
Yes, I think we can generalise here by dropping the "3". This is the same across all of the bootstrap template packs. 

You'll you be in the market to open up a PR to make the amends?

**Comment by TareqMonwer** [comment]
Sure, I'll open up a PR ASAP :)
