### ISSUE TITLE
Use Bootstrap 5

### ISSUE THREAD

**Issue by samarmohan** [django-crispy-forms/django-crispy-forms#1150]
Migrate to Bootstrap 5 because it is now officially out. Pretty self explanatory

**Comment by smithdc1** [comment]
Sure, please see. https://github.com/django-crispy-forms/crispy-bootstrap5

**Comment by pickfire** [comment]
Why should it be kept as a separate repository instead of including it with crispy forms like bootstrap 4 and the rest?

**Comment by smithdc1** [comment]
We've had an asking for a long time to split the template packs out of core. See the project linked below. 

Ultimately the goal is to help the projects become more maintainable. For example there's features in the tailwind packs that wouldn't be of benefit to other packs, likewise in the bs5 pack we've added support for floating fields which is only for bootstrap 5.

Hope that helps. 

https://github.com/django-crispy-forms/django-crispy-forms/projects

**Comment by Saul-BT** [comment]
It would be great to add this information in [the docs](https://django-crispy-forms.readthedocs.io/en/latest/install.html#template-packs).

Is someone working on that?

Btw thanks for your help @smithdc1 😄

**Comment by smithdc1** [comment]
> Is someone working on that?

Yes, we should add it . PRs welcome 👍
