### ISSUE TITLE
Performance Issues with FormHelper. Form Rendering increases from 7 seconds to 1.5 minutes using Crispy

### ISSUE THREAD

**Issue by StevenMapes** [django-crispy-forms/django-crispy-forms#1177]
* Package version: 1.12.0
* Django version: 3.2.5
* Python version: 3.8
* Template pack: Bootstrap4

### Description:

I've been using Crispy for about 6 years now and whilst I've accepted some increased performance overheads today I've hit a use where the form rendering increases from 7 seconds using `{{ form }}` to 15-17 seconds using `{% crispy form %}` and then to 
90 seconds when using `{% crispy form form_helper %}`.

In my case I am using it with a formset of 38 elements with each form having 12 fields.

Below is the form and formset (field names changed as I can't share those due to the nature of the project

```
class ExampleForm(Form):
    """To be used for a formset"""

    field_1 = CharField(required=True, min_length=1, widget=HiddenInput())
    field_2 = CharField(required=True, min_length=1, widget=HiddenInput())
    field_3 = CharField(required=False, min_length=10, max_length=12)
    field_4 = CharField(required=False, min_length=10, max_length=16)
    field_5 = IntegerField(required=True)
    field_6 = IntegerField(required=False)
    field_7 = CharField(required=False, max_length=1, label="D/F")
    field_8 = CharField(required=False, max_length=12)
    field_9 = IntegerField(required=False)
    field_10 = FloatField(required=False, min_value=0)
    field_11 = FloatField(required=False, min_value=0)
    field_12 = CharField(required=False, disabled=True, min_length=1, max_length=1000)


class ExampleFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.form_method = 'post'
        self.form_show_labels = False
        self.form_tag = False
        self.layout = Layout(
            Div(
                Div(
                    'field_1',
                    'field_2',
                    'field_3',
                    css_class="col",
                ),
                Div(
                    'field_4',
                    css_class="col",
                ),
                Div(
                    'field_5',
                    css_class="col",
                ),
                Div(
                    'field_6',
                    css_class="col",
                ),
                Div(
                    'field_7',
                    css_class="col",
                ),
                Div(
                    'field_8',
                    css_class="col",
                ),
                Div(
                    'field_9',
                    css_class="col",
                ),
                Div(
                    'field_10',
                    css_class="col",
                ),
                Div(
                    'field_11',
                    css_class="col",
                ),
                css_class="row"
            ),
            Div(
                Div(
                    'field_12',
                    css_class="col-12"
                ),
                css_class="row"
            ),
        )
        self.render_required_fields = True
```

**Comment by smithdc1** [comment]
Thanks for the report. 

Clearly this isn't acceptable. However, I'm strugling to reproduce. I've put together the benchmark listed below and while I'm seeing some slow down, it's not of the same magnitude. 

I also feel I've exagerated the last benchmark where the helper is being created during the benchmark whereas the form I've put outside of the benchmark loop.

Really happy to investigate this if you can help me pin down a reproducable example. 

```
.....................
form: Mean +- std dev: 104 ms +- 9 ms
.....................
crispy_filter: Mean +- std dev: 211 ms +- 11 ms
.....................
crispy_form: Mean +- std dev: 267 ms +- 16 ms
```

https://gist.github.com/smithdc1/0659b5eec593e0160568a4d71ceb0019

**Comment by StevenMapes** [comment]
Yeah you're right. Now I've taken the code out of the view and template and into three tests which produce these sorts of times

No Crispy = 0.916746
Without Helper = 1.963282
With Helper = 3.582032

Which is interesting as the tests mimick the main code I changed

I've put up my Django test case along with a large sample JSON that I was using https://gist.github.com/StevenMapes/491e66a7118c8b50cd1fe9da03aae69a

The only real difference from this and the view is this uses Template.render and Context where as the view was using render() with more complex templates but the only code that changed between my "real world usage" was the form tag.  In the end took Crispy out and manually rendered the form so it appeared the same as the Crispy Bootstrap layout and that has solved the issue for my client as now the view returns in just over 1 second

**Comment by smithdc1** [comment]
I'm guessing it will be impacted by the _large_ number of templates being rendered here. I count more than 20 for each form, so potentially _hundreds_ of templates being rendered across a formset. 

This would explain why a manually rendered form would be far quicker? 

I'm not immediately sure what we could do here, potentially recommend the tabular inline formset could help (it would avoid all of the 'divs'), but may not be suitable if a certain layout is desired. 

Final thought is presumably you had the cached template loader in play? (A Google search showed someone years ago having this issue).

Hmmm. A bit tricky this one.

**Comment by StevenMapes** [comment]
Yeah, it may be best just to add a note somewhere I guess in the
documentation but on reflection I agree that it'll be hard to fix without
being very specific to the desired layout

**Comment by smithdc1** [comment]
One thing to note is that Django currently uses strings to build its forms. There's is a PR to move to a template based render for a better API. However, it is slower and my benchmark showed it to be 2x slower. Therefore the 'no crispy' to 'no helper' benchmarks are looking competitive. 

It's only when we add helper and more templates we see a slow down, but that's a feels fairly small additional overhead given the increase in complexity.

**Comment by smithdc1** [comment]
I'll close this for now, but really happy to open it again and look at in more detail if there is a reproduceable example.
