### ISSUE TITLE
Support form wizard

### ISSUE THREAD

**Issue by omansion** [django-crispy-forms/django-crispy-forms#118]
Hi,

It would be nice if django-crispy-forms could handle [form wizards](https://docs.djangoproject.com/en/dev/ref/contrib/formtools/form-wizard/) this way :

``` python
{% crispy wizard helper %}
```

Thanks for this great lib!

Olivier

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
