### ISSUE TITLE
allow to pass a template object to function render_field

### ISSUE THREAD

**Issue by kverdecia** [django-crispy-forms/django-crispy-forms#1185]
I've an use case where I need to pass the template source code instead of the template path. Looking into the code I think this can be easyly done if it would be able to path a `django.template.Template` object to the function `crispy_forms.utils.render_fields`. I push a pull request with this.

**Comment by smithdc1** [comment]
Hey -- apologies it has taken a while to respond here. 

Could you explain in more detail about your use case. It seems unusual to pass in a `Template` object. Django's form's and widgets all use the template name as a string as an argument to their render methods. e.g. https://docs.djangoproject.com/en/4.0/ref/forms/api/#render

**Comment by smithdc1** [comment]
Happy to take a look at this if it's picked up again at some point in the future.
