### ISSUE TITLE
Q: Slicing by field names

### ISSUE THREAD

**Issue by interDist** [django-crispy-forms/django-crispy-forms#1187]
I would like to take a slice of the layout by using the names of the form fields, and not just indices. After experimentation, I came up with: 

    LayoutSlice(self.helper.layout, self.helper['field_one'].slice + self.helper['field_two'].slice)

This feels hacky and relying on internal APIs. But I did not find a public API that would allow achieving the same. Is this the only way?

**Comment by smithdc1** [comment]
I've had a look at this a couple of times and not found an easy way to do this. Also I'm not sure it's that simple to change the API to add this feature either. 

Happy to take a look at a PR if someone can find a more acceptable solution than I could!
