### ISSUE TITLE
RadioSelect 'class' attrs not being applied

### ISSUE THREAD

**Issue by nigelcopley** [django-crispy-forms/django-crispy-forms#1236]
* Package version: 1.13.0
* Django version: 4.0
* Python version: 3.8
* Template pack: Bootsrtap5

### Description:
When providing kwargs for the RadioSelect widget, the class attribute doesn't get applied.  I've tested it on Form and ModelForm and neither apply the class attribute.

```
widgets = {
            'test_field': forms.RadioSelect(attrs={'class': 'sr-only sr-only-focusable', })
        }
```

I also tried applying custom attributes and they get applied, just not the class attribute
```
widgets = {
            'destination': forms.RadioSelect(attrs={'data-test': 'test', 'class': 'sr-only sr-only-focusable', })
        }
```

results in 
`<input type="radio" class="form-check-input" name="0-destination" value="1" data-test="test" id="id_0-destination_1" required="">
`

**Comment by smithdc1** [comment]
https://github.com/django-crispy-forms/django-crispy-forms/pull/1286

I was unable to reproduce this.

I'd be happy to take another look if a reproducible example / failing test could be provided.
