### ISSUE TITLE
Incorrect rendering of ImageField

### ISSUE THREAD

**Issue by chicocheco** [django-crispy-forms/django-crispy-forms#1237]
* Package version: 1.14.0
* Django version: 4.0.2
* Python version: 3.10.1
* Template pack: crispy-bootstrap5 (0.6)

### Description:
Hi, 
I am trying to render ImageField with a customized widget (based on django's ClearableFileInput) with DRY method with help of crispy forms but it seems to be broken now comparing it with the previous version.
 
#### Previous behavior:
It works in my older project with django 3.2.4, django-crispy-forms 1.12.0, crispy-bootstrap5 0.4 but not anymore in the latest versions.

In the past there was no bootstrap styling applied to the ClearableFileInput widget. It looked like this:
![image](https://user-images.githubusercontent.com/33058002/154809193-2313bf05-d9a1-4102-9384-cb1547089df1.png)

This was a fix I used for an empty form:
`self.helper.layout = Layout(
...
Field('image', css_class='form-control'),
...
)`

But I wanted a widget with extra functionalities for editing an already uploaded image (update form) so I followed these steps https://stackoverflow.com/a/52184422/5258626 and it worked nicely. The result was this:

![image](https://user-images.githubusercontent.com/33058002/154809456-f188880f-0056-4d48-9fbf-cc48f1b8f3ec.png)

#### Current behavior:
Now the problem is that with the latest versions the default ClearableFileInput widget gets the bootstrap styling but incorrectly applied. I mean I appreciate the effort but it's not done well.

![image](https://user-images.githubusercontent.com/33058002/154809650-f25537c7-0968-4b60-a616-4f310c005fd0.png)

**HTML output:**
```
<div id="div_id_image" class="mb-3 row">
<label for="id_image" class="col-form-label col-lg-3 requiredField">
Image<span class="asteriskField">*</span></label> 
<div class="col-lg-9">  
   <div class="col-lg-9 mb-2"> <!--- this div is completely redundant  --->
      <div>
         <input type="file" name="image" class="form-control" accept="image/*" id="id_image" required="">
      </div>
      </div 
   </div>
</div>
```

Notice how `col-lg-9`, that is set by FormHelper()'s method (`helper.field_class = 'col-lg-9'`), is applied twice so there is an empty space on the right. Another thing is that I cannot simply override that so it would use my customized CustomClearableInput widget instead with this code:
```
class CustomClearableInput(forms.ClearableFileInput):
    template_name = 'widgets/image_input.html'  # my customized template

class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHorizontalHelper()

    class Meta:
        model = Product
        fields = ('name', 'url', 'category', 'image', 'description',)
        widgets = {
            'description': TinyMCE(),
            'image': CustomClearableInput(),
        }
```
It renders the default widget anyway:
![image](https://user-images.githubusercontent.com/33058002/154809985-c45dc730-68a5-4271-a870-9ed90435d773.png)

So we have two problems here. 

1. **helper.field_class** gets applied twice when using the default ClearableFileInput widget resulting in unexpected behavior (the column shrinks when you use anything else than 'col-12' bootstrap's class.
2. It seems that when using crispy forms, this same widget gets applied as last with ImageField no matter you specify your own. 

Edit: I found out that when I stop using crispy forms completely, it does render my customized widget of ImageField field.

**Comment by smithdc1** [comment]
> helper.field_class gets applied twice...

I was unable to reproduce this, see https://github.com/django-crispy-forms/django-crispy-forms/pull/1288

Happy to help take a closer look if a reproducible example can be provided. 

> It seems that when using crispy forms, this same widget gets applied as last with ImageField no matter you specify your own.

You'll need to use the `Field` layout object to assign a specific template for your custom widget. https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#universal-layout-objects.
