### ISSUE TITLE
Choices array of a field is not used dynamically anymore

### ISSUE THREAD

**Issue by danielsjf** [django-crispy-forms/django-crispy-forms#1248]
* Package version: 1.14.0
* Django version: 4.0.2
* Python version: 3.10
* Template pack: (Optional)

### Description:

In my code I'm updating the choices of a `CharField` dynamically (in init). I'm rendering it as a `RadioSelect` and using `InlineRadios`.

Before (<1.12.0), I could update the choices dynamically. In the newer version, I can still adapt the choices but it is indifferent to the rendering.

```python
class MyForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)
        self.fields['my_field'].choices.pop(0)
        self.helper.layout = Layout(
            InlineRadios('my_field'),
        )

    class Meta:
        model = MyModel
        widgets = {
            'my_field': forms.RadioSelect(),
        }
```

The popped choice is still shown. I can basically do whatever I want with choices but it has no impact.

This is possibly related to #1174 

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [ ] Screenshots
- [ ] Actual HTML generated
- [ ] Expected HTML

**Comment by danielsjf** [comment]
Workaround for now is to also update the widget choices with

```python
self.fields['my_field'].choices.pop(0)
self.fields['my_field'].widget.choices.pop(0)
```

**Comment by smithdc1** [comment]
Thanks for the feedback.  Still thinking about this in the meantime this may be similar  to 
https://code.djangoproject.com/ticket/33731

The aim is to mirror django core behaviour. So I'd ask what is the behaviour here if rendered with django itself. 🤔

**Comment by smithdc1** [comment]
> Workaround for now is to also update the widget choices with
> 
> ```python
> self.fields['my_field'].choices.pop(0)
> self.fields['my_field'].widget.choices.pop(0)
> ```

Yes, so this makes sense and is the behaviour I expect. We're now rendering the widget as Django itself would do. 

Django sets the choices on the widget to be the same as the field. Maybe the way the choices are redefined could make use of the `property` and `_set_choices`. 

https://github.com/django/django/blob/5eb6a2b33d70b9889e1cafa12594ad6f80773d3a/django/forms/fields.py#L872
