### ISSUE TITLE
Crispy Form does not automatically pick up and render correct input fields for TimeField, DurationField, DateField from ModelForm

### ISSUE THREAD

**Issue by edchelstephens** [django-crispy-forms/django-crispy-forms#1259]
### Software Versions:

* Package version: 1.9.2
* Django version: 3.1.2
* Python version: 3.8
* Template pack: bootstrap4

### Description:

I have a model with time, duration and datefield.
    `default_time = models.TimeField()`
    `default_duration = models.DurationField()`
    `start_date = models.DateField()`
    
I use crispy forms with the version above to create the form.
I was expecting crispy form to automatically pick up the field types from the model fields and render the specific field types accordingly, e.g. for 

`default_time -> <input type="time">`
`default_duration -> <input type="time>`
`start_date -> <input type="date">`

### Details:

- [ ✓] **Model Code**
![image](https://user-images.githubusercontent.com/49672830/170904029-7fabbb84-33f2-4555-8215-3ebc4c872d87.png)

- [✓ ] **Form Code:**
![image](https://user-images.githubusercontent.com/49672830/170904735-c9f71904-5121-4f32-a5c5-9fc3fd997f44.png)
![image](https://user-images.githubusercontent.com/49672830/170904760-fdc90c3c-1fbc-4852-8765-65d1b10b2429.png)

- [✓ ] **Django Template Code:**
![image](https://user-images.githubusercontent.com/49672830/170905629-b3d77fcf-4d32-46d7-ab87-8ae0db0917d8.png)

- [✓  ] **Actual HTML generated**
![image](https://user-images.githubusercontent.com/49672830/170904829-3563c070-b06c-44c8-91bf-edf58d4cc385.png)

**default_time html:**
`<div class="form-group" id="div_id_default_time"> <label class="requiredField" for="id_default_time">
                Default time<span class="asteriskField">*</span> </label> <div class=""> <input class="timeinput form-control" id="id_default_time" name="default_time" required="" type="text"> </div> </div>`
                
**default_duration html:**
`<div class="form-group" id="div_id_default_duration"> <label class="requiredField" for="id_default_duration">
                Default duration<span class="asteriskField">*</span> </label> <div class=""> <input class="textinput textInput form-control" id="id_default_duration" name="default_duration" required="" type="text"> </div> </div>`

**start_date html:**
`<div class="form-group" id="div_id_start_date"> <label class="requiredField" for="id_start_date">
                Start date<span class="asteriskField">*</span> </label> <div class=""> <input class="dateinput form-control" id="id_start_date" name="start_date" required="" type="text"> </div> </div>`

#### Any help is much appreciated! Thanks!

**Comment by smithdc1** [comment]
https://code.djangoproject.com/ticket/33113

The `type` is an attribute on the widget of your form. By default django does not add the types you are expecting and there's a ticket open to improve the docs for this. 

I therefore believe the correct approach is to add this to your widget in your form definition. 

Once defined I expect  Crispy-forms will then render the `type`.
