### ISSUE TITLE
CheckboxSelectMultiple regression

### ISSUE THREAD

**Issue by ritiko** [django-crispy-forms/django-crispy-forms#1263]
* Package version: 1.14.0
* Django version: 4.0.5
* Python version: 3.9
* Template pack: bootstrap4

### Description:

I'm upgrading from `django-crispy-forms==1.9.2` to `django-crispy-forms==1.14.0` and have a regression wrt `CheckboxSelectMultiple`. I had pinned that version on an older django version. I'm making this upgrade as part of an overall django upgrade.

`CheckboxSelectMultiple` isn't rendering anymore. Diving into the code, it looks like the filter `optgroups` might be responsible. Code snippet. This is part of a modelform

```python
class AnnoucementForm(forms.ModelForm):
    def __init__(self, organization, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            HTML("""
                <button class="mb-1 btn-xs btn btn-outline-primary mb-2" type="button" id="button-id-user-toggle">
                <i class="fas fa-filter"></i>
                Limit Recipients
                </button>
                """),
            'staff_groups',
        )

        self.fields['staff_groups'].queryset = self.fields['staff_groups'].queryset.filter(
            organization=organization
        )
        self.fields['staff_groups'].help_text = 'Will only send to selected staff groups if any is selected.'
        self.fields[
            'staff_groups'].label_from_instance = lambda obj: f"{obj.name} ({obj.short})"
        self.fields['staff_groups'].widget = forms.widgets.CheckboxSelectMultiple(attrs={
                                                                                  'class': 'h3'})
```

The `help_text` renders just fine but none of the fields actually render. Commenting out the widget line also causes field to render.

It seems like everything's filtered out on this line: https://github.com/django-crispy-forms/django-crispy-forms/blob/9429a0d2a092e9b85225fdc1fda7fd95b62d3096/crispy_forms/templates/bootstrap4/layout/checkboxselectmultiple.html#L6 and the implementation of  `optgroups` is responsible. Haven't dug too much into this but wanted to raise the issue as it's breaking silently and could be catastrophic for projects that heavily depend on crispy_forms

### Preferably also include:

- [x] Example Django Crispy Forms code
- [ ] Screenshots
- [ ] Actual HTML generated
- [ ] Expected HTML

**Comment by smithdc1** [comment]
Could you have a look at https://github.com/django-crispy-forms/django-crispy-forms/issues/1174

Do you have the same issue as described here

**Comment by smithdc1** [comment]
I'll assume this is a duplicate. If it can be shown as a different issue then we can re open and investigate.

**Comment by ritiko** [comment]
Sorry for the late reply. It appears to be related. Thanks for looking into this

For any future searchers, I solved this by setting the widgets under Meta i.e.

```python
form AnnouncementForm(..):
    ....
    class Meta:
        widgets = {
            'staff_groups': forms.CheckboxSelectMultiple(...)
        }
```
