### ISSUE TITLE
Feature Request: configurable global input size instead of bootstrap default size

### ISSUE THREAD

**Issue by NameX44** [django-crispy-forms/django-crispy-forms#1296]
# Problem

I would like to set a global input size for my whole FormHelper. It seems that it's not possible at the moment.

I want to avoid to set explicitly css_class="form-control-sm" or things like that for every fields.

# **Feature request**

Would be awesome to have something like this : 

`
self.helper = FormHelper()

self.helper.default_input_size = "sm" # or lg or '' for bootstrap default
`

This options should add sizing class on every input / form-control / form-group / input-group on every templates which needs it.

exemple in [bootstrap documentation](https://getbootstrap.com/docs/4.0/components/forms/) for input.

**Comment by smithdc1** [comment]
This request seems similar to the existing `field_class` attribute which can be set on `FormHelper`. Does this give you the functionality you are looking for?
