### ISSUE TITLE
Issue rendering submit button with 'btn btn-outline-primary' class

### ISSUE THREAD

**Issue by pedantic-curmudgeon** [django-crispy-forms/django-crispy-forms#1299]
* Package version: 1.14.0
* Django version: 4.0.5
* Python version: 3.10.2
* Template pack: bootstrap4

### Description:

I am trying to style a `Submit` button with a `css_class` of `btn btn-outline-primary` from [Boostrap4](https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons).

However, when I pass `css_class='btn btn-outline-primary'` into a `Submit` button, the rendered result is not as expected.

It appears that both the primary and primary outline classes are being rendered on top of each other.

This seems to be related to the following where the `css_class` is defaulted to `btn btn-primary` and the `css_class` passed into `Submit` is appended to it.

https://github.com/django-crispy-forms/django-crispy-forms/blob/1.14.0/crispy_forms/layout.py#L213
https://github.com/django-crispy-forms/django-crispy-forms/blob/1.14.0/crispy_forms/layout.py#L183-L184

Thanks!

### Preferably also include:

- [x] Example Django Crispy Forms code

```python
from crispy_forms.layout import Submit

Submit(
    'submit',
    'Save',
    css_class='btn btn-outline-primary',
)
```

- [x] Screenshots

Result
![image](https://user-images.githubusercontent.com/25124961/185537559-d4f4e220-9317-4627-844a-3a108bc58de2.png)

Expected
![image](https://user-images.githubusercontent.com/25124961/185537432-effa280b-70cf-44c2-90b7-07df6400eae3.png)

- [x] Actual HTML generated
```
<input type="submit" name="submit" value="Save" class="btn btn-primary btn btn-outline-primary" id="submit-id-submit">
```

- [x] Expected HTML
```
<input type="submit" name="submit" value="Save" class="btn btn-outline-primary" id="submit-id-submit">
```

**Comment by smithdc1** [comment]
I think the current advice here would be to subclass the Submit button and add your custom `field_classes`.
