### ISSUE TITLE
Officially support Django 4.1 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [django-crispy-forms/django-crispy-forms#1301]

**Comment by foarsitter** [comment]
The work for 4.1 seems to be done in https://github.com/django-crispy-forms/django-crispy-forms/pull/1257 so a new release will be sufficient, I think?

**Comment by browniebroke** [comment]
For others interested, the new release being prepared here #1294

**Comment by smithdc1** [comment]
https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/2.0

I've just pushed version 2.0 which now has the 4.1 classifier. It also supports 4.2 but the classifiers are not available at time of writing.
