### ISSUE TITLE
add "append()" method to Layout

### ISSUE THREAD

**Issue by nerdoc** [django-crispy-forms/django-crispy-forms#1307]
* Package version:=1.14.0
* Django version: 4.1
* Python version: 3.10
* Template pack: bootstrap5

### Description:

I often come into situations within a bigger project where I need a plugin class that creates a form which is rendered automatically within a bigger pack of templates. All these plugin forms look different, each plugin class has it's own form. But all need the same buttons, like "Save" and "Cancel". So I'd like to automate this process. Currently, it's only possible to create a list of LayoutObjects within the plugin, and let the plugin hook put it together using 

```python
self.helper.layout = Layout(*self.plugin_layout + [ButtonHolder(*self.buttons)])
```
Where buttons=[Button("submit", _("Save"))].

This is a bit cumbersome. It would be really helpful to add `LayoutObject`s after initial creation to a Layout. Layout just adds the fields to an internal list ATM. This behaviour could be changed later, but it would also be ok to adapt my suggestion then.

I would suggest to add an `append()` method to the Layout object, like a list has one. So at the end, individual buttons could be appended in another part of the code, which is impossible ATM (with legal tools, sure you can use `self.helper.layout.fields.append()`).

```python
class Layout(LayoutObject):
    ...
    def append(fields: LayoutObject|list[LayoutObject]):
        if isinstance(fields, LayoutObject):
           fields = [fields]
        self.fields += fields
```

This would make some working with Layouts easier.

**Comment by nerdoc** [comment]
alternatively (and more pythonic) would be letting users write `self.helper.layout += ButtonHolder(...)`.
```python
class Layout(LayoutObject):
    ...
    def __iadd__(self, other)
        self.fields.append(other)
```

**Comment by ckrybus** [comment]
You can already do that, for example:

```python
layout.append(HTML("<p>whatever</p>"))

layout.extend([
    HTML("<p>whatever</p>"),
    Div('add_field_on_the_go')
])

layout.insert(1, HTML("<p>whatever</p>"))
```

Source https://django-crispy-forms.readthedocs.io/en/latest/dynamic_layouts.html?highlight=insert#manipulating-a-layout

**Comment by nerdoc** [comment]
Oh, whow, must have missed that. Thanks!
