### ISSUE TITLE
Selecting layout objects with slices doesn't work ('LayoutSlice' object is not subscriptable)

### ISSUE THREAD

**Issue by Sulfyderz** [django-crispy-forms/django-crispy-forms#1326]
* Package version: 1.14.0
* Django version: 4.1.3
* Python version: 3.10.4
* Template pack: bootstrap5

### Description:
Hello,

There is a bug with the helper when we want to update the layout on the go.
I have this layout in my form `__init__` method:
```
self.helper.layout = Layout(
            Div(
                Div(
                    HTML('<ul id="ul-id-member">'),
                    HTML("</ul>"),
                    BaseInput(
                        "input-member",
                        "",
                        css_id="input-id-member",
                        hx_include="#ul-id-member",
                        hx_target="#member-suggestions",
                        hx_trigger="focus changed, newMemberSearch from:body delay:200ms",
                        hx_swap="innerHTML",
                        hx_get="",
                    ),
                    css_class="member-tag",
                ),
                HTML('<ol id="member-suggestions" class="member-suggestions"></ol>'),
                css_class="member-invite",
            ),
            Field("role", id="select-id-role"),
            Submit("invite", "Invite"),
            Button("cancel", "Cancel"),
        )
```

I would like to access the BaseInput as described in the [doc](https://django-crispy-forms.readthedocs.io/en/latest/dynamic_layouts.html#selecting-layout-objects-with-slices). Unfortunately, it doesn't work at all. When I try `form.helper[0][0][-1]` in my view, Python tells me that `TypeError: 'LayoutSlice' object is not subscriptable`.

Not sure, but I think it's a bug. Could you help me ?

**Comment by smithdc1** [comment]
I think it's the `[-1]` that's not supported. Does `[0][1]` work for you?

**Comment by Sulfyderz** [comment]
Hello,

No, it doesn't work.
I tried these :
```
>>> form.helper[0][0] # Should select the nested Div
>>> form.helper[0][1]  # Should select the nested HTML
```

Then I got this :
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: 'LayoutSlice' object is not subscriptable
```

I found the solution. In your doc, you forgot to add `.layout`. Thus, I should use "`form.helper.layout[0][0][1]`" instead of "`form.helper[0][0][-1]`" to select my `BaseInput`. Now, it works.

Thank you for your help.

**Comment by Sulfyderz** [comment]
Well, I found something interesting. It's somehow related to my other issue https://github.com/django-crispy-forms/django-crispy-forms/issues/1327. Since I can't have any `LayoutSlice` for nested objects, I can't have the related methods such as `update_attributes`.

What could be great is not to have that question in mind: "Should I use `form.helper[0]` or `form.helper.layout[0]` ?". Both should have the same methods. What do you think @smithdc1 ?

**Comment by Sulfyderz** [comment]
Hello again,

After checking your code, I know why it doesn't work. Your `LayoutSlice` doesn't have a `__getitem__` method. That's why you can only have first-level elements in your layout. Moreover, you are right about `-1` as an indice, `form.helper[-1].update_attributes` do not work at all.

I tried to change/update your code to PR but I didn't get your interest with the `slice` as follow :
```
class LayoutSlice:
    # List of layout objects that need args passed first before fields
    args_first = (Fieldset, MultiField, Container)

    def __init__(self, layout, key):
        self.layout = layout
        if isinstance(key, int):
            self.slice = slice(key, key + 1, 1)
        else:
            self.slice = key
```

Almost all other methods in your `LayoutSlice` use that. A simpler way is to remove it. If you can share your agenda to have chosen that way, I could help.
