### ISSUE TITLE
django 4.1.5 allauth and crispy forms not working

### ISSUE THREAD

**Issue by firaki12345-cmd** [django-crispy-forms/django-crispy-forms#1329]
* Package version: 1.14.0
* Django version: 4.1.5
* Python version: 3.10.6
* Template pack: bootstrap4

**### Description:**

so i have installed crispy forms and have added it into the settings py file with also the template pack, and i have added the django all auth templates to my app folder so i can override them.

**the templates work as i have used {% extends "testing/base.html "%}** on the first line and it works perfectly .. Only the problem is the crispy form filter not working, so its not styling it.

**here is my settings.py**

![3](https://user-images.githubusercontent.com/77625215/214593041-1c4f29e3-d16b-4e79-8f42-2ebd9392a036.png)

**Here is my html file**

![1](https://user-images.githubusercontent.com/77625215/214593174-21ac741b-c31c-4188-a1df-5489c32dbbd7.png)

![2](https://user-images.githubusercontent.com/77625215/214593187-4f31831a-6014-4256-80ac-2a861107a238.png)

**Here is my login page**

![Screenshot from 2023-01-25 11-07-54](https://user-images.githubusercontent.com/77625215/214593232-006e3975-b546-4cd6-bf00-3ae9b4017aa1.png)

**Comment by smithdc1** [comment]
It's hard to diagnose a full example like this. However, it looks like your second html file needs to load the crispy form tags?
