### ISSUE TITLE
Enhancement: improve media files inclusion + documentation

### ISSUE THREAD

**Issue by nerdoc** [django-crispy-forms/django-crispy-forms#1330]
* Package version: django-crispy-forms        1.14.0, crispy-bootstrap5          0.7
* Django version: 4.1
* Python version: 3.10
* Template pack: (Optional) bootstrap5

### Description:

Crispy documentation is ambiguous: The [crispy docs](https://django-crispy-forms.readthedocs.io/en/latest/form_helper.html) say at the `include_media = True` section: 

    By default django-crispy-forms renders all form media for you within the form.

At [Settings media files](https://django-crispy-forms.readthedocs.io/en/latest/install.html?highlight=media#setting-media-files) it says the (IMHO) opposite: 

    crispy-forms does not include static files. You will need to include the proper corresponding media 
    files yourself depending on what CSS framework (Template pack) you are using.

So it seems to be bit weird, and there are a few stackoverflow pages that try to solve that problem.

So how do you include media files in crispy forms? Docs could tell more here. Let's say I use a CustomCheckboxWidget for a django form, and then migrate to crispy form because it fullfills my needs with the widget there, I just want to include it's javascript. Crispy does not call the CustomCheckboxWidget's `render()` method, and won't use it's Media class, or does it?
What if I don't use a Django forms widget, but a custom Crispy field - where do I add media there?

**Comment by nerdoc** [comment]
To summarize it again: It seems that crispy includes the Media class of the Form, but I can't see where it includes Media classes of widgets, as it doesn't even render those widgets.
AND, if I define a custom Crispy Field (which seems to be a widget like Django widgets), I can't include Media data there.

e.g. I have a `TimeSelector` crispy field (which has a bs5 time input group with +/- buttons left/right that increase/decrease the time by 15min. Therefore Js is needed, and I want to include that in the form which contains this Crispy field.
I can only define a `class Media` of the form, but can't include that Js with every form that renders a TimeSelector crispy field automatically

**Comment by smithdc1** [comment]
Hey @nerdoc 

So I think there are two things here. The first is [Form Assets (the media class)](https://docs.djangoproject.com/en/4.1/topics/forms/media/). In the case of  `include_media` attribute this specifically means [Form Media](https://docs.djangoproject.com/en/4.1/topics/forms/media/#media-on-forms) there the "default ... is the result of adding the media definitions for all widgets that are part of the form".

The second are general static files. e.g the main bootstrap css and script tags. These are not included by the template packs and you'll need to add those yourself (usually in a `base.html` or similar I'd expect). 


What I'm really struggling to understand is form media renders but widget media does not. See https://github.com/django-crispy-forms/crispy-bootstrap5/pull/136

Debuging here inside the `uni_form.html` template. I expect `{{ form.media}}` to give the same result. 

https://github.com/django-crispy-forms/crispy-bootstrap5/blob/94f0ca5adbe528b7ea43ab8238e4adc849ae84a3/crispy_bootstrap5/templates/bootstrap5/uni_form.html#L4

And using the debugger we seem to get the same values. I'm therefore unsure why it's not being rendered. 

```
> form
SampleFormWithMedia: <SampleFormWithMedia bound=False, valid=Unknown, fields=()>
> form.media
Media(css={'all': ['test.css']}, js=['test.js'])
> include_media
True

> form
SampleFormWithWidgetMedia: <SampleFormWithWidgetMedia bound=False, valid=Unknown, fields=(media)>
> form.media
Media(css={'all': ['test.css']}, js=['test.js'])
> include_media
True
```

**Comment by smithdc1** [comment]
I managed to work it out, I had a name clash on my form with "media" the input and "form.media". Those tests on my example now pass. 

I therefore believe it's possible to define media on your widget and that to appear in all the forms where it is required.
