### ISSUE TITLE
Tab does not respect string case on render

### ISSUE THREAD

**Issue by PydPiper** [django-crispy-forms/django-crispy-forms#1334]
* Package version:  1.14.0
* Django version: 3.2.8 
* Python version: 3.9.6

### Description:
First off, thank you for the amazing package! This is a minor annoyance that i have a work around for but it was causing bugs that took a bit to figure out. I would like to remove my work-around for a native fix to the following issue.

Issue: The `Thisname` for tab name is rendered as all lowercase id on the front end side. 
```python
self.helper.layout = Div(TabHolder([Tab('THISname', 'field1', field2')]))
```
renders as 
```
<div id="thisname" class="tab-pane active"> 
```

Expected behavior: tab
```
<div id="THISname" class="tab-pane active"> 
```

**Comment by smithdc1** [comment]
Thanks for the report. I'm not sure there's much we can do as this has been like this ~forever[1]. If we were to change this now then I imagine we'll also get reports of introducing a breaking change as they'll be relying on the lower-casing impact of slugify.

Happy to hear proposals on how this could be done in a backward compatible way. 

[1] https://github.com/django-crispy-forms/django-crispy-forms/blame/0247e9200174b9a9cbb87357ff12a9d138efd2e4/crispy_forms/bootstrap.py#L226
[2] https://docs.djangoproject.com/en/4.1/ref/utils/#module-django.utils.text

**Comment by PydPiper** [comment]
@smithdc1 thanks for the reply! What you said makes sense, the only proposal i would have for backward compatibility is adding an extra field for case_sensitive=True handling that by default (if the kwarg does not exists defaults to False)

**Comment by PydPiper** [comment]
Took another look at your refs and crispy could implement its own `slugify` like so
```python
def slugify(value, allow_unicode=False):
    """
    Convert to ASCII if 'allow_unicode' is False. Convert spaces or repeated
    dashes to single dashes. Remove characters that aren't alphanumerics,
    underscores, or hyphens. Convert to lowercase. Also strip leading and
    trailing whitespace, dashes, and underscores.
    """
    value = str(value)
    if allow_unicode:
        value = unicodedata.normalize("NFKC", value)
    else:
        value = (
            unicodedata.normalize("NFKD", value)
            .encode("ascii", "ignore")
            .decode("ascii")
        )
    value = re.sub(r"[^\w\s-]", "", value)
    return re.sub(r"[-\s]+", "-", value).strip("-_")
```
code copied from https://docs.djangoproject.com/en/4.1/_modules/django/utils/text/#slugify and modified to remove lower-case

**Comment by smithdc1** [comment]
Thanks for having a look at that. 

Does defining the [`css_id`](https://django-crispy-forms.readthedocs.io/en/2.0/api_bootstrap.html#crispy_forms.bootstrap.Tab) when creating the class work for you? 

So something like `Tab('THISname', 'field1', field2', css_id='THISname')`

**Comment by PydPiper** [comment]
yeah i think that's clean enough, but i am happy to wait for the community to give feedback before a final decision, as i have a work-around for handling this issue currently

**Comment by smithdc1** [comment]
I'll close this to now, but happy to re-review if we receive any more feedback.
