### ISSUE TITLE
Crispy forms templates won't load for django-crispy-forms 2.0

### ISSUE THREAD

**Issue by mikbuch** [django-crispy-forms/django-crispy-forms#1336]
* Package version: 2.0
* Django version: 4.1.4 & 4.1.7 & 3
* Python version: 3.10
* Template pack: bootstrap4, but it affects all template packs

### Description:

Crispy forms templates won't load on template rendering.

Solution: downgrade crispy forms to 1.14.0

Probable cause: crispy_forms package that is installed to site-packages is missing "templates" directory? Very strange.

### Preferably also include:

- [x] Example Django Crispy Forms code

```
{% load crispy_forms_tags %}

        <div class="login-page">
            <form class="login-container" method="POST">
                {% csrf_token %}
                {{ login_form|crispy }}
                <div class="btn-action-wrapper">
                    <button class="btn btn-primary" type="submit" style="margin-top: 10px">Login</button>
                </div>
            </form>
        </div>
```

- [x] Screenshots

<img width="2447" alt="image" src="https://user-images.githubusercontent.com/10733514/219179095-0ad97e48-5523-4276-8f02-4b8e915bd487.png">

- [x] Actual HTML generated

None, error, either Django debug or 500 server error.

- [x] Expected HTML

```
<html><head></head><body><div class="login-page">
            <form class="login-container" method="POST">
                <input type="hidden" name="csrfmiddlewaretoken" value="vY6tZVikuKEA1fPDkmfIQ01MeOqrGZMO7CCJDfnMYJjnCX8uAzeMVMLoOFNpfF66">
                

    






    


    <div id="div_id_username" class="ctrlHolder">
        
            
        

        
            

            <label for="id_username" class="requiredField">
                Username<span class="asteriskField">*</span>
            </label>
        

        
            <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" class="textinput textInput" required="" id="id_username">
        

        
    </div>



    


    <div id="div_id_password" class="ctrlHolder">
        
            
        

        
            

            <label for="id_password" class="requiredField">
                Password<span class="asteriskField">*</span>
            </label>
        

        
            <input type="password" name="password" autocomplete="current-password" class="textinput textInput" required="" id="id_password">
        

        
    </div>






                <div class="btn-action-wrapper">
                    <button class="btn btn-primary" type="submit" style="margin-top: 10px">Login</button>
                </div>
            </form>
        </div>
</body></html>
```

**Comment by mikbuch** [comment]
Wow, the 2.0 release was 2 days ago? https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/2.0

That explains why I started having these issues today, once I updated the whole project (virtual environment). :)

**Comment by smithdc1** [comment]
Please have a look through the changelog. There's an upgrade guide when moving to 2.0. 

The key change is that the template packs are now in standalone packages. 

Therefore, you'll need to install the appropriate template pack and add it to your installed apps.

**Comment by mikbuch** [comment]
Oh, I see, I thought that it may be some change like that, but the quick fix for me was just the downgrade.

I will take a look at the changelog and the documentation, thank you for pointing me out in that direction.

Actually, I would have maybe one more suggestion to add: I was even looking at the updated "Installation" part of the documentation (https://django-crispy-forms.readthedocs.io/en/latest/install.html#template-packs), but I didn't read it thorough enough, I am sorry. My suggestion is then, for users less attentive and/or less experienced with template packs, to add there, in the documentation, a short instruction how to install these packs, similar to the notes from the changelog (https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/2.0). Or, even better, to add an example line to the "Installation" how to install the bootstrap pack, i.e.:

```
 pip install crispy-bootstrap4
```

That would help a lot of people I guess. What do you think?

**Comment by smithdc1** [comment]
Sounds reasonable -- PR's welcome!

**Comment by mikbuch** [comment]
PR added, please review

**Comment by mikbuch** [comment]
Hi @smithdc1 , what is the status of this issue / PR ?

**Comment by smithdc1** [comment]
I think this is completed. Happy to take any further suggestions as follow up PRs.
