### ISSUE TITLE
get_context_data available to Crispy's helper?

### ISSUE THREAD

**Issue by nitsujri** [django-crispy-forms/django-crispy-forms#1343]
I'm new to Django and crispy so apologies if this is the wrong place to ask this. I really like what crispy offers, and I've been struggling for hours trying to convert this one thing to `Hidden()`

In django-allauth, there's a dependency on `redirect_field_value` and `redirect_field_name` in the [form.html](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/login.html#L39) only available after [`get_context_data`](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L174).

Is it possible to convert the below `HTML` into a conditional `Hidden`?

```python
            HTML("""
                {% if redirect_field_value %}
                    <input type="hidden" value="{{redirect_field_value}}" name="{{redirect_field_name}}" />
                {% endif %}
            """),
```

Ideally it would look something like:

```python
if context['redirect_field_value']:
    helper.add_input(
        Hidden(context['redirect_field_name'], value=context['redirect_field_value'])
    )
```

It feels impossible because I can't get access to the `get_context_data`? That the `.helper`'s lifecycle is earlier than context or that the Form simply doesn't have access to the View and its context data.

**Comment by smithdc1** [comment]
Crispy allows [updating layouts on the go](https://django-crispy-forms.readthedocs.io/en/latest/dynamic_layouts.html). 

Where are you adding this? 

``` python
if context['redirect_field_value']:
    helper.add_input(
        Hidden(context['redirect_field_name'], value=context['redirect_field_value'])
    )
```

I wonder if overriding the view's `get` method you could then call `get_context_data` or more specifically just call `get_request_param` as per this line? Depending on what that returns you could then add the additional input? 

https://github.com/pennersr/django-allauth/blob/77368a84903d32283f07a260819893ec15df78fb/allauth/account/views.py#L179

**Comment by nitsujri** [comment]
@smithdc1 thanks for the reply!

> Where are you adding this?

I'm currently adding this in the `models.Form` subclass as [recommended by the Layouts docs](https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#fundamentals). Specifically, I'm adding it using the [method `def helper` @property](https://github.com/django-crispy-forms/django-crispy-forms/blob/main/crispy_forms/helper.py#L168) that I found while reading the docs looking for an answer to this.

> I wonder if overriding the view's get method you could then call get_context_data

I've come to the conclusion that I would have to do just that and call the `get_context_data` early and pass it directly into the `Form`. My options come down to:

- Pass in the view via `self` and override [`get_form`](https://github.com/django/django/blob/main/django/views/generic/edit.py#L33) and the Form's `__init__`. Then I can call `get_request_param` as mentioned above.
- Call the `get_context_data` in an overridden `get_form` and pass the context in by overriding like above.

> Crispy allows [updating layouts on the go](https://django-crispy-forms.readthedocs.io/en/latest/dynamic_layouts.html).

While this would get what I'm aiming for, I'm not truly a fan of this one because now the form is being manipulated in different locations, which creates maintainability problems (i.e. it's super not obvious where this field comes from to another engineer).

I'll probably end up closing this out because fundamentally the `get_context_data` is later in the lifecycle compared to `get_form` and if I want the context data in the form, I have to pass it in directly.
