### ISSUE TITLE
[Suggestion] Activate "active" option in Tab class

### ISSUE THREAD

**Issue by ChloeQuignot** [django-crispy-forms/django-crispy-forms#1344]
* Package version:2.0
* Django version:4.1.7
* Python version:3.10.6
* Template pack: crispy-bootstrap4==2022.1

### Description:

Hello,

Thank you so much for this module! Great work!

I'm trying to use `crispy_forms.helper.FormHelper` to divide my form into Tabs but they all appear closed ("inactive") when I render my page, even though I specify the `active=True` option for the first Tab. After looking at the source code, I wonder if it's not linked to the definition of the `Tab` class in `crispy_forms.bootstrap` in which the `css_class` option is set to "tab-pane" by default (I think that's why `active=True` doesn't seem to have an effect).

After playing around a bit, I managed to find a solution by creating my own `Tab` class with an added `__init__` method which runs the `__init__` of the parent class (`Container`) and then adapts the `css_class` according to the arguments. When `active=True`, I add `active` and `show` classes to the `css_class` option (there's probably better ways of doing it but this does the job for me):

```
from crispy_forms.bootstrap import  Container
from crispy_forms.utils import TEMPLATE_PACK
from django.template.loader import render_to_string

class myTab(Container):
    """
    Tab object. It wraps fields in a div whose default class is "tab-pane" and
    takes a name as first argument. Example::

        Tab('tab_name', 'form_field_1', 'form_field_2', 'form_field_3')
    """
    link_template = '%s/layout/tab-link.html'

    def __init__(self, name, *fields, css_id=None, css_class=None, template=None, active=None, **kwargs):
        Container.__init__(self, name, *fields, css_id=None, css_class=None, template=None, active=None, **kwargs)
        self.css_class = "tab-pane"
        if active:
            self.css_class += ' active show'   

    def render_link(self, template_pack=TEMPLATE_PACK, **kwargs):
        """
        Render the link for the tab-pane. It must be called after render so css_class is updated
        with active if needed.
        """
        link_template = self.link_template % template_pack
        return render_to_string(link_template, {'link': self})
```

And in my forms.py of my Django project, I use myTab instead of Tab:
```
        self.helper.layout.append(TabHolder(
            myTab("Input1", *options1, css_id="input-tab-1", active=True),
            myTab("Input2", *options2, css_id="input-tab-2"),
        ))
```

For more clarity, a `diff -u old.py new.py`:
```
--- old.py	2023-03-23 22:26:34.692517827 +0100
+++ new.py	2023-03-23 22:27:06.696542006 +0100
@@ -1,14 +1,17 @@
-
-class Tab(Container):
+class myTab(Container):
     """
     Tab object. It wraps fields in a div whose default class is "tab-pane" and
     takes a name as first argument. Example::
 
         Tab('tab_name', 'form_field_1', 'form_field_2', 'form_field_3')
     """
-    css_class = "tab-pane"
     link_template = "%s/layout/tab-link.html"
+    def __init__(self, name, *fields, css_id=None, css_class=None, template=None, active=None, **kwargs):
+        Container.__init__(self, name, *fields, css_id=None, css_class=None, template=None, active=None, **kwargs)
+        self.css_class = "tab-pane"
+        if active:
+            self.css_class += ' active show'   
 
     def render_link(self, template_pack=TEMPLATE_PACK, **kwargs):

```

Kind regards,
Chloe

**Comment by smithdc1** [comment]
Hi Chloe,

I've started to have a look at this. Is the requirement that you want to specify a particular tab is open (say the second one), or just the first one is open? 

I'm expecting that this code here ensure that the first tab is open, even without specifying `active=True`. 

https://github.com/django-crispy-forms/django-crispy-forms/blob/897b6dc46b7d7f01e0a2989b1a4f07fa3c1c7456/crispy_forms/bootstrap.py#L664-L670

I've created a small example using crispy-test-project at https://github.com/django-crispy-forms/crispy-test-project/tree/1344

With this layout:

```python 
    helper.layout = Layout(
        TabHolder(
            Tab("First Tab", "text_input", "text_input_a"),
            Tab("Second Tab", "text_input_b", "text_input_c"),
        )
    )
```

I see this. 
![image](https://user-images.githubusercontent.com/39445562/230011171-c0b2943d-b849-47c0-b05a-473cbca960dc.png)

**Comment by ChloeQuignot** [comment]
Hi smithdc1,
Thanks for your help.

**Comment by smithdc1** [comment]
No problem. 

I think if the ask is to show the second tab open by default (I'm not sure why this would be the case 🤔) then that would require much more thought.

 I think your notes above would likely be a good starting point of what would be required.

Good luck with your project. 👍
