### ISSUE TITLE
InlineRadios and InlineCheckboxes not Rendering Properly with crispy-bootstrap5

### ISSUE THREAD

**Issue by gbwlucite** [django-crispy-forms/django-crispy-forms#1350]
I am trying to use the `InlineRadios` and `InlineCheckboxes` in for a ModelForm with django. I am wanting to use them on a model for 2 fields which have a `ForeignKey` and `ManyToMany` relationship with the model in question (not sure if that is important). 

* Package version: crispy-bootstrap5==0.7
* Django version: Django==4.2
* Python version: Python 3.11.3
* Template pack: bootstrap5

### #Forms.py file (clipping)
`   

  
         def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                self.helper = FormHelper()
                self.helper.layout = Layout(
                    Fieldset(
                    'Add a Ticket',
                    Div('weighdate', 'quality_control', title = "Enter a title here", style="background: #FFE5B4;"),
                    'payment', 'loading_statement', InlineCheckboxes('variety_chosen'), 
                    'store_location', 'external_location', 'weight_one', 'weight_two', 'net_weight',
                    'tr_no', 'comments', 'weighoperator_name', 'driver_name',
                  
              ),
             
              InlineRadios('registration'),
              
              Submit('submit', 'Submit', css_class='button white'),
          )
`

**- This is what the page looks like - with numbers in the checkboxes and the radio fields not displaying properly.** 

<img width="450" alt="2023-05-18" src="https://github.com/django-crispy-forms/django-crispy-forms/assets/56308676/841ae4d1-0b2c-4825-b7de-b15446292aed">

- Actual Html
`<input type="select" class="form-check-input" name="variety_chosen" value="1">`
`<input type="select" class="form-check-input" name="registration" value="">`

- I think this widgets are generated by these three files:
[\crispy_bootstrap5\templates\bootstrap5\layout\checkboxselectmultiple_inline.html](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/layout/checkboxselectmultiple_inline.html)
[\crispy_bootstrap5\templates\bootstrap5\layout\radioselect_inline.html](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/layout/radioselect_inline.html)
[\crispy_bootstrap5\templates\bootstrap5\layout\radio_checkbox_select.html](https://github.com/django-crispy-forms/crispy-bootstrap5/blob/main/crispy_bootstrap5/templates/bootstrap5/layout/radio_checkbox_select.html)

I've checked that my files are the same as the ones found on here as well.
Any ideas what may be the issue -  I am not an expert at HTML which is why I wanted to use Bootstrap so help would be greatly appreciated.

**Comment by smithdc1** [comment]
Hi 👋 
Could you provide the actual HTML output for the whole inline radio field, i.e. including it's wrapping `<div>` the registration label and so on? 

Thanks!

**Comment by gbwlucite** [comment]
I have deleted my code that reproduces this and decided to go another way I tried reproducing it but have changed too many things to back track and foolishly did not save a version as it wasn't working - sorry for wasting your time.

**Comment by elnygren** [comment]
This is still a problem:

the HTML created has the wrong `type="select"` that should be `type="checkbox"`

reprod:

```
InlineCheckboxes("field")
```

HTML produced:

```
<div class="form-check form-check-inline"> 
        <input type="select" class="form-check-input" name="inventory_category" value="...."> 
        <label for="" class="form-check-label">label</label>
</div>
```

**Comment by elnygren** [comment]
## Solution:

Manually set the field in your ModelForm, eg:

```
inventory_category = forms.ModelMultipleChoiceField(
        queryset=ListingCategory.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
```

not sure what Field/Widget Django uses by default for M2M Fields

**Comment by housUnus** [comment]
@elnygren solution worked for me, but still a an issue to declare the field in the form again
