### ISSUE TITLE
ReadOnly as "html" aka printing just form instance values.

### ISSUE THREAD

**Issue by esseti** [django-crispy-forms/django-crispy-forms#1352]
Hello,
is there a component or something to easily print form instance data?
right now i was able to do so just like this:

```
self.helper.layout = Layout(
            Row(
              Column(HTML(f'<div  class="form-group"> '
                            f'<label>Name</label> '
                            f'<div>{self.instance.name}</div> '
                            f'</div>'),
                       css_class="col-md-3"),
                ....
            )
        )
```

is there something smarter? such as Instance('field') that maybe uses boostrap or template components to make the form look better?

**Comment by smithdc1** [comment]
`HTML` has access to the current context. So if in the current template the form instance is assigned to a variable called "form" (say), then you can access the fields on that in the [usual way](https://docs.djangoproject.com/en/4.2/topics/forms/#rendering-fields-manually) (`form.name`) for example.
