### ISSUE TITLE
Allow Fieldset to accept Fields

### ISSUE THREAD

**Issue by kytta** [django-crispy-forms/django-crispy-forms#1361]
* Package version: 2.0
* Django version: 3.2.18
* Python version: 3.8.17
* Template pack: crispy-bootstrap5 0.7

### Description:

The `Fieldset` class accepts a number of fields to render in a `<fieldset>`. Apparently, the value of this field can only be `str`:

https://github.com/django-crispy-forms/django-crispy-forms/blob/3b81cc98f99505cd55a7fdc7cb7ca2744f6e2546/crispy_forms/layout.py#L521

This causes a type checking error if one uses `Field` and any subclasses of it, like `AppendedText` from the Bootstrap pack.

I propose changing the type of the kwargs to `str | LayoutObject`

**Comment by smithdc1** [comment]
Fixed in #1363
