### ISSUE TITLE
[Question/Feature Request] Use without template pack

### ISSUE THREAD

**Issue by VaZark** [django-crispy-forms/django-crispy-forms#1364]
## Description:

I'm using a Daisy Ui a tailwind-based component framework. This is already installed globally and invoked on all pages.

It'd be great if I could use the base crispy form package just for the CSS overrides using the **CRISPY_CLASS_CONVERTERS** param and global layouting.

**Comment by smithdc1** [comment]
Thanks for the suggestion Crispy forms needs a template pack to be able to render its output. 

As far as im aware some opinion is needed for how thhtml is to be laid out. E.g input inside or alongside the label. Likely folk would want to customise this. 

Luckily its not difficult to create your own base template (`field.html`) and you can set the `field_template` on the `FormHelper`  

https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-project-templates

Other than that maybe if it's just widget tweaks you need then maybe it's worth looking at the django-widget-tweaks library?
