### ISSUE TITLE
Discuss possible funding with Sentry. 

### ISSUE THREAD

**Issue by carltongibson** [django-crispy-forms/django-crispy-forms#1366]
<img width="229" alt="b1dcf1f04468850e" src="https://github.com/django-crispy-forms/django-crispy-forms/assets/64686/e687830e-ae20-42bc-afc9-23c54a434384">

@getsentry fund 95% of their direct dependencies. 

Crispy Forms is in the 5%

https://github.com/getsentry/sentry/blob/0e724df1fabb7c6fbb80285207dbc0ccc9e0ef4d/requirements-base.txt#L13

Discuss with them to see if we can fix that.

**Comment by chadwhitacre** [comment]
> Crispy Forms is in the 5%

Ah, I guess this is confusing on GitHub's side. It's really 95% of our _sponsorable_ direct dependencies. The 5% are either Sentry employees or sponsorable maintainers with a minimum higher than we're able to reach.

I'll mention this to them. Sorry for the confusion!

**Comment by chadwhitacre** [comment]
If you sign up though I can deal you in. FYI we're doing small amounts through GitHub Sponsors and potentially larger amounts through Thanks.dev. Sign up on both? :)

**Comment by smithdc1** [comment]
Hi @chadwhitacre  -- Thank you for responding here. 

I've made progress signing up to both as you kindly suggested. So far I've managed signed up to [Thanks.dev](https://thanks.dev/p/gh/django-crispy-forms). I've also applied for GitHub Sponsors and our application is currently in the queue to be reviewed by GitHub staff. 

I'll update when I hear more from GitHub.

**Comment by chadwhitacre** [comment]
Awesome! We're aiming to start paying out on Thanks.dev this week. Lmk once you're on GitHub Sponsors and I'll add you there as well. 👍

**Comment by smithdc1** [comment]
Hey all 👋

Approval for the organisation to join sponsors came through earlier today. 

https://github.com/sponsors/django-crispy-forms

**Comment by carltongibson** [comment]
Great! thanks for setting that up @smithdc1 🏅

> Lmk once you're on GitHub Sponsors and I'll add you there as well. 👍

@chadwhitacre Here you go 😊 Is there anything else we need to do? Thanks so much. Maybe a small thing from your end, but means a lot on ours 🥰

**Comment by chadwhitacre** [comment]
It's not much but I set up $5/mo to @django-crispy-forms from @getsentry.

<img width="336" alt="Screenshot 2023-11-01 at 4 11 57 PM" src="https://github.com/django-crispy-forms/django-crispy-forms/assets/134455/7fcba0dd-f91b-4ced-bd48-fbf5ef020ac2">

Now let's get a 1,000 other companies to do the same! 😁

**Comment by carltongibson** [comment]
Thanks @chadwhitacre, that's awesome. 🎁
