### ISSUE TITLE
Is it possible to customize the Changelist form ?

### ISSUE THREAD

**Issue by Birddle** [django-crispy-forms/django-crispy-forms#1376]
* Package version:
* Django version: 5.0
* Python version: 3.3
* Template pack: (Optional)

### Description:
Can this package be customized to modify the layout of the changlist?
As you can see, I'm in the process of customizing the default layout (custom action buttons, custom rendering methods), but it's very overwhelming. Not only do I need to override a lot of modelAdmin methods, but I also need to override the labels in the template. 
I just was wondering if it would fit my needs.
<img width="1231" alt="image" src="https://github.com/django-crispy-forms/django-crispy-forms/assets/86408260/1030d726-619e-4720-9d71-e167790dd8f8">

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [x] Screenshots
- [ ] Actual HTML generated
- [ ] Expected HTML

**Comment by smithdc1** [comment]
Hi @Birddle -- Crispy-forms will render any form that's passed to it. Sure, you could use it in a django admin template. 

I think this question is therefore more about how to customise the admin than about crispy-forms. I think asking on the Django Forum would be a better source of help for your issue. It's a much more active community than this issue tracker.
