### ISSUE TITLE
Option to disable wrapping div around field

### ISSUE THREAD

**Issue by medihack** [django-crispy-forms/django-crispy-forms#1379]
* Package version: 2.1
* Django version: 4.2.10
* Python version: 3.12
* Template pack: crispy-bootstrap5 2023.10

### Description:

Sometimes, I want to design funny widgets like this:

![DateRange](https://github.com/django-crispy-forms/django-crispy-forms/assets/120626/f8d7dc77-422d-4e24-8b7e-e07eedc311e8)

This would be easily doable with django-crispy-forms (without any custom template), if the wrapping `div` could be turned off (as all those fields are wrapped together in a `div`). Can we integrate such an option for `Field`?

**Comment by medihack** [comment]
I am closing this as I more and more come to the conclusion that something like this better fits a custom layout object.

**Comment by smithdc1** [comment]
> I am closing this as I more and more come to the conclusion that something like this better fits a custom layout object.

This sounds like the way. Multiwidgets can be a bit tricky.
