### ISSUE TITLE
Error: TemplateDoesNotExist - bootstrap4/field.html when upgrading to v2

### ISSUE THREAD

**Issue by tomdtp** [django-crispy-forms/django-crispy-forms#1386]
* Package version: 2.1
* Django version: 5.0.4
* Python version: 3.10
* Template pack: bootstrap4 - 24.1

### Description:

I am trying to upgrade from crispy-forms 1.14.0 to 2.1.
When I bump from 1.14.0 to 2.1 I get the error `TemplateDoesNotExist - bootstrap4/field.html `

The line this results from is: `{% trans 'Category' %}<br>{{ form.category|as_crispy_field }}`

**Comment by smithdc1** [comment]
Hi @tomdtp -- you'll need to install https://pypi.org/project/crispy-bootstrap4/ and add it to your `INSTALLED_APPS`.

For full migration guide from v1.x to v2.0 see:

https://github.com/django-crispy-forms/django-crispy-forms/blob/main/CHANGELOG.md#major-changes-and-migration-guide
