### ISSUE TITLE
ModuleNotFoundError: No module named 'crispy_forms'

### ISSUE THREAD

**Issue by JanBronee** [django-crispy-forms/django-crispy-forms#1402]
* Package version:  2.3
* Django version:  5.1.2
* Python version:  3.13.0. (Mac OS with M2-chip)
* Template pack: (Optional)

**pip list | grep crisp**
crispy-bootstrap5        2024.10
django-crispy-forms      2.3

**python3 manage.py runserver**
...
...
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'crispy_forms'

**Comment by smithdc1** [comment]
Hi @JanBronee -- this looks like virtual environment issue to me. I'm afraid they are a little difficult to offer support with. 

It may be worth seeing if any of the suggestions here work for you. 

https://stackoverflow.com/questions/28560968/importerror-no-module-named-crispy-forms
