### ISSUE TITLE
Crispy forms to render multiple forms

### ISSUE THREAD

**Issue by tarasdi** [django-crispy-forms/django-crispy-forms#144]
Hi,

I don't think this is possible, but I thought I'd check. Does crispy forms support rendering and processing of multiple forms combined into one larger layout, and if not, has it ever been considered? EG: consider a 'Person' crispy form for a 'Person' model with name/age/etc.. attributes. Now imagine your app wants to display a form to allow a user to enter 'Parents', that is, two 'Person' models. For the layout you could render the two forms separately using two crispy tags in the template, or what if you could create a crispy form that doesn't map to a Django model, but whose layout is composed of the layouts of the two constituent forms? This would allow you to use the 'Parents' form as part of an even larger form, and also reuse the 'Parents' form in other parts of the app.

You could achieve this reuse by having separate templates for each form composition (in this case a 'parents' template) and including them via 'includes', but having it in the code seems neater and more flexible. 

One thing you'd have to consider in addition to HTML generation is form validation (possibly by calling is_valid on each of the constituent forms).

Post on multiple form models per view: http://stackoverflow.com/questions/569468/django-multiple-models-in-one-template-using-forms.

**Comment by ssocias** [comment]
@qris I've been trying to implement your solution but can't get it to work. Any chance you can help me? I posted  [my question] (http://stackoverflow.com/questions/28996351/formset-within-a-form-using-django-crispy-forms) on stackoverflow a few weeks back but am still stuck.

**Comment by durdenk** [comment]
qris , is this method still working. I get KeyError: 'wrapper_class'

**Comment by samkuehn** [comment]
@durdenk I was getting the same error.  I opened an issue #511 and have submitted a pull request.

**Comment by sLesage** [comment]
I have been looking for something similar for a while now. So ... have there been any updates ?

**Comment by J20S** [comment]
+1 for any updates?

**Comment by joewandy** [comment]
Still waiting for an update too here ..

**Comment by carltongibson** [comment]
It's unlikely we'll now add anything here. 

Rendering multiple forms settIng form_tag=False on the Helper gives you 90% of what you need. 

I'm sceptical that anything else would be generic enough and simple enough to include in the library. (It doesn't strike me as a problem that you can solve with a list in userland view code.)

I'll leave this open, and discussion open too, for the now. Please don't comment with "Any updates?" or similar. 

Happy to consider serious suggestions. Pull requests are welcome. (Although see above.)

**Comment by bobort** [comment]
It looks like the work that maraujop did is not in the master branch, but it is exactly what we need for this feature to work.  Was there any particular reason why this feature did not make it into master?  I know this question is similar to "any updates?", but why should anyone do a pull request if the code is already complete and ready to use?

**Comment by carltongibson** [comment]
@bobort At this point it's mainly a combination of age vs the trade-off between utility and added-complexity and maintenance overhead. 

I'm in favour of users just solving this in their own code by setting `form_tag=False` on the Helper and rendering the list of forms they want. (And yes, that will involve user involvement in their own software.) 

As I said, I'm happy to review concrete suggestions — part of that is _why_ it would be better as a library provided solution. I'm going to close the discussion on this ticket: I would prefer to start discussion afresh if there's a sensible proposal.
