### ISSUE TITLE
Add class to control-group

### ISSUE THREAD

**Issue by VMitov** [django-crispy-forms/django-crispy-forms#157]
Can't add class to control-group/ctrlHolder div. This will be helpful in situations when there is formset and you want to select one of the fields in each form.

**Comment by foobar76** [comment]
Whow ... this took me a while to find. Just came here by googling after fiddling in the field template around. Did I missed something in the docs? Otherwise maybe add this, since this is extremely useful for use in bootstrap forms. Tnx for the feature anyway :)
