### ISSUE TITLE
Django 1.4.5 and Crispy-forms-1.2.3 rendering issue with class-based views

### ISSUE THREAD

**Issue by thongly** [django-crispy-forms/django-crispy-forms#164]
After switching to crispy-forms, I'm having issues rendering my ModelForms with class-based views as follows:

The forms render, but without any adherence to defined layouts (not included below), nor is there a submit button. Are there version incompatibility issues?
# forms.py

```
from models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import *
from crispy_forms.bootstrap import *

class MyModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.form_action = 'mymodel_add'
        self.helper.add_input(Submit('submit', 'Submit'))
        super(MyModelForm, self).__init__(*args, **kwargs)

    class Meta:
        model = MyModel
```
# views.py

```
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

class MyModelCreateView(CreateView):
    model = MyModel
    template_name = 'core/MyModel_add.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyModelCreateView, self).dispatch(*args, **kwargs) 
```

**Comment by Hikaon** [comment]
I have encounter similar (I think) problem with Django 1.8 and crispy 1.6.
forms.py
`class ListingModelForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(ListingModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'property_form'

    class Meta:
        model = Listing
        exclude = ('location',)
`
views.py
`class AddProperty(CreateView):
    model = Listing
    form = ListingModelForm
    form_class = ListingModelForm
    # fields = "__all__"
    template_name = "seller_add_property.html"

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        data = super(AddProperty, self).get_context_data(**kwargs)
        if self.request.POST:
            data['attributes'] = PropertyAttributesFormset(self.request.POST)
        else:
            data['attributes'] = PropertyAttributesFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        attributes = context['attributes']
        self.object = form.save(commit=True)
        if attributes.is_valid():
            for attr in attributes.cleaned_data:
                attr['listing'] = self.object
                attr.pop("DELETE")
                attr.pop("id")
                AttributeListing.objects.create(**attr)
        else:
            print(attributes.errors)
        return super(AddProperty, self).form_valid(form)

PropertyAttributesFormset = inlineformset_factory(Listing, AttributeListing, exclude=("order",), form=AttributeListingForm, extra=1)`

template
`{% load crispy_forms_tags %}
{% block content %}
    {% crispy form %}
    <table id="formset-table">    
    <tr>
        <th>Additional attrbute</th>&nbsp
        <th>Value</th>
    </tr>
        {% for form in attributes.forms %}
        <tr>
           <td class="attr_select">{{ form.attribute }}</td>
           <td>{{ form.value }}</td>
        </tr>
        {% endfor %}
    </table>
    {{ attributes.management_form }}
{% endblock %}
`

form rendered without id
