### ISSUE TITLE
RadioSelect attrs not applied

### ISSUE THREAD

**Issue by gompster** [django-crispy-forms/django-crispy-forms#206]
When a RadioSelect widget is rendered in the bootstrap theme, the classes that are passed to the **attrs** parameter are not rendered.

If I define a field like this:

<pre>field = forms.ChoiceField(widget=forms.RadioSelect(attrs={"class": "myclass"}))</pre>

And add this to the __init__ function of the form:

<pre>self.helper.layout = Layout(InlineRadios('field'))</pre>

The class "myclass" is not applied to the radio buttons. I think this is due to the rendering of radioselect.html, which does not seem to include input classes.

**Comment by nigelcopley** [comment]
hi, it seems this bug has cropped up again.  

Django==4.0 & django-crispy-forms==1.13.0
