### ISSUE TITLE
table_inline_formset.html does not render non-Field layout objects such as StrictButton

### ISSUE THREAD

**Issue by palm86** [django-crispy-forms/django-crispy-forms#224]
If I render a formset with the default template, layout objects such as StrictButton render as expected. However, when rendering with table_inline_formset.html, these objects are ignored. I would expect each to be included in its own `<td></td>`. I haven't been able to figure out why this doesn't happen by just looking at the templates.

**Comment by iTaybb** [comment]
Would like to have this fixed.
