### ISSUE TITLE
Proposition : replace HTML Layout by a Render one

### ISSUE THREAD

**Issue by mijamo** [django-crispy-forms/django-crispy-forms#227]
It happens to me that in many forms I need to add some html content, with a template (like charts etc.).

Currently what I do is HTML(render_to_string(template, context)), but actually it's a bit redondant with what HTML widget does after that ...

Why not just transform the HTML widget to behave like the render function ?

So that we could do Render('<p>plain html</p>') or Render ('template.html', {'fields':fields}) for example ?

In fact in my dreams we could also pass a Layout object as argument in a context, to have something like Render('template.html',{'field1' : Field('first_field'), 'field2' : Field('second_field')}) but that would need a bit more work, even if that would just be awesome.

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
