### ISSUE TITLE
Correct way to implement a cancel button w/ UpdateView+ModelForm?

### ISSUE THREAD

**Issue by jasonslater2000** [django-crispy-forms/django-crispy-forms#242]
Just wanted to run this by you and get your thoughts...

If you're using ModelForms and UpdateView, you're letting Django take care of the 
form layout, tweaking some setting perhaps via Crispy, and then letting Crispy render it.  

In these types of views, you often want to have a Cancel button on your form:

![pastedgraphic-1](https://f.cloud.github.com/assets/1718983/1141192/0f5cceb0-1caf-11e3-8a62-6258a0078583.png)

If you Google around, end users of Crispy don't seem to have a consistent idea of how to accomplish this.
*\* Some people suggest appending raw HTML via Crispy's helper object -- not a clean approach
*\* Some people suggest just using Crispy to render the fields, then wrap your own form in HTML -- not clean either, since now you've got to maintain code in two places
*\* Some people suggest putting a button in which has onclick="history.go(-1)"  -- go back a page in the browser history.  The history(-1) approach is bad if you submit with bad data, which posts and comes back invalid, and then try to cancel -- in this case, going back one page takes you back to the form you submitted with invalid data.

(As an aside, Django is supposed to be Javascript-agnostic, meaning that if you've got to resort to DOM manipulation via Javascript to accomplish something this basic, you're probably doing something wrong.) 

I had an idea - perhaps you could add another Submit button, this time labeled "Cancel", and style it accordingly.

basically, taking this:

```
        self.helper.add_input(Submit('submit', 'Create Project'))
```

and making it this:

```
        self.helper.add_input(Submit('submit', 'Create Project'))
        self.helper.add_input(Submit('cancel', 'Cancel', css_class='btn-default'))
```

(The styling on the Cancel button was supposed to give me a basic black button as appears in my picture above.)

Since these are both form submits which do a post back to the view, your view code would look something like this.

```
def form_valid(self, form):
    if 'cancel' in self.request.POST:
        return HttpResponseRedirect(self.get_success_url())
    return super(Project_UpdateView, self).form_valid(form)
```

Basically, seeing if 'cancel' is in the POST dictionary and redirecting accordingly, otherwise following the normal path.  It ends up functioning, but I noticed that I had very little control over the styling of that new Cancel button. If I styled it "btn-danger" (i.e. Red button), that worked.  Otherwise, it always seemed to end up Blue like the other button.

![pastedgraphic-2](https://f.cloud.github.com/assets/1718983/1141201/41edd888-1caf-11e3-9e4c-11a841b3b9ea.png)

So I looked into the Submit class within Crispy and found this:

```
input_type = 'submit'
field_classes = 'submit submitButton' if TEMPLATE_PACK == 'uni_form' else 'btn btn-primary'
```

What this means is that if you're using bootstrap it's always going to get styled the same way ('btn-primary', i.e. Blue button).  Due to how bootstrap works, the Red danger button overrides this style, but things like Default button don't.

My solution:

create a new SubmitButton class which removes the "btn-primary" styling.

from django.conf import settings
TEMPLATE_PACK = getattr(settings, 'CRISPY_TEMPLATE_PACK', 'bootstrap')
class SubmitButton(BaseInput):
    input_type = 'submit'
    field_classes = 'button' if TEMPLATE_PACK == 'uni_form' else 'btn' #removed btn-primary

When you use it, you've got to specify the style of the button, since the "btn-primary" default is gone now.  So now, when you use it in Crispy layout code, it's clean and simple and you now have control over the styling of your buttons.

```
self.helper.add_input(SubmitButton('submit', 'Update',css_class='btn-primary'))
self.helper.add_input(SubmitButton('cancel', 'Cancel',css_class='btn btn-default'))
```

and the rendered HTML is correct:

```
 <div class="form-actions">
  <input type="submit" name="submit" value="Update" class="btn btn-primary" id="submit-id-submit">
  <input type="submit" name="cancel" value="Cancel" class="btn btn-default" id="submit-id-cancel"> 
 </div>
```

There's probably a better solution which would involve adding an anchor, which is either styled like a button or wraps a button, and links back to the page which invoked the UpdateView in the first place.  The anchor approach would mean one less transaction (the POST) to handle the Cancel operation.

**Comment by thecardcheat** [comment]
I am encountering this issue with bootstrap3, It can cause additional frustration if you add additional styling to btn-primary to fit a color scheme but do not re-define btn-danger for example. A clear use case that this restricts is having multiple submits for "Save" "Save & Return" "Save and add another" etc. which since btn-default has the lowest priority, means you can never use it.

I am thinking that [Line 213](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/layout.py#L213) is actually broken with the current [template packs](http://django-crispy-forms.readthedocs.org/en/latest/install.html#template-packs). I don't use Foundation, but their (Button docs)[http://foundation.zurb.com/docs/components/buttons.html] would indicate that their button classes are named differently than boostrap, so unnecessary styling is applied to Foundation, and possibly unwanted styling is applied to bootstrap.

I think the correct way to go is to leave the current decision for uni-form (I don't use it, I assume it is ok), use "button" for Foundation, and use only "btn" for bootstrap. The boostrap situation is less than ideal than Foundation because their default button styling only requires the single class, but for bootstrap you will still get a mostly-styled button and you probably want to be identifying btn-* anyway.

**Comment by carltongibson** [comment]
OK. This is a fair use-case. We should handle it — either directly or with a documented _recommended solution_. 

There are two separate cases: 

1. A Cancel Option
2. Multiple Submits

On 1, I don't like POSTing the form. (Sure, I see it works.) Better for me is to have a link, with the option to style that as a button if you so wish. (Often "Cancel", as a secondary option, being a plain hyperlink works well.)

> ... you probably want to be specifying btn-* each time anyway

So maybe the `btn-primary` gets moved to a kwarg for the user to override if needed?

Happy to see PRs for either of these points (separately). 

Right now I'm not so worried about Foundation: [crispy-forms-foundation](https://github.com/sveetch/crispy-forms-foundation) are welcome to implement whatever layout objects they need. If there's some API they're after to make that easy/easier I'm happy to review that sympathetically at the time.

**Comment by brandonwbrown** [comment]
Just refreshing this conversation and registering my vote here for a Cancel button with an href argument and css_class. I'd implement it if I knew how... thanks much.

**Comment by carltongibson** [comment]
Please don't make "+1" comments. There's a reaction button for that purpose. It just wastes time and is annoying

**Comment by diogolr** [comment]
If you're using Bootstrap (like I think you do), you can use `FormActions`:
```python
from crispy_forms.bootstrap import FormActions
from crispy_forms.layout import Button
from crispy_forms.layout import Submit

helper.add_layout(
    Layout(
        Field( ... ),
        Field( ... ),
        Field( ... ),
        FormActions(
            Submit( 'save', 'Save', css_class = 'btn btn-primary' ),
            Button( 'cancel', 'Cancel', css_class = 'btn btn-default' )
        )
    )
)
```

**Comment by carltongibson** [comment]
Yes, the FormActions example is even [in the docs](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html#bootstrap-layout-objects).

The canonical answer here will be "Use Layouts" [Docs](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html)

Either adding a `Button`, or using `HTML` to add an anchor is clear enough. 

Again, very happy to see PRs on specific points — but I'm going to close this as I don't really see it as an _Issue_.

**Comment by pyutil** [comment]
Yes, Layout+FormActions. But what if I don't define and don't want define the explicit list of Field's?

**Comment by pyutil** [comment]
This is really pain and frustration. I just want the Cancel button as btn-outline-secondary. When I use Submit, the button will receive btn-primary. When I use Button, it looks properly, however I need Javascript to set window.location=..

**Comment by pyutil** [comment]
This is strange, but works:
```
rows = [el for el in form.fields]
rows.append(
    FormActions(
        Submit('Save', _('Save')),
        HTML(f'<a href="{reverse("focov:choose-regulation")}" class="btn btn-outline-secondary">{_("Cancel")}</a>'),
    css_class="row"),
)
self.layout = Layout(
    Fieldset('', *rows),
)
```
