### ISSUE TITLE
First AccordionGroup can never be set to collapsed at initial page load.

### ISSUE THREAD

**Issue by adamsc64** [django-crispy-forms/django-crispy-forms#245]
When there are no errors, the first `AccordionGroup` in an `Accordion` will always be set to active, even you originally set it as `active=False`. For example, in this case:

``` python
    test_form.helper.layout = Layout(
        Accordion(
            AccordionGroup(
                'one',
                'first_name',
                active=False,
            ),
        )
    )
```

One might expect that this single group be collapsed at initial page render. However, the `active` kwarg, as defined, will be ignored. It is overrided as `True`.

This behavior is unexpected and overly restrictive. There may be reasons why you want to render an Accordion with all internal groups initially closed. Further, the Twitter Bootstrap documentation [see http://getbootstrap.com/2.3.2/javascript.html#collapse] allows this rendered state as a possibility at initial page load.

**Comment by jvd10** [comment]
Seems that active=False is still ignored.  Simple one line change in the Accordion's render method works for me.  This does prevent the first container from being active even if active kwarg not supplied.

```
class CustomAccordion(Accordion):

    def render(self, form, form_style, context, template_pack=TEMPLATE_PACK):
        content = ''

        # accordion group needs the parent div id to set `data-parent` (I don't
        # know why). This needs to be a unique id
        if not self.css_id:
            self.css_id = "-".join(["accordion", text_type(randint(1000, 9999))])

        # first group with errors will be visible, others will be collapsed by
        # default, or will follow the active kwarg if it was supplied
        if form.errors:
            self.first_container_with_errors(form.errors.keys()).active = True

        for group in self.fields:
            group.data_parent = self.css_id
            content += render_field(
                group, form, form_style, context, template_pack=template_pack
            )

        return render_to_string(
            self.template,
            Context({'accordion': self, 'content': content})
        )
```
