### ISSUE TITLE
HTML5 data attribute for CheckboxSelectMultiple

### ISSUE THREAD

**Issue by mzu** [django-crispy-forms/django-crispy-forms#247]
Hi. Is there a way to add individual data_name attributes (as described here: https://django-crispy-forms.readthedocs.org/en/latest/layouts.html#layout-objects-attributes) to each individual input of a CheckboxSelectMultiple widget via the crispy-forms helper?

E.g. my CheckboxSelectMultiple gets initialised via a ModelForm and I would like to add a HTML5 data attribute to each checkbox. When selected I would like to perform some JavaScript actions on the individual data that belongs to the checkbox.

Cheers.

**Comment by carltongibson** [comment]
You'd need to override the relevant template I guess. (Sorry, not much of an answer after all this time.)
