### ISSUE TITLE
Support HTML5 boolean attributes in `BaseInput` layout objects.

### ISSUE THREAD

**Issue by msegal** [django-crispy-forms/django-crispy-forms#257]
Currently, `BaseInput` calls `flatatt()` which converts all attributes to `attr="value"` form. Thus, there is no way to pass an HTML5 boolean attribute (such as `disabled`), which should not be followed by an equal sign.

This would be an easy fix: a one line change to `crispy_forms.utils.flatatt`.

**Comment by carltongibson** [comment]
Happy to see input on this one but it's not something I'm going to prioritise at the moment. (Just a question of bandwidth really) If it comes up again when we're more on top of the backlog we can reconsider. 

> Happy to see input on this one...

**Comment by slagelwa** [comment]
+1
