### ISSUE TITLE
add display filters to `Field` objects

### ISSUE THREAD

**Issue by yekibud** [django-crispy-forms/django-crispy-forms#259]
I came across the issue of wanting to persist phone number values differently than their display, i.e.

XXX-XXX-XXXX
- persisted value (per the `django_localflavor.us.USPhoneNumberField` specification)

(XXX) XXX-XXXX
- the desired display value for my app

I believe the recommended way to do this is to apply a template filter to the value, but I don't think there is currently a way to do this with crispy forms.  I wound up implementing the desired functionality with a custom form widget, but I'm wondering if this should be handled in crispy, instead?  If so, how should it be implemented?  I currently pass my form widget a template filter, but maybe the crispy api would simply get a tempate filter name that would be used in the field template?

**Comment by carltongibson** [comment]
Custom widget seems reasonable. (Ideal in fact)
