### ISSUE TITLE
Hidden form fields and wrappers

### ISSUE THREAD

**Issue by aschriner** [django-crispy-forms/django-crispy-forms#260]
I am trying to generate some hidden fields.  I'm using one type of field that is from here: https://github.com/philippbosch/django-geoposition.  It's just a compound lat/long field (two inputs).  To hide them I am trying:

```
Layout(Field('js_duration', type='hidden'),
    Field('location', type='hidden'))
```

When I do the above to hide the fields, it works fine on 'js_duration' (a FloatField) but on 'location', it only hides the two text input boxes, leaving the div wrapper with ctrlHolder class, and the labels.  Shouldn't it hide the whole thing?

**Comment by carltongibson** [comment]
Meh. Not sure. Happy to look at a concrete PR showing the behaviour change (the before and after) etc. Other than that it's not something we've got the bandwidth to address as an active issue.
