### ISSUE TITLE
CSS class cleanup in bs3 templates

### ISSUE THREAD

**Issue by kenthauser** [django-crispy-forms/django-crispy-forms#265]
Hi,

I tracking down why some forms weren't rendering as I expected, I noticed that there are several places where the templates don't render exactly like the BS example code. In addition, I noticed serveral CSS classes which are not defined in BS3. I think there are two types of these: the BS2 classes which have been removed, and classes UniForm defined and are still with us today.

From my notes, I see the extra classes as::
#### Bootstrap 2 deprecated
- form-actions 
- error
- controls
- alert-block
- alert-heading
#### UniForm (deprecated?)
- requiredField
- ctrlHolder
- errorField
- inlineLabel
- formHint

I am planning to update the BS3 templates to remove the remaining BS2 stuff. I can remove the UniForm classes at the same time if appropriate. Any comments would be appreciated.  

Thanks. Kent

**Comment by carltongibson** [comment]
I'm going to close this as not really actionable. 

I'm **very happy** to take small PRs addressing individual issues but it's too much to verify such a list, especially after so much time.
