### ISSUE TITLE
Formset allow model instance field

### ISSUE THREAD

**Issue by s7726** [django-crispy-forms/django-crispy-forms#270]
Trying to use crispy forms to display a survey type application.
Right now the form has to be setup using a for loop

```
for form in formset
    form.instance.question
    crispy form
endfor
```

If I could access the instance of the field while doing the Layout in crispy I could drop the loop and just do

```
crispy formset
```

I think this would be a great addition to crispy.

**Comment by carltongibson** [comment]
Happy to see a PR on this. Going to close it as an active issue though.
