### ISSUE TITLE
InlineField (inline_field.html) does not support displaying form errors

### ISSUE THREAD

**Issue by s7726** [django-crispy-forms/django-crispy-forms#271]
I've just spent hours trying to figure out why my form was not highlighting the boxes or displaying any info about why the form was not submitting.

The template is not setup to display the error or help text.

**Comment by zoidbergwill** [comment]
Is this project being maintained? Is there any change of this being fixed?

**Comment by robbyt** [comment]
@zoidbergwill unfortunately, this project is pretty quite...

**Comment by carltongibson** [comment]
I'm going to assume this is resolved. @zoidbergwill shout if it's not (and you want to consider it an active issue).
