### ISSUE TITLE
crispy-forms does not seem to look at DateInput widget's 'format' attribute when form is rendered

### ISSUE THREAD

**Issue by pravasi** [django-crispy-forms/django-crispy-forms#276]
I am using django-crispy-forms for a Formwizard and using bootstrap_datepicker for a pop up calendar for choosing the date for a field 'distribution_start_date' which is a DateField. For the form I have widgets = {'distribution_start_date': forms.DateInput(format='%m/%d/%Y'),}. For input everything works fine ,the 'distribution_start_date' field value is displayed correctly after chosing the date (format='%m/%d/%Y',maybe from 'format' option given in javascript ) and saved fine.But when the saved model is displayed for editing, the the value for the field is dispalyed in the format='%Y-%m-%d' which is the first default format for DATE_INPUT_FORMATS.Does crispy-forms look at widget's 'format' attribute when form is rendered?

**Comment by carltongibson** [comment]
`format` is the format in which this field’s initial value will be displayed. If that's not happening we can look at a concrete test case showing that. I'm going to assume there was some other issue here.
