### ISSUE TITLE
Field layout object appears not to use helper.field_template

### ISSUE THREAD

**Issue by eskeli** [django-crispy-forms/django-crispy-forms#277]
It appears that Field object does not use helper.field_template attribute. Instead it just uses the default template for the field (when template argument is not set for Field object). Is this intended behavior? To me it feels inconsistent.

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
