### ISSUE TITLE
Why set css_class in CrispyFieldNode? 

### ISSUE THREAD

**Issue by matthewh** [django-crispy-forms/django-crispy-forms#283]
I'm using designmodo's flatui framework, a derivative of bootstrap3, and I created a custom template pack but I ran into a minor issue that required me to extend the crispy_forms_field.CrispyFieldNode in my own project. The only change I needed to make was  `TEMPLATE_PACK == 'flatui'`. 

Buried in the middle of crispy_forms_field.py:
            if (
                TEMPLATE_PACK == 'bootstrap3'
                and not crispy_forms_field.is_checkbox(field)
                and not crispy_forms_field.is_file(field)
            ):
                css_class += ' form-control'

Can you offer any insight into why template specific css attributes are being modified here? I would have expected to see this in the template logic perhaps. I'd like to refactor that chunk but I'm not sure where else to put it. Any advice?

**Comment by carltongibson** [comment]
The main repo contains four template packs now. There's also a [Foundation template pack](https://crispy-forms-foundation.readthedocs.io/en/latest/) (Maybe there are others)

Happy to take a PR linking to external template packs. Going to close this as an Active Issue.
