### ISSUE TITLE
use layout fields to define form.fields

### ISSUE THREAD

**Issue by yekibud** [django-crispy-forms/django-crispy-forms#289]
Using `ModelForm` with `crispy_forms` requires that a form's fields be specified both in `MyModelForm.Meta.fields`  and in `form.helper.layout` (otherwise form validation will fail since `form.fields` will default to all the model fields if it is not explicitly specified).  This doesn't seem very DRY.  

So shouldn't we try to set `form.fields` based on `layout.get_field_names()`?  I implemented this by setting a form's fields in `MyModelForm.__init__`.  However, there seems to be a bit of a "chicken and egg" problem, as `layout.get_field_names()` is an instance method, but instantiating the layout seems to set the fields on the form.  In order to avoid this, I copy the form first, get the fields from the instantiated layout, then use the layout fields to define the original form's fields.  

Can anyone think of a better way to do this via `crispy_forms` itself?  Or is there a reason we should continue to have to specify fields in both `MyModelForm.Meta.fields` and `form.helper.layout`?

**Comment by carltongibson** [comment]
If you want control over the layout you'll always need to specify it. Otherwise CF **does** build a default layout from the `Form` instance. 

Happy to review concrete suggestions but I don't see anything we can do here as is.
