### ISSUE TITLE
Escaping values

### ISSUE THREAD

**Issue by frasern** [django-crispy-forms/django-crispy-forms#296]
I was surprised to see that a lot of values seem to be just piped through the `|safe` filter in the templates. This effectively disables Django's auto-escaping functionality and requires explicit escaping of values within the form definition in Python.

Compare rendering a standard Python form:

``` python
>>> from django import forms
>>> class MyForm(forms.Form):
...   foobar = forms.CharField(label='Foo & bar')
...
>>> unicode(MyForm())
u'<tr><th><label for="id_foobar">Foo &amp; bar:</label></th><td><input id="id_foobar" name="foobar" type="text" /></td></tr>'
```

(notice that the label has been auto-escaped to use `&amp;`)

Compare this to the output from Crispy Forms:

``` python
>>> from django.template import Template, Context
>>> template = Template('{% load crispy_forms_tags %}{% crispy form %}')
>>> template.render(Context({'form': MyForm()}))
u'\n\n<form  method="post" ><div id="div_id_foobar" class="form-group"><label for="id_foobar" class="control-label  requiredField">\n\t\t\t\tFoo & bar<span class="asteriskField">*</span></label><div class="controls "><input class="textinput textInput form-control" id="id_foobar" name="foobar" type="text" /> </div></div></form>\n'
```

(notice that the label is unsafe and outputs just `&`)

To get safe and valid HTML, I need to either manually use the HTML entity:

``` python
>>> class MyForm(forms.Form):
...   foobar = forms.CharField(label='Foo &amp; bar')
```

Or programmatically escape it:

``` python
>>> from django.utils.html import escape
>>> class MyForm(forms.Form):
...   foobar = forms.CharField(label=escape('Foo & bar'))
```

Note that marking the string as unsafe does not work:

``` python
>>> from django.utils.safestring import mark_for_escaping
>>> class MyForm(forms.Form):
...   foobar = forms.CharField(label=mark_for_escaping('Foo & bar'))
...
>>> template.render(Context({'form': MyForm()}))
u'\n\n<form  method="post" ><div id="div_id_foobar" class="form-group"><label for="id_foobar" class="control-label  requiredField">\n\t\t\t\tFoo & bar<span class="asteriskField">*</span></label><div class="controls "><input class="textinput textInput form-control" id="id_foobar" name="foobar" type="text" /> </div></div></form>\n'
```

My understanding is that auto-escaping is best practice and that generally using [`mark_safe`](https://docs.djangoproject.com/en/dev/ref/utils/#django.utils.safestring.mark_safe) on strings in Python that you explicitly want to avoid escaping is preferred to manually escaping the values.

Is there a particular reason Crispy Forms assumes all strings are safe? Removing this behaviour would probably be a good idea, but would be backward incompatible.

Happy to put together a pull request if necessary.

**Comment by michaeljones** [comment]
+1, I've just come across this. It seems undesired and we should surely be matching Django's behaviour? I am running 1.6 though so perhaps this is different for more recent Django versions?

**Comment by carltongibson** [comment]
Happy to take input here.

**Comment by sjoerdjob** [comment]
To me, this also seems to be undesired, and I would like to try and propose a pull-request for this. I can however also imagine that just removing the `|safe` in all the templates is a breaking change, and should possibly go through a deprecation period over some releases.

Is a deprecation period for this desired?

If a deprecation period is to be desired, I would think an approach could be to implement a new templatefilter `deprecated_safe`, and use that instead.

```
def deprecated_safe(value):
    if conditional_escape(value) != value:
        # Only warn if changing safe-by-default to escape-by-default would result 
        warnings.warn("<Some specific message>", RemovedInCrispy20)
    return mark_safe(value)
```

Possibly with a different deprecation period, of course.

Do you think something like the above could work to eventually transition behaviour from never-escaping to conditional_escape?

**Comment by carltongibson** [comment]
TBH (some time later) I think we should probably think about just introducing the breaking change, with explanation, and bump the major version.

**Comment by smithdc1** [comment]
We've recently discussed bumping the major version for other breaking changes. So it sounds like this is the path the project is headed. 

Will be good to see what this looks like but I'm nervous about time it may take to get everything in place to deliver the changes. 

I'll try and give some thought to a plan so we have some steps we can track.

**Comment by yujinyuz** [comment]
Are there any workarounds for this?

I'm using django-crispy-forms together with django-summer-note

When I type:

`You make bold tags like this: <b>I'm bold<b>`

<img src="https://user-images.githubusercontent.com/10604391/98411888-bfe3ec00-202b-11eb-9599-bc4dc07491d0.png" alt="image">

In the summernote editor, it looks like this: 
```html
<p>You make bold tags like this: &lt;b&gt;I'm bold&lt;b&gt; <br></p>
```

But when I try to edit it, it gets rendered as an actual HTML

<img src="https://user-images.githubusercontent.com/10604391/98411912-d1c58f00-202b-11eb-93da-0df9613c5977.png" alt="image">

In Django Admin, it displays just fine `You make bold tags like this: <b>I'm bold<b>` since it's not using crispy forms to render it

**Comment by smithdc1** [comment]
Hi @yujinyuz I'm not familiar with django-summer-note so I'm not sure how this actually gets rendered. In any case here are a few ideas available within crispy-forms. 

- Do any of the options in the original post help?
- You can manually over-ride the [template](https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-layout-objects-templates). So if it's a `|safe` filter somewhere causing the issue, you could make that amend.

**Comment by yujinyuz** [comment]
Thanks @smithdc1 

I forgot to mention that I tried overriding the default template for the `div` and removed the `|safe` filter but it's generating a string and doesn't render the actual HTML

```html
<div id="div_id_instructor_notes" class="form-group"> <label for="id_instructor_notes" class="control-label "> Instructor notes </label> <div class="controls "> <textarea name="instructor_notes" cols="40" rows="10" class="summernoteinplacewidget form-control" id="id_instructor_notes" hidden="true"> Bold: &amp;lt;b&amp;gt;Weee&amp;lt;/b&amp;gt;</textarea><script> function initSummernote_id_instructor_notes() { $(document).ready(function($) { var origin = window.document.getElementById('id_instructor_notes'); var csrftoken = getCookie('csrftoken'); var settings = {"airMode": false, "width": "100%", "height": "480", "followingToolbar": false, "toolbar": [["style", ["style"]], ["font", ["bold", "italic", "underline", "superscript", "subscript", "strikethrough", "add-text-tags", "clear"]], ["fontname", ["fontname"]], ["fontsize", ["fontsize"]], ["color", ["color"]], ["para", ["ul", "ol", "listStyles", "paragraph"]], ["table", ["table"]], ["insert", ["link", "picture", "videoAttributes", "hr", "faicon", "math"]], ["view", ["codeview"]], ["help", ["help"]]], "codemirror": {"mode": "htmlmixed", "lineNumbers": "true", "lineWrapping": "true", "theme": "monokai"}, "lang": "en-US", "url": {"language": "/static/summernote/lang/summernote-en-US.min.js", "upload_attachment": "/summernote/upload_attachment/"}}; var $sn = $(origin); $sn.html(origin.value); var $nEditor, $nCodable, $nImageInput; $(origin).hide(); function recalcHeight(e) { var nEditable = e.find('.note-editable'); var nEditor = $('.note-editor'); var height = parseInt( parseInt(settings.height) // default - e.find('.note-toolbar').outerHeight() - e.find('.note-status-output').outerHeight() - e.find('.note-statusbar').outerHeight() - (nEditor.outerHeight() - nEditor.innerHeight()) // editor's border ); nEditable.outerHeight(height); } var initEditor = function() { $sn.summernote($.extend(settings, { callbacks: { onInit: function() { $nEditor = $sn.next(); $nCodable = $nEditor.find('.note-codable'); recalcHeight($nEditor); // Apply attributes with wrapper div var $wrap = $($nEditor).wrap( '<div class="summernote-div"></div>' ).parent(); $wrap.attr('cols', '40'); $wrap.attr('rows', '10'); $wrap.attr('class', 'summernoteinplacewidget'); // Move dropdown dialog when it exceeds the bound of the editor $nEditor.find('.note-btn-group').on('shown.bs.dropdown', function () { var nDropdown = $(this).find(".dropdown-menu"); var offset = nDropdown.offset(); var width = nDropdown.width(); var windowWidth = $(window).width(); var margin = 15; if( offset.left + width + margin > windowWidth ) { var left = windowWidth - width - offset.left - margin; nDropdown.css("left", left + "px"); } }); }, onBlur: function() { origin.value = $sn.summernote('code'); }, onBlurCodeview: function() { origin.value = $sn.summernote('code'); }, onImageUpload: function(files) { // custom attachment data var attachmentData = origin.dataset; $nImageInput = $nEditor.find('.note-image-input'); $nImageInput.fileupload(); var jqXHR = $nImageInput.fileupload('send', { files: files, formData: $.extend({csrfmiddlewaretoken: csrftoken}, attachmentData), url: settings.url.upload_attachment, }) .done(function (data, textStatus, jqXHR) { $.each(data.files, function (index, file) { $sn.summernote("insertImage", file.url); }); }) .fail(function (jqXHR, textStatus, errorThrown) { // if the error message from the server has any text in it, show it var msg = jqXHR.responseJSON; if (msg && msg.message) { alert(msg.message); } // otherwise, show something generic else { alert('Got an error while uploading images.'); } }); // Summernote will replace ImageInput when next the dialog opens. // But we have to reset it to prevent additional uploading by form itself. $nImageInput.replaceWith($nImageInput.val('').clone(true)); } } })); }; // include summernote language pack, synchronously $.ajax({url: settings.url.language, dataType: "script", complete: initEditor}) // For CodeMirror $sn.on('summernote.codeview.toggled', function() { var cmEditor = $nCodable.data('cmEditor'); if( cmEditor ) { cmEditor.on('blur', function() { origin.value = cmEditor.getValue(); }); } }); // See https://docs.djangoproject.com/en/dev/ref/contrib/csrf/#ajax function getCookie(name) { var cookieValue = null; if (document.cookie && document.cookie != '') { var cookies = document.cookie.split(';'); for (var i = 0; i < cookies.length; i++) { var cookie = jQuery.trim(cookies[i]); // Does this cookie string begin with the name we want? if (cookie.substring(0, name.length + 1) == (name + '=')) { cookieValue = decodeURIComponent(cookie.substring(name.length + 1)); break; } } } return cookieValue; } }); } </script> <script> initSummernote_id_instructor_notes(); </script> <div id="hint_id_instructor_notes" class="help-block">This field is only visible to Staff. Use it to place answer keys or other notes.</div> </div> </div>
```

You can see that this textarea is wrapped inside a div

```html
<textarea name="instructor_notes" cols="40" rows="10" class="summernoteinplacewidget form-control" id="id_instructor_notes" hidden="true"> Bold: &amp;lt;b&amp;gt;This is bold&amp;lt;/b&amp;gt;</textarea>
```


This is from django admin
<img width="1042" alt="Screen Shot 2020-11-07 at 9 14 40 PM" src="https://user-images.githubusercontent.com/10972027/98442196-44269400-213e-11eb-9dd9-7c50820eff9c.png">


And this is what is rendered in the frontend

<img width="861" alt="Screen Shot 2020-11-07 at 9 17 21 PM" src="https://user-images.githubusercontent.com/10972027/98442284-b13a2980-213e-11eb-8d20-fe89f38a38ba.png">

**Comment by smithdc1** [comment]
What happens if you try it without crispy-forms? If it's a text area then I think the input gets rendered by Django itself? 

Also I think this is the expected default behaviour? See Django docs link?

https://docs.djangoproject.com/en/3.1/ref/templates/language/#automatic-html-escaping

**Comment by Peter-Slump** [comment]
Agree with the issue starter @frasern ;  A lot of items are piped through the `|safe` filter this introduces all kind of security vulnerabilities! For us a reason to **not use** this package anymore.

**Comment by smithdc1** [comment]
All of the `|safe` filters have now been removed from the templates except for `help_text`. This is to maintain compatibility with Django itself. See https://docs.djangoproject.com/en/4.0/ref/forms/fields/#help-text
