### ISSUE TITLE
check box input inside label?

### ISSUE THREAD

**Issue by burakk** [django-crispy-forms/django-crispy-forms#297]
I want my check box field to be a single line but django-crispy-forms creates html as below:

``` html
<label class="radio"><input type="radio" name="channel_source" id="id_channel_source_1" value="fromfile">I will add channels and data from a file </label>
```

Why is input inside the label?  And is there a way for single line rendering of field?

**Comment by GracjanZwr** [comment]
"W3 allows inputs to be inside labels, and bootstrap recommends this way of doing things, that's why this is done this way."
@burakk , Do u have any idea Why ???

**Comment by carltongibson** [comment]
It makes the clickable area bigger. 

I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
