### ISSUE TITLE
Crispy-forms' documentation renders with errors in admindocs

### ISSUE THREAD

**Issue by toolness** [django-crispy-forms/django-crispy-forms#299]
I'm not sure whether this is due to a bug in my dependency configuration, admindocs, or docutils, but crispy-forms' documentation renders with errors in the admindocs django app. I've documented this more extensively at https://github.com/toolness/hive-django/issues/1.

**Comment by carltongibson** [comment]
Happy to take input on this but can't consider it an active issue at the moment.
