### ISSUE TITLE
Issue using django-autocomplete-light and crispy forms?

### ISSUE THREAD

**Issue by jrwagz** [django-crispy-forms/django-crispy-forms#300]
I'm having a layout issue with the results box for my django-autocomplete-light fields, and it doesn't happen when I don't use the crispy filter on the form.  I am using bootstrap3.

Here is more details, https://github.com/yourlabs/django-autocomplete-light/issues/253

Any ideas?

**Comment by gdvalderrama** [comment]
What solved it for me was adding `{{ form.media }}` in the template, before the field (not sure if order matters).
