### ISSUE TITLE
Unable to add attributes to FieldWithButton 

### ISSUE THREAD

**Issue by tijmenvandenbrink** [django-crispy-forms/django-crispy-forms#302]
Hi there,

I'm trying to use the placeholder attribute in combination with the FieldWithButton but I can't seem to get it working. This is the piece of code I've got so far:

``` python
class FtpuserForm(forms.Form):
    username = forms.CharField()

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.form_method = 'post'
    helper.form_action = 'create_user'

    helper.layout = Layout(
        FieldWithButtons('username', StrictButton('Go!', type='submit', css_class="btn-success")),
    )
```

Shouldn't we be able to do the exact same thing as with the normal Field Layoutobject:

``` python
Field('field_name', style="color: #333;", css_class="whatever", id="field_name")
```

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
