### ISSUE TITLE
Is there a way to add multiple errors to a field?

### ISSUE THREAD

**Issue by acechorizo** [django-crispy-forms/django-crispy-forms#304]
There aren't any examples I've found to add multiple errors to a field.  In order to accomplish this, I'm adding to forms.util.ErrorList()

```
    if creative_size:
        if creative_size.name == 'Other':
            if comments == '':
                msg = u"Please tell us more about the creative size."
                if 'comments' not in self._errors:
                    self._errors['comments'] = forms.util.ErrorList()
                    self._errors['comments'].append(self.error_class([msg]))
                elif 'comments' in self._errors:
                    self._errors['comments'].append(self.error_class([msg]))

                if cleaned_data.has_key("comments"):
                    del cleaned_data["comments"]

    if creative_type:
        if creative_type.name == 'Other':
            if comments == '':
                msg = u"Please tell us more about the creative type."
                if 'comments' not in self._errors:
                    self._errors['comments'] = forms.util.ErrorList()
                    self._errors["comments"].append(self.error_class([msg]))
                elif 'comments' in self._errors:    
                    self._errors["comments"].append(self.error_class([msg]))

                if cleaned_data.has_key("comments"):
                    del cleaned_data["comments"]   
```

If I add more than one error message to a field, the output for the errors is not styled correctly.

This is the output I see:

<p id="error_1_id_comments" class="help-block">
    <strong></strong>
</p>

<ul class="errorlist">
    <li>
        <strong>
            Please tell us more about the creative size.
        </strong>
    </li>
</ul>

<p></p>

<p id="error_2_id_comments" class="help-block">
    <strong></strong>
</p>

<ul class="errorlist">
    <li>
        <strong>
            Please tell us more about the creative type.
        </strong>
    </li>
</ul>

<p></p>

This is an example of when one error is emitted - this is styled correctly:

<span id="error_1_id_start_date" class="help-block">
    <strong>
        Start date: Enter a valid date.
    </strong>
</span>

I can style the output to mimic the single errors, but I was wondering if there is a way to do it within crispy forms and get the same error output across the board.

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
