### ISSUE TITLE
Remove hard coded hack to bootstrap3 on crispy_forms_field.py

### ISSUE THREAD

**Issue by luzfcb** [django-crispy-forms/django-crispy-forms#306]
@maraujop 

I'm doing a customization template `bootstrap3` as a new template pack at the moment, I simply called `mytemplatepack`. Simply copied the templatepack `bootstrap3` provided by crispy-forms for global templates folder of my project, renaming it to `mytemplatepack`, and changing the references in the html files from `bootstrap3` to `mytemplatepack`.

I added this configuration in settings.py:
`CRISPY_TEMPLATE_PACK = 'mytemplatepack'`

These were the only changes I made. 

After an initial test, checked the generated html was not equal to that generated using the template `bootstrap3`, as was to be expected.

After many tests to try to figure out what I was missing, I checked that there is a hard coded hack for bootstrap3

https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templatetags/crispy_forms_field.py#L116-L121

Is it really necessary that hack?

The same way that I decided to reuse the template provided by crispy-forms, others may have the same idea.

Anyway, thank you for this project.

**Comment by carltongibson** [comment]
Happy to take a PR parameterising things such as this. Due to bandwidth, I'm going to close this as Out of Scope for the moment.  We may have capacity to reconsider in the future.
