### ISSUE TITLE
how to get two check boxes next to next?

### ISSUE THREAD

**Issue by sridhar1982** [django-crispy-forms/django-crispy-forms#313]
I want to have two check boxes next to next like I have shown in the image. The form has other fields, which I have left out here. is it possible to get this using crispy-forms?
![screen shot 2014-04-10 at 5 12 40 pm](https://cloud.githubusercontent.com/assets/4313954/2675074/22d70358-c10e-11e3-9bc9-660cdfc2fa6a.png)

**Comment by carltongibson** [comment]
You'd need to use [a custom Layout ](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html).
