### ISSUE TITLE
aab class in bootstrap3 layouts

### ISSUE THREAD

**Issue by madstacks** [django-crispy-forms/django-crispy-forms#314]
What is the `aab` class in these layout template files

crispy_forms/templates/bootstrap3/inputs.html 
crispy_forms/templates/bootstrap3/layout/formactions.html

https://github.com/maraujop/django-crispy-forms/search?q=aab&ref=cmdform&type=Code

**Comment by zoidbergwill** [comment]
Good question. Would happily see a PR to get rid of these.

**Comment by carltongibson** [comment]
I'm going to close this. I'm happy to take a PR on it, but it's not high priority at the moment.
