### ISSUE TITLE
How can I show in input numbers with 2 decimals?

### ISSUE THREAD

**Issue by fellipeh** [django-crispy-forms/django-crispy-forms#324]
Hi,

in a normal template I can use: {{ myfield|floatformat:2 }}

How can I do these in django-crispy-forms ?

Cheers!

**Comment by carltongibson** [comment]
You'd need to override the specific field template.

**Comment by berdamc** [comment]
> Hi,
> 
> in a normal template I can use: {{ myfield|floatformat:2 }}
> 
> How can I do these in django-crispy-forms ?
> 
> Cheers!

Hi man, you can make it ? Show two decimals on crispy field ?
