### ISSUE TITLE
Independent Helper

### ISSUE THREAD

**Issue by Glideh** [django-crispy-forms/django-crispy-forms#327]
Is there a way to define a standalone helper like:

``` python
class MyHelper(FormHelper):
    form_class = 'form-horizontal'
    label_class = 'col-sm-3'
    field_class = 'col-sm-9'
```

That I could use directly from my templates

``` template
{% crispy my_form my_helper %}
```

---

The [docs says](http://django-crispy-forms.readthedocs.org/en/latest/crispy_tag_forms.html#fundamentals)

> Most of the time, you will want to use the helper attached

That doesn't seem to be my case for 3 main reasons:
- I'm using the same forms in multiple pages with not always the same rendering
- I use the same CSS for most of my forms
- I generally prefer controlling the rendering from the templates

**Comment by shlomozippel** [comment]
I agree with your points and ended up creating a few helpers and exposing them globally to templates via a template context processor.
