### ISSUE TITLE
Add wrapper class support to append prepend text

### ISSUE THREAD

**Issue by petkostas** [django-crispy-forms/django-crispy-forms#328]
It would be nice to add wrapper class support to bootstrap "append prepend text field" (similar to the Field class), that way you can append to the containing element classes, it would add to widgets needing support such datetimepicker js plugins.

**Comment by kevinpostal** [comment]
+1

**Comment by carltongibson** [comment]
@kevinpostal Github have just introduced the reactions button — it's the smiley face with the + next to it — so you don't need to add the +1s. Thanks. 

In general, tested, documented PRs welcome.
