### ISSUE TITLE
Left aligned label for checkboxes

### ISSUE THREAD

**Issue by moimael** [django-crispy-forms/django-crispy-forms#330]
Hi,

I have a form, inside a modal, rendered using django-crispy-forms. Everything is fine, except the checkbox label alignment. I can't find why it is aligned the wrong side.
(the switch is actually a checkbox, and the result is the same if I remove the bootstrap-switch plugin and uses plain checkboxes)

![capture d cran de 2014-05-12 17 44 22](https://cloud.githubusercontent.com/assets/1479859/2946500/689ab9c4-d9ec-11e3-8019-a67778cdccac.png)

Any thoughts ?

Thanks !

**Comment by carltongibson** [comment]
The _fix_ here is to override the field template to generate the HTML you require. (This has to be user-land: we can't possibly support every variation in the templates.)
