### ISSUE TITLE
table_inline_formset.html doesn't display non_form_errors

### ISSUE THREAD

**Issue by benjaminrigaud** [django-crispy-forms/django-crispy-forms#334]
https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap3/table_inline_formset.html

and

https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap/table_inline_formset.html

should use {% include "bootstrap3/errors_formset.html" %} somewhere (before the table?).

Ben

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
