### ISSUE TITLE
extended help on mouseover?

### ISSUE THREAD

**Issue by luke3141** [django-crispy-forms/django-crispy-forms#335]
I've got a few forms where I want some detailed help, though would like to avoid cluttering the page with big chunks of help text. What I would like is a way where on mouseover of a certain element related to a field, I could display some extended help text.

I'm happy to get my hands dirty and implement this myself, though would like some feedback from Miguel/others before I do this. To start with:

a) Is this functionality at all useful to anyone else, or am I just a special case?
b) There appears to be a low level of acceptance of pull requests. Is this because the module is not regularly maintained or there are problems with many pull requests? If the latter, what needs to be done to increase the chances of a pull request being accepted?
c) What's the best method to implement this?
- use the current help_text with a field/switch to choose to display help text block/inline or mouse over?
- create a new field (this seems more versatile). eg: extended_help_text. If so, what name?
- mouse over what? the label? the field? the existing help text, or create a small '?' and mouse over that?

**Comment by carltongibson** [comment]
Creating a custom Layout object would be the way to go. 

I suspect it's not something we'd add to the core library but if you packaged it up (and it looked good) we'd be happy to link to it from the docs.
