### ISSUE TITLE
RadioSelect renders as empty

### ISSUE THREAD

**Issue by larseggert** [django-crispy-forms/django-crispy-forms#337]
A `RadioSelect` in 1.4.0 only seems to render the label and not any options?

Workaround is to manually create the options:

```
{% for radio in form.an_option %}
    <div class="radio">{{ radio }}</div>
{% endfor %}
```

**Comment by rasca** [comment]
This happens to me too, in radioselect.html it searches for the options in field.field.choices when I need it to search in field.field.widget.choices.

Sadly changing this breaks test_custom_django_widget test. I'll have to dig deeper for a fix.

**Comment by keimlink** [comment]
We have the same problem. Is there any solution so far?

**Comment by rasca** [comment]
What I did as a workaround was to set the field choices as well as the widget choices in the form's `__init__`...

Hope this helps you. For the real fix we should create a new templatetag that gives us the choices from the widget if any and otherwise from the field.

**Comment by DebVortex** [comment]
Has anything been done, regarding this Issue? Is there a fix, yet?

**Comment by carltongibson** [comment]
@DebVortex Not yet. PRs welcome.

**Comment by carltongibson** [comment]
Really happy to see any input on this. — A failing test case would be a great start.

**Comment by pdewacht** [comment]
Here's a short failing test case:

    class RadioSelectSampleForm(forms.Form):
        fruit = forms.CharField(
            widget=forms.RadioSelect(
                choices=[('apple', 'Apple'),
                         ('pear', 'Pear')]))
    
    def test_radio_select_widget():
        form = RadioSelectSampleForm()
        html = render_crispy_form(form)
        assert html.count('type="radio"') == 2

The RadioSelect's choices list is ignored when rendering. This is with Django 1.11.3 and crispy-forms 1.6.1.

**Comment by carltongibson** [comment]
I'm happy to look at a PR on this. Other than that I'm going to close this as stale.

**Comment by jacopsd** [comment]
Why was this closed?
I tried release 1.8.1 and the issue is still there: when using a radioselect widget, there is no selection box at all.

**Comment by jacopsd** [comment]
Found the cause of the issue, in my case.
CRISPY_TEMPLATE_PACK was incorrectly configured.

**Comment by glsherid** [comment]
> Found the cause of the issue, in my case.
> CRISPY_TEMPLATE_PACK was incorrectly configured.

I'm seeing this issue now with Bootstrap4 - what did you do to resolve it in the CRISPY_TEMPLATE_PACK?

**Comment by jacopsd** [comment]
CRISPY_TEMPLATE_PACK = "bootstrap4"
