### ISSUE TITLE
Multifield Layout object should have form merged into the context

### ISSUE THREAD

**Issue by jamesmfriedman** [django-crispy-forms/django-crispy-forms#338]
Ran into a fun issue... The HTML Layout object has access to the form context, which is great, unless you are using an HTML Layout object, inside a Multifield Layout, inside a formset...

Here is an example of what I was trying to do but wouldn't work

``` python
     self.layout = Layout(
            MultiField(
                '<button type="button" class="close" tabindex="-1">&times;</button>',
                HTML('<img src="{{ form.media_path }}"/>'),
                'media',
                'tmp_path',
                'media_path',
            )
        )
```

So the issue is there is no concept of the values flowing through the multifield or the current form that is being iterated over in the formset. Simple one line fix, add the form to the context in the Multifield.render method in Layout.py.

``` python
def render(self, form, form_style, context, template_pack=TEMPLATE_PACK):
       #added this line so we now have context for our formset iteration
        context.update({'form': form})

        # If a field within MultiField contains errors
        if context['form_show_errors']:
            for field in map(lambda pointer: pointer[1], self.get_field_names()):
                if field in form.errors:
                    self.css_class += " error"

```

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
