### ISSUE TITLE
Double "form-control" class with bootstrap3

### ISSUE THREAD

**Issue by sergetab** [django-crispy-forms/django-crispy-forms#347]
I've noticed that every input in my form has double "form-control" class. After some debugging I realized the reason is that CrispyFieldNode.render method is called twice for each input. Here is the code from the method

```
...................
if (
  TEMPLATE_PACK == 'bootstrap3'
  and not is_checkbox(field)
  and not is_file(field)
  ):
     css_class += ' form-control'
...................
```

As I understand it is called while creating the layout and again while processing template. I am new to Crispy Forms and not really sure how it's supposed to be.

**Comment by carltongibson** [comment]
Due to age and bandwidth, I'm going to close this for now. Happy to look at it if it comes up again.
