### ISSUE TITLE
"choices" defined at __init__ not detected

### ISSUE THREAD

**Issue by humitos** [django-crispy-forms/django-crispy-forms#351]
Hello,

I'm not sure if this question is valid, but who knows?

The thing is that I have this code and for some X reason I have to set the `choices` attribute for `field` at `__init__` level. So, I've done it like this code shows

```
class MyModel(models.Model):
    field = models.CharField(max_length=31, choices=())

    def __init__(self, *args, **kwargs):
        super(MyModel, self).__init__(*args, **kwargs)
        self._meta.get_field_by_name('field')[0]._choices = config.get_choices()
```

So, when I render the form with crispy-forms the choices are no discovered by crispy and the field input is rendered as a simple text input instead of as a select input.

Is this is the correct behaviour of crispy-forms?

**Comment by carltongibson** [comment]
Not sure. There's not quite enough to go on here. Due to age I'm going to close this. We can reassess if it comes up again.
