### ISSUE TITLE
StaticField is not compatible with widget ReadOnlyPasswordHashWidget

### ISSUE THREAD

**Issue by massa1240** [django-crispy-forms/django-crispy-forms#352]
I am trying to replace the django admin template and using django-crispy forms for rendering the forms, but I had a problem with StaticField when rendering ReadOnlyPasswordHashWidget. The hashed value is rendered instead, which is not I wanted. 

Another thing I tried to do was adding a css_class "form-control-static" directly to the Field(), but it won't work, since crispy_field tag ensures that the class form-control will be added in the final.

Some possible solution I thought to deal with this:
- Create a css class to 'readonlypasswordhashwidget', which is not a good idea
- Create a new template for this case, which also is not a good idea
- Create the possibility to choose whether widget should be ignored or not. However, this only works on those cases when the widget prints a div (e.g: does not work with checkbox or radio buttons, if only the option chosen must be showed, but it wouldn't be a problem as it does not work anyway, because "True" is printed instead of the option chosen)

Have anybody had any problem like this?

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
