### ISSUE TITLE
Cannot use custom template tags / filters

### ISSUE THREAD

**Issue by pterrien** [django-crispy-forms/django-crispy-forms#359]
Hi,

First, let me thank you for this great project, it appears to bring really useful functionality to Django!

I'm facing a problem with the HTML Layout object, and couldn't find any existing issue for it. When using my own custom template filter, I get an _invalid filter_ error when using something like:
`HTML('{{ some_value|my_template_filter }}')`
To have it work, I must write:
`HTML('{% load my_tag_module %}{{ some_value|my_template_filter }}')`

My filter works well, and I correctly added the {% load my_tag_module %} at the beginning of my template file. Moreover, using it outside the crispy form works well. Obviously, the HTML object doesn't seem to inherit the loaded template modules.

Maybe I've missed something ? Anyway a simplistic workaround would be to define a method that will prepend the module loading before the HTML code:

```
def html_with_custom_tags(tag_lib, html_code, *args, **kwargs):
    return HTML("{%% load %s %%}%s" % (tag_lib, html_code), *args, **kwargs)
...
# call the user-defined method instead of HTML object
html_with_custom_tags('my_tag_module', '{{ some_value|my_template_filter }}')
```

I agree, that's not the greatest solution ever, just a "quick-and-dirty" patch... :-)

I don't know if this should be considered an issue, but you may want to add something in the documentation about it?

Cheers,

Pascal.

**Comment by carltongibson** [comment]
This is a known (and documented) limitation. I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
