### ISSUE TITLE
RadioSelect Choice Help Text

### ISSUE THREAD

**Issue by michaelhelmick** [django-crispy-forms/django-crispy-forms#362]
I know choices are supposed to be a 2-tuple of "value, display value" but I came across a need to display help text per choice.

I added a custom template:

``` html
{% if choice.2 %}
    <p class="help-block">{{ choice.2 }}</p>
{% endif %}
```

And in my choice tuple, I just added a third option.

``` python
CHOICES = (
    ('1', 'Some Display', 'This option will do something cool if selected'),
)
```

Does it make sense for crispy-forms to support this behavior?

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
