### ISSUE TITLE
Labels not rendered

### ISSUE THREAD

**Issue by beltiras** [django-crispy-forms/django-crispy-forms#363]
I'm having a problem with labels not rendering at all.    Since I am using Mako I have to build a frontend to crispy and the chosen method is defining a schema for list/dict structure that will be translated into crispy.  I am using version 1.4.0.

```
from crispy_forms.helper import FormHelper
from crispy_forms.layout import (Layout,
                             MultiField,
                             Fieldset,
                             HTML,
                             Row,
                             Div,
                             Field)
from crispy_forms.bootstrap import InlineCheckboxes

from django.template import RequestContext


CRISPY_ELEMENT = {
    'multi':MultiField,
    'fieldset':Fieldset,
    'single':Field,
    }


class CrispyFront(object):

    def __init__(self, request, settings):
        self.helper = FormHelper()
        self.context = RequestContext(request)
        self.context['form_show_errors'] = True
        self.layout = []
        for elem in settings:
            if elem['type'] in CRISPY_ELEMENT:
                self.layout.append(CRISPY_ELEMENT[elem['type']](*elem['args']))

        self.helper.form_class = 'form-inline'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.label_size = 'col-sm-offset-3'
        self.helper.form_show_labels = True
        self.helper.layout = Layout(*self.layout)


    def render_layout(self, form):
        return self.helper.render_layout(form, self.context)
```

settings looks something like this:

```
[{'type':'fieldset', 'args':['heading','field1','field2']},{'type':'single','args':'field3'}]
```

When rendering them naked in django (using .as_p or .as_table), the label shows up without problems.  If I don't define CRISPY_TEMPLATE_PACK as bootstrap, they show up (either by skipping the definition, or setting it to 'uni_form').

The problem seems to be that the variables that control both label class and visibility (form_show_lables most notably) are not passed on to the template.  I read the code a bit to try to be a responsible open-source-community member and ask for a fix via a pull request but have been unable (so far) to find where the problem lies.  I can modify the template source to not take note of form_show_labels and that fixes the problem (althou I can't add a class to a label with any ease).

I will investigate further.

**Comment by ephes** [comment]
Stumbled upon this today, thanks a lot :)
