### ISSUE TITLE
Bootstrap 3 and custom template package

### ISSUE THREAD

**Issue by arnists** [django-crispy-forms/django-crispy-forms#367]
crispy_forms_field.py line 109 of master branch hardcodes the name of the template pack instead of having some sort of template pack _type_ to control whether form-control should be an included class.

Can be solved by changing it to:

'bootstrap3' in TEMPLATE_PACK

**Comment by carltongibson** [comment]
Happy (very happy) to take input on parameterising template packs. Not something we've got the bandwidth to address directly ourselves at the moments.
