### ISSUE TITLE
Feature idea: pass extra context to `Layout` objects when initialising them

### ISSUE THREAD

**Issue by adam-thomas** [django-crispy-forms/django-crispy-forms#371]
Hi @maraujop,

I've been working on an extensive `crispy_form` recently and have come across an interesting limitation.  I have a Fieldset with a custom template, along the lines of:

```
Fieldset(
    '<span>{}</span> {}'.format(section_number, section_title),
    *fields,
    template='custom_fieldset.html'
)
```

I'm not keen on having the `<span>` tags in the Python code, and would rather them be in the template, so that my template could contain something like this:

```
{% if legend %}
    <h3>
        {% if section_number %}<span>{{ section_number|safe }}</span> {% endif %}
        {{ legend|safe }}
    </h3>
{% endif %}
```

with the fieldset itself looking like:

```
Fieldset(
    section_title,
    *fields,
    section_number=section_number,
    template='custom_fieldset.html'
)
```

Unfortunately, there's currently no way to pass additional context `kwargs` into a `Layout` object; the above code just adds a `section-number` attribute to the `<fieldset>` HTML tag.

My suggestion is to add another keyword argument called `context` (or possibly `layout_context` or similar) that would allow us to pass extra properties into the layout template context without having to subclass `Fieldset` (or whichever other layout object is being used).  This would allow:

```
Fieldset(
    section_title,
    *fields,
    context={'section_number': section_number},
    template='custom_fieldset.html'
)
```

Does this sound like something you'd be interested in?

Thanks!

(cc @meshy, @Ian-Foote)

**Comment by durdenk** [comment]
I need the same, 
extra context for my fields.

**Comment by palestamp** [comment]
One more vote for extra context

**Comment by carltongibson** [comment]
Sounds interesting but, I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
