### ISSUE TITLE
Bad alignment of "Delete" checkboxes for formsets rendered using table_inline_formset.html

### ISSUE THREAD

**Issue by eujing** [django-crispy-forms/django-crispy-forms#376]
So I was trying to render a formset as a table with bootstrap 3 and followed the docs, using the table_inline_formset template. 
I wanted the "Delete" column name to appear in my table header, and I did not know of any other way besides overriding table_inline_formset.html at line 23:

Original: {% if field.label and not field|is_checkbox and not field.is_hidden %}
Editted: {% if field.label and not field.is_hidden %}

However, this resulted in bad alignment as shown here:
![image](https://cloud.githubusercontent.com/assets/2179179/4489572/ea8fe120-4a1c-11e4-945d-3eaf86140215.png)

After looking through the elements generated, it seems to be caused by each row's <th> having class "checkbox". Changing it to "form-group" kind of solved the alignment issues:
![image](https://cloud.githubusercontent.com/assets/2179179/4489610/82bec4e8-4a1d-11e4-8868-d7a88670d760.png)

Changing line 9 in field.html seemed to solve the problem for me

Original:
<{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% else %}class="checkbox{% endif %}...
Editted:
<{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" class="form-group...

I'm not sure why checkboxes were treated separately in the first case, maybe there are some cases in which my changes would cause regressions. Or maybe there is a better way to show the delete column?

**Comment by carltongibson** [comment]
Default answer is to override the template — we can't possibly support every HTML variation in the supplied templates. 

If you think it's a more general issue I'm **very happy** to review concrete changes in a PR. This isn't something we have bandwidth to address ourselves at the moment however.
