### ISSUE TITLE
Set custom css class to specific labels

### ISSUE THREAD

**Issue by rpalacios** [django-crispy-forms/django-crispy-forms#379]
Hi.

This is my first time writing something on github. I am a new Django fan too, new python fan, that is trying to get out from the dark Java side.

I am working in a web app. It will have a lot of forms, some one have little bit complex, due it comes from Excel forms that people used to fill.

By example, I want to mix a simpe bootstrap form with a horizontal form. The problem I am trying to handle is that I need to set the css class of especific `Field`'s labels. I know that helper class have a **label_css** property I can set it, but this one will add the css class for all form's labels.

I tried to inherit from `Field` and tried to add this property directly to `Field` object, but it does seem to work.

This is my class:

```
class HorFormField(Field):

    def __init__(self, *args, **kwargs):
        super(HorFormField, self).__init__(*args, **kwargs)

        if 'label_css' in kwargs:
            self.label_css=kwargs.pop('label_css')

        if not 'template' in kwargs:
            self.template = "bootstrap3/hor_form_field.html"
```

And this is `hor_form_field.html` snippet where I trying to use the label:

```
        ...
    {% if field.label and not field|is_checkbox and form_show_labels %}
        <label for="{{ field.id_for_label }}" class="control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}    >>>>>>    {% if field.label_css %}{{ field.label_css }}{% endif %}" <<<<<  >
            {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
        </label>
    {% endif %}
        ...
```

How can I accomplish this I want to do?

Thanks in advance,
Roger

**Comment by carltongibson** [comment]
For extra complex forms you may be better served with a custom template (and rendering the form directly). 

This isn't an addressable issue for Crispy Forms.

**Comment by asimilon** [comment]
This is a shame, I have a large form that I would like to override the label_ and field_ classes for a small handful of fields.  When you say it's not addressable, do you mean no-one is interested in adding this functionality or it's literally impossible within crispy's architecture?  If it's the former I will look into implementing it, if it's the latter I won't waste my time trying :smiley:

**Comment by carltongibson** [comment]
Well , anything is possible. 😃 I’d begin looking at introducing a custom Layiut object, or whether I could get away with just overriding a template. In the limit just using a custom template to render the whole form may be simpler (but if the changes are generic there’s no reason something else won’t work)
