### ISSUE TITLE
Customizing betterform.html?

### ISSUE THREAD

**Issue by danielmanser** [django-crispy-forms/django-crispy-forms#384]
Hi

This is not  really an issue, but a question. I managed to customize `form.html` with the use of `helper.field_template = 'crispy-forms/field.html'`. Now I need to also customize the file `betterform.html`. I'm using the bootstrap3 theme.

How can I accomplish this? I've tried to find it, but didn't succeed. Any help is highly appreciated.

Daniel

**Comment by carltongibson** [comment]
Errr... the template is at `templates/bootstrap3/betterform.html`...
