### ISSUE TITLE
Tooltip or Popover next to form labels

### ISSUE THREAD

**Issue by cyberjoac** [django-crispy-forms/django-crispy-forms#389]
Hi, 
I love Django Crispy and I'm trying to improve the UX in my forms by adding to it bootstrap popovers or tooltips (dynamic bubble that are toggled on hover that shows extra information about the form field).

What would be the best way to go to do that?
I cannot find an easy way to add some pure HTML, next to specific labels..

Thanks for your help.

**Comment by CasJ** [comment]
I am trying to do the same thing....

**Comment by cyberjoac** [comment]
Here's how I did it:
```Python
def popover_html(label, content):
    return label + ' <a tabindex="0" role="button" data-toggle="popover" data-html="true" \
                            data-trigger="hover" data-placement="auto" data-content="' + content + '"> \
                            <span class="glyphicon glyphicon-info-sign"></span></a>'

class DesignForm(ModelForm):
    class Meta:
        model = Design
        fields = ('title', 'description')
        labels = {
            'title': popover_html('Title', "The name of your design"),
        }
```
Enjoy ;-)

**Comment by avenet** [comment]
That was great @cyberjoac, your solution is pretty neat, I loved it.

There are some problems when you want the content variable translated (so you will need to use ugettext_lazy on content), so it tries to create the string for the label and it's translated to the default language. I solved it by translating the whole html (in my case it was static). 

I'm sure that's not an optimal solution, but it's the only one I've found so far.

**Comment by francisjervis** [comment]
This actually produced unexpected results for me - the HTML in the popover_html function was shown as the text in the tooltip! The expected behavior was in fact achieved by just adding the a string for "title" to the field's line in the form's helper method, like so:

    Field('firstNameField', type="text", css_class = "form-control", title = 'Enter your first name'),

**Comment by carltongibson** [comment]
The canonical way to adjust the HTML is to override the templates. (Layout objects take a template parameter.)

**Comment by matthew-a-dunlap** [comment]
I stumbled across this and found it useful. I went with an approach similar to @jhagege's, but I automatically generate the popovers for all fields that have help text (on a per form basis):

```
def popover_labels(model, field_strings):
    fields_html = {}
    for field_string in field_strings:
        field = model._meta.get_field(field_string)

        html = field.verbose_name
        if(field.help_text != ""):
            print(field.help_text)
            html += '<button type="button" class="btn btn-secondary" data-toggle="tooltip" data-placement="top" title="'+field.help_text+'">?</button>'
        fields_html[field.name] = html
    return fields_html

class ManuscriptBaseForm(forms.ModelForm):
    class Meta:
        model = m.Manuscript
        fields = ['title','pub_id','qual_analysis']
        labels = popover_labels(model, fields)
```
