### ISSUE TITLE
use jquery widget in imagefied

### ISSUE THREAD

**Issue by kartikdanidhariya** [django-crispy-forms/django-crispy-forms#405]
Hi,
I am using django 1.7.4

i am using crispytag in my form.py  but now i want to user widget  or jquery plugin for imagefield in my form .py (image upload like in http://olx.in/posting/)

so how can i done that in my form 
pls help!!!
Thanks in advace!!!

**Comment by Zopieux** [comment]
Give a specific `id` and/or `class` to your `file` input. All the rest must be done with standard HTML and Javascript, it has nothing to do with Crispy Forms.

```python
layout = Layout(
   Field('imageupload', id='imagefield', template='my_special_image_template.html'),
   # ...
)
```
Then put your custom logic in `my_special_image_template.html`, referring `#imagefield`.
