### ISSUE TITLE
Make Layout objects attributes accept template tags

### ISSUE THREAD

**Issue by DemersM** [django-crispy-forms/django-crispy-forms#409]
That would be great to be able to do:

```
Submit('submit', 'Submit', onclick='importLayer({{ folder.pk }}'),
```

instead of:

```
HTML('<input type="button" value="Submit" onclick="importLayer({{ folder.pk }})" />'),
```

Is it possible?

**Comment by carltongibson** [comment]
This certainly wouldn't be an obvious change. I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
