### ISSUE TITLE
css_id for Fields is rendered as css-id attribute

### ISSUE THREAD

**Issue by yosemitebandit** [django-crispy-forms/django-crispy-forms#426]
This bit of my layout:

``` python
self.helper.layout = Layout(
  Field('uuid', placeholder='abc123', css_id='uuid-input')
  ..
)
```

was rendered as this HTML:

``` html
<input class="textinput textInput form-control" css-id="uuid-input" 
       id="id_uuid" name="uuid" placeholder="abc123" type="text">
```

I found `css_id` will set the `id` attribute correctly on `StrictButton`.  And I found that I can just use the `id` named argument instead of `css_id` to get things working in `Field`, that is, this worked for me:

``` python
self.helper.layout = Layout(
  Field('uuid', placeholder='abc123', id='uuid-input')
  ..
)
```

**Comment by BodhiSukha** [comment]
Same here as @yosemitebandit

**Comment by James1345** [comment]
Confirmed. 
Python 3.4.2
Django 1.8.2
Crispy Forms 1.4.0

**Comment by carltongibson** [comment]
We need to:

* [ ] review this against 1.5.1
* [ ] (Re)Decide the desired behaviour
* [ ] Add tests to confirm the desired behaviour
* [ ] Make sure that's consistent
* [ ] Make sure the docs are saying the right thing.

**Comment by carltongibson** [comment]
`Field` is the anomaly here. It's documented using `id` directly but pretty much everything else takes `css_id`. 

Very happy to see a PR cleaning that up.
