### ISSUE TITLE
Add import render_crispy_form to example code

### ISSUE THREAD

**Issue by tayden** [django-crispy-forms/django-crispy-forms#431]
```
 from  crispy_forms.utils import render_crispy_form
```

Should probably be added to the docs example here:

http://django-crispy-forms.readthedocs.org/en/latest/crispy_tag_forms.html?highlight=render_crispy_form#render-a-form-within-python-code

**Comment by michalwerner** [comment]
+1

**Comment by carltongibson** [comment]
Fixed
