### ISSUE TITLE
Cannot specify custom Field template anymore

### ISSUE THREAD

**Issue by bmampaey** [django-crispy-forms/django-crispy-forms#441]
Because of the line 437 in crispy_forms/layout.py
template = self.template % template_pack

it is not possible to specify a custom template

**Comment by Paul424** [comment]
I found the same issue and found a workaround as follows:

        try:
            template = self.template % template_pack
        except TypeError:
            template = self.template

I also thought to prefix the custom template with %s/ and move the template itself below that folder (bootstrap3) but that did not work.

**Comment by carltongibson** [comment]
Very happy to see input on this.

**Comment by carltongibson** [comment]
I'll take a PR on this but I'm going to close it pending such input. It's not priority right now.
