### ISSUE TITLE
Review MultiField layout objects to Bootstap (and Bootstrap 3)

### ISSUE THREAD

**Issue by thecardcheat** [django-crispy-forms/django-crispy-forms#478]
Arises due to a change made in 3a1bceebca01d4ac5c6c5d952d05854ea3a79a39, because bootstrap/layout/buttonholder.html and bootstrap3/layout/buttonholder.html do not exist. To reproduce, just try to render any Layout with a ButtonHolder with bootstrap or bootstrap3 template pack.

**Comment by carltongibson** [comment]
@thecardcheat — Argh! Yes. 

Fancy adding those, with a regression test if possible?

**Comment by carltongibson** [comment]
This is not just ButtonHolder but (at least) MultiField too. #428

**Comment by carltongibson** [comment]
Both ButtonHolder and MultiField are documented as being [Uni-Form Only](http://django-crispy-forms.readthedocs.org/en/latest/layouts.html#uni-form-layout-objects). 

I'll review if they make sense for Bootstrap, but if not the answer may end up being "Don't use them".

**Comment by thecardcheat** [comment]
@carltongibson Ah, I had actually looked at the docs to see if there was an intentional exclusion, but just didn't see that section and totally glossed over it in the [Layouts fundamentals](http://django-crispy-forms.readthedocs.org/en/latest/layouts.html) which is what I had followed originally when making layouts. For my purposes then, I will simply remove ButtonHolder so I can upgrade to 1.5.0 now since it makes no apparent visual difference. Let me know if you want assistance defining an Exception for this event, or whatever, depending on what you decide.

**Comment by carltongibson** [comment]
@thecardcheat OK. Thanks!

**Comment by koliber** [comment]
@carltongibson I hope you decide that it makes sense to have `MultiField` in bootstrap/bootstrap3. I would really love to see it in there.

**Comment by carltongibson** [comment]
@koliber My basic thought (currently) is `MultiField` probably reasonably but that `ButtonHolder` is already handled by `FormActions`.

1. I'd be interested in others' comments. 
2. PRs along that line would be welcomed.

**Comment by koliber** [comment]
@carltongibson agreed that `ButtonHolder` and `FormActions` are duplicate technology. As a user who can remember learning pains with crispy forms, I would like to throw out one suggestion. What if the name was standardized on either `ButtonHolder` or `FormActions` for both uni-forms and bootstrap. Backward-compatibility aliases could be put into both so that either name could be used with either template pack. Not having looked through the dev history, I do not see why these two similarly-functioning components should be named differently.

**Comment by carltongibson** [comment]
> ... through the dev history ... 

It may well just be an accident of history. `FormActions` ties in which Bootstrap terminology. `ButtonHolder` would have been around since the _Days Before Crispy Forms_ 

I'd review a PR here but it's not super high priority for me personally.

**Comment by carltongibson** [comment]
ButtonHolder template was added in #520
