### ISSUE TITLE
Class input-group-addon is missed

### ISSUE THREAD

**Issue by 000paradox000** [django-crispy-forms/django-crispy-forms#505]
django-crispy-forms/crispy_forms/templates/bootstrap3/layout/prepended_appended_text.html

In the lines 16 and 18 we should use input-group-addon class instead of input-group

**Comment by darkowic** [comment]
Yes, I found the same problem. I dont understand why someone added there if is select section without
input-group-addon

**Comment by carltongibson** [comment]
A PR would go well here.

**Comment by darkowic** [comment]
I was thinking about this but I don't understand idea behind spiting it in select and input tags

[link to file](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap3/layout/prepended_appended_text.html)

**Comment by carltongibson** [comment]
It may just be an accident of history... 

Indeed it looks like you don't really want to be on that branch at all:

>  Avoid using `<select>` elements here as they cannot be fully styled in WebKit browsers.
> - http://getbootstrap.com/components/#input-groups

**Comment by carltongibson** [comment]
Due to bandwidth, I'm going to close this as an active issue. If someone running into this want's to suggest a fix (in a PR) that would be great.
