### ISSUE TITLE
Request: Allow buttons to be preprended with FieldWithButtons

### ISSUE THREAD

**Issue by stantond** [django-crispy-forms/django-crispy-forms#506]
For text and raw HTML, we have: `AppendedText`, `PrependedText`, `AppendedPrependedText`.

However, `FieldWithButtons` only allows buttons on the right side. Why not the left?

This would be useful for:
- Right-to-left languages
- A button(s) on both sides
  - My own use case - left button fills field with reverse-geocoded address from HTML5 navigator, right button actions on that data

It wouldn't need an additional field, given that only one attribute can ever be a string (unlike the `Text` fields above):
- Both sides: `FieldWithButtons(StrictButton("Left"), 'field_name', StrictButton("Right"))`
- Left side: `FieldWithButtons(StrictButton("Left"), 'field_name')`
- Right side: `FieldWithButtons('field_name', StrictButton("Right"))`

What do you think?

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
