### ISSUE TITLE
Tests that just assert a string object

### ISSUE THREAD

**Issue by zoidbergwill** [django-crispy-forms/django-crispy-forms#527]
While working on bootstrap4 support I came across a couple lines in the tests that just `assert <hardcoded_string>`.

 https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/test_form_helper.py#L598

https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/tests/test_form_helper.py#L605

It looks like they were added [here](https://github.com/maraujop/django-crispy-forms/commit/5c3a2680e2a0a607208e897dc5c278436b69f681)

**Comment by carltongibson** [comment]
Yep. Happy to see these parameterised and the asserts broken down to match what's being tested. (E.g. `test_label_class_and_field_class`: look for exactly the label and field class, which can then be template pack specific.)

**Comment by smithdc1** [comment]
I think we can close this. We've now got the `parse_form(form) == parse_expected("result_file_name")` style. Likely we don't need to go and convert all of the tests (that feels like an overly onerous change!)
