### ISSUE TITLE
Form with URL arguments doesn't work

### ISSUE THREAD

**Issue by fellipeh** [django-crispy-forms/django-crispy-forms#530]
Hi, I have these url:

```
url(r'^city/(?P<city_id>\d+)/$', 'core.views.city_edit', name='desk_core_city_edit'),
```

and these form:

```
class CityForm(ModelForm):
    class Meta:
        model = City
        exclude = ['cod_pais']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'ciityForm'
        self.helper.form_method = 'POST'
        self.helper.form_action = reverse('desk_core_city_edit', args={'city_id': City.pk})
        self.helper.form_class = 'form-horizontal form-bordered'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
            'status',
            'desc',
            Field('uf', css_class="chosen"),
            FormActions(Submit('submit', 'Save', css_class='btn btn-primary'))
        )

        super(City, self).__init__(*args, **kwargs)

```

But when I try to run, show me these error:

```
Reverse for 'desk_core_city_edit' with arguments '('city_id',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['desktop/core/city/(?P<city_id>\\d+)/$']
```

I tried to use `kwargs` instead of `args`, and I got the same error!

The argument is correctly inserted in URL.. why crispy doesn't see that?

Regards,

**Comment by fellipeh** [comment]
I found my problem... 

Here:

```
self.helper.form_action = reverse('desk_core_city_edit', args={'city_id': City.pk})
```

My ```City.pk``` return a object... I try to put  ```City.id``` and show me that City doesn't have ```id```...
How can I use the ID field in these case?

**Comment by mverleg** [comment]
City is the model, not an instance of it, so it doesn't have an id (or pk). Python/Django/Crispy cannot fill that in for you dynamically.

In forms.py you don't have access to request and so you presumably cannot know the required id. You will have to the action-url to the form in the view instead, like so (untested):

def my_view(request):
    city_instance = get_my_city(request)
    self.helper.form_action = reverse('desk_core_city_edit', kwargs={'city_id': city_instance.pk})

Note this is in a view, note the kwargs instead of args and especially note city_instance instead of City.

**Comment by SonofLight** [comment]
You can use the form instance to pass parameters. I used self.instance.parameter in my form_action and it returned the page.  

you have to use the form instance parameter in your view:

`
def city_view(request, city_id):
    city = City.objects.get(pk = 'city_id')
    form = CityForm(request.POST, instance=city)
`

then you are able to access the attributes of your city instance in the form.

`
class CityForm(ModelForm):
    class Meta:
        model = City
        exclude = ['cod_pais']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'ciityForm'
        self.helper.form_method = 'POST'
        **self.helper.form_action = reverse('desk_core_city_edit', args={'city_id': self.instance.pk})**
        self.helper.form_class = 'form-horizontal form-bordered'
        self.helper.label_class = 'col-lg-3'
        self.helper.field_class = 'col-lg-9'
        self.helper.layout = Layout(
            'status',
            'desc',
            Field('uf', css_class="chosen"),
            FormActions(Submit('submit', 'Save', css_class='btn btn-primary'))
        )

        super(City, self).__init__(*args, **kwargs)
`

**FYI: you can do foreign key relations via this as well on your form instance. 
**
_IE: self.instance.user.id_
