### ISSUE TITLE
Crispy doesn't follow Layout using inlineformset

### ISSUE THREAD

**Issue by fellipeh** [django-crispy-forms/django-crispy-forms#533]
Hello, I need to create a inlineformset, and work with crispy.. I have these Helper:

```
class OfertasFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(OfertasFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.layout = Layout(
            Field('Field1', css_class="select-chosen"),
            'Field2',
            'Field3',
            Field('Field4', css_class='form-control input-datepicker-close', placeholder="dd/mm/yyyy",
                  data_date_format="dd/mm/yyyy"),
            'Field5',
            FormActions(Submit('submit', 'Save', css_class='btn btn-primary'),
                        )
        )
```

and my view:

```
    ofertasinlineformset = inlineformset_factory(Author, Books,
                                                     exclude=(),
                                                     can_delete=False)
    helper = OfertasFormSetHelper()
    helper.template = 'bootstrap/table_inline_formset.html'

```

In my template, show me in these order:  Field1 - Field3 - Field2 - Field4 - Field5 ... means.. show me exactly the pos in my models...

It's my mistake, or any problem in crispy?

Cheers

**Comment by aleodoni** [comment]
Hello fellipe, Instead of using this :

ofertasinlineformset = inlineformset_factory(Author, Books,
                                                     exclude=(),
                                                     can_delete=False)

try this :

ofertasinlineformset = inlineformset_factory(Author, Books, form=YourFormsetNameHere,
                                                     can_delete=False)

**Comment by fellipeh** [comment]
Hello @aleodoni ,

I tried, but same problem... :(

When I don't use crispy, django generate 10 time each sql.. using crispy, django generate 20 times each SQL..

**Comment by aleodoni** [comment]
sorry fellipeh, but your previous question wasn't about the field order regarding the model and the helper ?

**Comment by polansky** [comment]
Hi @fellipeh.  I think the issue here is that table_inline_formet.html template doesn't currently support any specified Layout.  The project's author mentions it here:  http://stackoverflow.com/a/18480826/2391062. He also points to the fact that it's documented as such here: http://django-crispy-forms.readthedocs.org/en/latest/crispy_tag_formsets.html#custom-templates-and-table-inline-formsets

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. We may have capacity to reconsider in the future.
