### ISSUE TITLE
FormActions Lazy translation

### ISSUE THREAD

**Issue by ycocatrix** [django-crispy-forms/django-crispy-forms#540]
I cannot manageto do lazy translation in theFormActions

FormActions(
    Submit('save_changes', _(u'Change the social message'), css_class="btn-primary btn-lg m-t-md")       )

**Comment by carltongibson** [comment]
Can you show your imports? You'll need to be using `ugettext_lazy`

I'm going to close this assuming it's not an actual issue. Happy to continue discussion and/or re-open if it is a problem with crispy forms.

**Comment by manikos** [comment]
Unfortunately, this still remains an issue. The `value` is not changed to the specified language until the server is restarted. I tried it in a Django 2.2 and Django 3.1 (python 3.6) environment without any caching activated or anything similar.
