### ISSUE TITLE
Add Bootstrap 4 to docs

### ISSUE THREAD

**Issue by zoidbergwill** [django-crispy-forms/django-crispy-forms#543]
There isn't any mention of the Bootstrap 4 support in the docs. I meant to add it when I originally added the support.

**Comment by shulcsm** [comment]
Can you look into this https://github.com/maraujop/django-crispy-forms/commit/a9477f115261be41a07f8aed34aa63b97db4cbb0#commitcomment-16729911 please? You hardcoded a class that should be resolved from form_style or something.  Now we have a broken horizontal form by default(you have to supply label and field width classes) to get something working. Vertical form is impossible. IMHO default should result in vertical form without any additional configuration.

**Comment by carltongibson** [comment]
@shulcsm Do you want to open a proper issue with a full description and suggested fix? A PR would be even better!

**Comment by shulcsm** [comment]
Sure, sorry. #573

**Comment by carltongibson** [comment]
See #732: I've asked for help finalising Bootstrap 4 support, and we'll do a new release in the autumn before Django 2.0, or sooner if we get lots of input.
