### ISSUE TITLE
Python 3 wheel is missing on PyPI for version 1.6.0

### ISSUE THREAD

**Issue by keimlink** [django-crispy-forms/django-crispy-forms#563]
The wheel for version 1.6.0 has only been uploaded to [PyPI](https://pypi.python.org/pypi/django-crispy-forms/1.6.0) for Python 2, not for Python 3.

**Comment by hellysmile** [comment]
+1, can You release sdist?

**Comment by seocam** [comment]
True! +1 for sdist!

**Comment by keimlink** [comment]
@hellysmile @seocam Why do you want a sdist when you can have a wheel?

**Comment by carltongibson** [comment]
OK — sorry about that — I have no idea what happened. `twine` seems to only want to upload the Py2 Wheel. 

I've uploaded the `sdist` for now. Not perfect but it'll work for you. 

I'll investigate what's broken for the next release.

**Comment by keimlink** [comment]
Thanks for uploading the sdist!

Did you know you can use the test PyPI server to do test releases?

**Comment by carltongibson** [comment]
No I didn't, but it's worked previously... As I say, I'll investigate for the next release. 

Thanks for reporting the issue!

**Comment by kevin-brown** [comment]
Are you sure the wheel is being generated for Python 3, or that it is generated as a universal wheel?

Just noticed this today when reviewing our wheel usage on one of my projects.
