### ISSUE TITLE
Multifield render fail with custom template pack (string formatting error)

### ISSUE THREAD

**Issue by dennyb87** [django-crispy-forms/django-crispy-forms#585]
Hello!
I am getting this error when try to render a Multifield with a custom template pack (django 1.8 - crispy 1.6):

> not all arguments converted during string formatting

The issue come from this [line of code](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/layout.py#L320) in crispy_forms/layout.py:
`field_template = self.field_template % template_pack`

It should probably use an hack like [get_template_name](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/layout.py#L13) in TemplateNameMixin to make it work properly?

**Comment by carltongibson** [comment]
You need to explain the issue a bit better...

**Comment by alexeykuz** [comment]
@carltongibson you cant pass custom field_template to MultField like:
```
        return layout.MultiField(
            ...
            field_template='something/multifield.html',
            template='something/layout/multifield.html'
        )
```
there is hack for `template` exists, but not for `field_template`
https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/layout.py#L13
that probably should be applied also on `field_template`
https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/layout.py#L320

**Comment by carltongibson** [comment]
I'm happy to look at a PR on this. Otherwise I'm going to close this as stale.
