### ISSUE TITLE
{% crispy form %}

### ISSUE THREAD

**Issue by fjbardelli** [django-crispy-forms/django-crispy-forms#589]
tengo el siguiente codigo 

**`Form.py`**

```
# -*- coding: utf-8 -*-
from django.contrib.auth import authenticate
from django.core.exceptions import ValidationError

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML, Button, Row, Field, Fieldset, ButtonHolder, Submit, Column
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django import forms

class ConfirmacionUserForm(forms.Form):

    username = forms.CharField(
        label='Usuario', min_length=3, max_length=20,
        validators=[validate_username],
        required=True,
        error_messages={'invalid': 'Entre 6 y 20 caracteres'})
    password = forms.CharField(
        label='Clave', widget=forms.PasswordInput(),
        validators=[validate_password],
        error_messages={'invalid': 'Clave Incorrecta'},
        required=True)
    confirmacion = forms.CharField(label='Confirmacion', widget=forms.PasswordInput())
    email = forms.EmailField(label='E-Mail',
                             required=True,
                             error_messages={'invalid': 'Mail invalido'})
    telefono = forms.CharField(label='Teléfono Fijo')
    celular = forms.CharField(label='Teléfono celular')

    def __init__(self, *args, **kwargs):
        super(ConfirmacionUserForm, self).__init__(*args, **kwargs)
        helper = FormHelper()
        helper.add_input(Submit('submit', 'Submit'))


    def clean(self):
        if self.cleaned_data.get('password') == self.cleaned_data.get('confirmacion'):
            print('Clave confirmada')
        else:
            print('Clave No confirmada')
            raise ValidationError('La clave no puede ser confimrada.')
        # return super(ConfirmacionUserForm, self).clean()
        return self.cleaned_data

```

**View.py** 

`class ConfirmacionUserView(FormView):
    template_name = "dashboard/confirmacionuser.html"
    form_class = ConfirmacionUserForm
    success_url = "/"

```
def get_initial(self):
    initial = super(ConfirmacionUserView, self).get_initial()
    initial = initial.copy()
    initial['email'] = self.request.user.email
    initial['username'] = self.request.user.username
    self.form_class(initial)
    return initial

def form_valid(self, form):
    if form.is_valid:
        usr = self.request.user
        if usr.provisorio:
            usr.provisorio = False
            usr.username = self.request.POST['username']
            usr.email = self.request.POST['email']
            usr.Clave = self.request.POST['password']
            usr.set_password(usr.Clave)
            usr.save()
        return HttpResponseRedirect('/logout')
    return super(ConfirmacionUserView, self).form_valid(form)`
```

**Template**

`{% extends "index/base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}Confirmación de Usuario{% endblock %}
{% block extra_head %}
    <script src="{% static "js/hideShowPassword/hideShowPassword.min.js" %}" type="text/javascript"></script>
{% endblock %}
{% block site_body %}class="login-page"{% endblock %}

{% block content %}
    <section id="secLogin">
        <div class="row">
            </div>
                    <form name="{{ form.form_name }}" method="post" action="." novalidate> 
                        {% csrf_token %}
                        {% crispy form %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </form>
        </div>
    </section>
{% endblock %}

{% block extra_content %} {% endblock %}`

but when I run it I get the following error and I can not find the cause

![captura de pantalla de 2016-05-16 16 56 48](https://cloud.githubusercontent.com/assets/3776014/15302050/3e9ae17e-1b87-11e6-99bb-6f4535f1d87e.png)

**Comment by SalahAdDin** [comment]
Tenés que pasar el formulario dentro del contexto de la vista, para eso siempre mejor usar un cbv.
Ah, acá toca hablar en inglés creo.

**Comment by carltongibson** [comment]
Supongo qué esto ha sido resolvado. Si qué no haga un comentario.
