### ISSUE TITLE
Broken styles when using FormHelper

### ISSUE THREAD

**Issue by MichaelPavlov** [django-crispy-forms/django-crispy-forms#592]
I'm using crispy-forms and django-filter. And I'm trying to customize my form. Here is a snippet:

```
class FilterForm(Form):
    def __init__(self, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'get'

        self.helper.layout = Layout(
            Row(
                Div('country', css_class='col-sm-3'),
                Div('brand', css_class='col-sm-3'),
            )
        )
```

Can you guys hint me why the arrow button in select control shrinks like this? I guess it somehow has to do with FormHelper

![selection_008](https://cloud.githubusercontent.com/assets/17099703/15448388/748287b6-1f69-11e6-9a31-9d462fe6eabf.png)

**Comment by carltongibson** [comment]
@MichaelPavlov Sorry for the slow uptake here. I'm afraid there just isn't enough to go on. I assume by now you've found a work around.

**Comment by MichaelPavlov** [comment]
@carltongibson It was the default style for selectbox in firefox. Thanks for the reply anyway. Cheers.
