### ISSUE TITLE
CSS class get *appended* instead of set

### ISSUE THREAD

**Issue by gtrman** [django-crispy-forms/django-crispy-forms#602]
At this point https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/layout.py#L185 css_classes get _appended_, which is a bit awkward. It took me some time to figure out where that btn-primary kept coming from. Better change it to explicitly set value.

**Comment by zoidbergwill** [comment]
What about making your own custom CSS class that sets the different field_classes?

There are definitely cases where both appending and setting would be useful.

**Comment by gtrman** [comment]
> What about making your own custom Submit class that sets the different field_classes?

Really don't know how to respond to this. It _feels_ like "make your own, this is how we do it". Still, remains that its is an undocumented "feature", and in my eyes unwanted. If you'd use the value as a fallback value, I'd have no problem with it.

**Comment by zoidbergwill** [comment]
So `field_classes` isn't used in as many places as I thought, so having it documented that they are the defaults for the different template packs, but overridden with `css_classes` makes sense, but then maybe we should change the name of that `arg` to `field_classes` too.

You're welcome to submit a PR.

**Comment by carltongibson** [comment]
I'm going to close this as something we just don't have the bandwidth to take on as an Active Issue.

I'm happy to review PRs addressing it from a docs or code POV but it's not something we can allocate time to right now.
