### ISSUE TITLE
Button submit doesn't pass in the form signal post 

### ISSUE THREAD

**Issue by SalahAdDin** [django-crispy-forms/django-crispy-forms#604]
Hi guys, i have the next but: 
I have a submit button with a name:

``` python
Div(
                Submit(
                    'change_password',
                    'Cambiar',
                    css_class='btn fill green',
                ),
                css_class='btn-container',
            ),
```

And in the view i have to workflow that depends of name button:

``` python
def post(self, *args, **kwargs):
        """ Handle userprofile forms
        """
        request = self.request

        if 'change_password' in request.POST:
            form_password = ChangePasswordForm(
                request.POST,
                instance=request.user,
            )
```

But when i click in the button i have other performance that isn't expected. Investigating deeper in the html request i found this:
![problemacrispyforms](https://cloud.githubusercontent.com/assets/5034215/16702906/c84a358e-452e-11e6-8b78-7cff732de088.png)

Where are the button name???

Other field's values are passing in the post signal, but the button isn't it.
![changepasswordform](https://cloud.githubusercontent.com/assets/5034215/16702953/189fb4aa-452f-11e6-8fc5-7e8b35a3bdd5.png)

So, what's wrong?

**Comment by durdenk** [comment]
If your post request is an ajax request, that doesn't pass button values by default. Its an javascript issue.

**Comment by carltongibson** [comment]
I'm afraid there's not enough to go one here. If the generated submit has the `name` attribute set then it will be passed by the browser when you POST the form.
