### ISSUE TITLE
Crispy filter does not include form media after 1.6.0 release

### ISSUE THREAD

**Issue by sbrand83** [django-crispy-forms/django-crispy-forms#605]
The crispy filter does not include a form's media anymore since release 1.6.0.  This appears to be a bug as in the previous release, 1.5.2, the crispy filter when applied to a form or formset's context variable would include the form's media when rendered.

**In the template**

```
{% load crispy_forms_filters %}
...
{{ form|crispy }}
```

**Form class**

```
class MyForm(forms.Form):
    date=forms.DateField(
        label='Approved',
        required=True,
        widget=DatePlaceholder,
     )
...
```

The date field uses a widget that requires some javaScript and CSS to work correctly.  These files are included in the form's media when constructed in the view.

In version 1.5.2, this media would be included in the rendered html as seen below:

```
<link href="/path/to/jquery-ui-1.8.18.custom.css" type="text/css" media="all" rel="stylesheet">
<link href="/path/to/jquery-ui.css" type="text/css" media="all" rel="stylesheet">
<link href="/path/to/autocompleteselects.css" type="text/css" media="all" rel="stylesheet">
<script type="text/javascript" src="/path/to/jquery.autocompleteselects.js"></script>

<div id="div_id_approved_date" class="control-group"> 
    <label for="id_approved_date" class="control-label ">
         Approved
    </label>
    <div class="controls">
        <input class="dateinputwithplaceholder input-block-level" id="id_approved_date" name="approved_date" placeholder="mm/dd/yyyy" type="text">
    </div>
</div>
```

However, when using version 1.6.0, without changing any code, this is the rendered html:

```
<div id="div_id_approved_date" class="control-group"> 
    <label for="id_approved_date" class="control-label ">
         Approved
    </label>
    <div class="controls">
        <input class="dateinputwithplaceholder input-block-level" id="id_approved_date" name="approved_date" placeholder="mm/dd/yyyy" type="text">
    </div>
</div>
```

As you can see, the form media is no longer being included when being rendered by the filter.

This seems like it is a bug introduced between release 1.5.2 and 1.6.0.
It initially seems like this could be related to the changes from #525 with the optional inclusion of form media when using the `crispy` template tag. Perhaps the include_media context variable is not being set correctly.

**Comment by troyshu** [comment]
I'm seeing this issue as well in crispy 1.6.0. I'm using Django 1.10, if that matters. 

Anyways, the workaround that I'm using for now is the one at https://github.com/django-crispy-forms/django-crispy-forms/issues/263: to use `{{ form.media}}` to render the form's media assets.

**Comment by carltongibson** [comment]
#525 added a `include_media` FormHelper attribute. 

Can you check this is `True` and report back? 

I'm not expecting to see this issue...

**Comment by carltongibson** [comment]
Reviewing #525, I'm going to close this. `include_media` has good test coverage but defaults to `False` — that'll be your issue. 

**If** it's not come back and we can re-open.

**Comment by troyshu** [comment]
Thanks for pointing that out! In my form, `self.helper.include_media` is `True` (not from me setting it, but just from the initialization of `self.helper` with `self.helper = FormHelper()`).

I, like the original poster, was using the filter to render a form`{{ form|crispy }}`, perhaps mistakingly. The issue goes away when I use the crispy tag `{% crispy form %}` to show my form. Is that the desired behavior?

**Comment by carltongibson** [comment]
Ah, yes. The crispy filter...

> Is that the desired behavior?

That's a good question.

**Comment by carltongibson** [comment]
(Initially leaning towards "Yes" — not least to encourage people not to use it 🙂)

**Comment by carltongibson** [comment]
I'm going to come down on the yes side. Closing this.
