### ISSUE TITLE
HTML 5 attribute required is included in FileField and is not necessary when is already a file in the field

### ISSUE THREAD

**Issue by 000paradox000** [django-crispy-forms/django-crispy-forms#610]
![chrome](https://cloud.githubusercontent.com/assets/2762494/17811258/6e262f3e-65e7-11e6-859a-8a580bb39f0d.png)
![ff](https://cloud.githubusercontent.com/assets/2762494/17811259/6e2aca76-65e7-11e6-96a3-2bc233c9039b.png)

**Comment by smithdc1** [comment]
So by now crispy-forms now relies on Django for rendering the `required` attribute.
