### ISSUE TITLE
Writing dynamic (form-agnostic) layout objects

### ISSUE THREAD

**Issue by hheimbuerger** [django-crispy-forms/django-crispy-forms#611]
I've found the following line in [templatetags/crispy_forms_tags.py#L132](https://github.com/maraujop/django-crispy-forms/blob/dev/crispy_forms/templatetags/crispy_forms_tags.py#L132):

```
# If we have a helper's layout we use it, for the form or the formset's forms
if helper and helper.layout:
```

Shouldn't that be as follows instead?

```
if helper is not None and helper.layout is not None:
```

The reason is that right now, the truthyness check is based on the `__len__` methods implemented by `LayoutObject` (thereby False if it has no fields) and `FormHelper`'s base class `DynamicLayoutHandler` (thereby False if it either has no layout object or that layout object has no fields).
This is because Python uses [__len__ in absence of __nonzero__ to determine truthyness](https://docs.python.org/2/library/stdtypes.html#truth-value-testing).

The reason for this suggested change is that I'd like to write a layout object which is form-agnostic, i.e. it applies a certain behavior dynamically to any form it gets thrown at. Right now, this doesn't appear to be easily possible.

Would you agree that this change expresses the intention of that line better? I don't see why that check would be based on the existence of fields.

I believe this expression is also related to the documentation stating the following in the [Helper attributes you can set](http://django-crispy-forms.readthedocs.io/en/latest/form_helper.html#helper-attributes-you-can-set):

> field_template
> When set allows you to render a form/formset using a custom field template. Default template is at {{ TEMPLATE_PACK }}/field.html. Beware that this is only effective when setting a FormHelper.layout.

When initially reading this, I didn't understand why a layout is necessary to make the `field_template` take effect. I'd like to be able to set a `field_template` without having to write my own layout object.

For that, I'm using the following workaround subclasses for now:

```
class NoopLayout(Layout):
    """
    A special layout manager for crispy, used to unlock some functionality in crispy (like custom field templates),
    which are only available when a layout manager is used, even though none is needed.

    So this layout manager just pretends to know how to lay out any form, but then when it is asked to lay out an
    actual form, it will just return the fields in the order from the form.
    """
    def __nonzero__(self):
        """ This is just to convince the crispy template tag that we're a valid layout object, which knows
            about fields (even though we have no clue yet!).
        """
        return True

    def render(self, form, *args, **kwargs):
        # now we know the actual form fields!
        self.fields = form.fields.keys()

        # [TODO: we could do something with this specific form's fields here]

        # let the base class handle the actual rendering of fields into HTML
        return super(NoopLayout, self).render(form, *args, **kwargs)

class LazyLayoutFormHelper(FormHelper):
    """
    A simply FormHelper subclass which changes behavior of the base class in only one aspect: the original
    FormHelper is truthy if and exactly if it has a layout object and that layout object has at least one field.
    This is due to its base class DynamicLayoutHandler overriding __len__, which is Python uses in absence of
    a __nonzero__ implementation to determine truthyness.

    A LazyLayoutFormHelper however is always truthy, no matter whether it has a layout object and how many
    fields that layout object has. Thereby it always passes the crispy template tags helper existence checks.
    """
    def __nonzero__(self):
        return True
```

This allows to write a form helper like this, which can be used with any simple Django form, like the `django.contrib.auth` forms (haven't tried any more complex ones):

```
my_helper = LazyLayoutFormHelper()   # we need a special FormHelper when using NoopLayout, because otherwise crispy will believe our layout object is invalid
my_helper.layout = NoopLayout()   # field_template has no effect unless a custom layout object is used
my_helper.field_template = 'my-custom-field.html'
```

**Comment by zoidbergwill** [comment]
@hheimbuerger Would happily approve a PR for this, sounds like the current behaviour is unintended behaviour to me, so it should keep backwards compatibility too.

**Comment by carltongibson** [comment]
@hheimbuerger I'm happy to look at specific PRs around this but it's not something I want to allocate bandwidth to directly. 

`FormHelper` instances are initialised with a default layout — which will apply the `field_template` when rendered. (I removed the misleading doc remark in 2183a831fa6a727ee51e5d66bf33979f73dd6527)

See [`build_default_layout`](https://github.com/django-crispy-forms/django-crispy-forms/blob/dev/crispy_forms/helper.py#L226-L227). Does this not already do what your `NoopLayout` provides? 

Again: happy to review concrete additions.
