### ISSUE TITLE
Problems with Bootstrap 4 formatting hack in helper.FormHelper

### ISSUE THREAD

**Issue by pydanny** [django-crispy-forms/django-crispy-forms#613]
In [Cookiecutter Django](https://github.com/pydanny/cookiecutter-django) we've discovered that when using Bootstrap 4, there is a bit of code in Crispy Forms which is causing us a lot of problems. This code is caused us serious problems with all our forms:

```
class FormHelper(DynamicLayoutHandler):
    ...
    if template_pack == 'bootstrap4':
        grid_colum_matcher = re.compile('\w*col-(xs|sm|md|lg|xl)-\d+\w*')
        using_grid_layout = (grid_colum_matcher.match(self.label_class) or
                             grid_colum_matcher.match(self.field_class))
        if using_grid_layout:
            items['using_grid_layout'] = True
```

Our issues with the above approach:

1. Fragile: Hardcoding like this assumes Bootstrap 4's API doesn't change (it does)
2. Unforgiving: Doesn't allow for any variation in template design
3. Really Unforgiving: No way to override this behavior
4. Undocumented: No mention in the documentation, or it's too hard for me to find

Right now our solution is to implement our own hack to get around this behavior, which is not ideal and something we want to fix.

**Comment by carltongibson** [comment]
Yep. OK. On a currently mission to get Django Filter down to Inbox Zero then another pass at Crispy Forms is next on my list. 

There are a couple of Django 1.10 related items in `master` already so I'm looking to do a small release _soon_.

Do you have a specific fix in mind?

**Comment by pydanny** [comment]
Here's what I would do:

1. Provide some way to override the behavior in that code snippet. Perhaps allow setting of an attribute on the FormHelper() class so you could have: `if using_grid_layout or not self.using_grid_layout:`
2. Document the heck out of whatever override you do

**Comment by carltongibson** [comment]
OK. 

Presumably the branch here was just added to mirror the existing (long time) code for the uniform and bootstrap 3 template packs. 

First question is whether the code here would be OK if corrected — I.e. does this just come up because Bootstrap 4 hasn't settled yet, still being in development — or is there something about Bootstrap 4 that means it requires a different approach entirely. 

This leads to the second question, which is, can you explain the actual errors your seeing so we have some idea of what exactly needs fixing. And what we're aiming for?

**Comment by zoidbergwill** [comment]
Thanks for all the input, @pydanny.

This support was added when Bootstrap 4 was still quite early alpha, and it was added to fix [a specific issue](https://github.com/maraujop/django-crispy-forms/issues/573). There was a fair amount of discussion around trying to find a better solution.

While Bootstrap 4 is alpha, I think it's hard for a library to perfectly support it. Though I understand your frustration with me adding a "hack" that also wasn't well documented.

> Right now our solution is to implement our own hack to get around this [behaviour], which is not ideal and something we want to fix.

~Would this hack fit upstream?~ 

Which is removing the `row` class for `form-group`s.

I'll happily make the PR for a more appropriate solution for that issue, if you have one?

I'll take a look at it more tomorrow too, to see if I can find a better solution, or if that hack isn't necessary anymore for use with flexbox.

**Comment by pydanny** [comment]
@zoidbergwill, the problem we had is that the `row` attribute made it so that input fields and their label did not line up. It's impossible to override this with the current Crispy Form design, hence why I suggested an override. As to our hacky fix: https://github.com/pydanny/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/%7B%7Bcookiecutter.project_slug%7D%7D/static/js/project.js#L21:

``` javascript
$('.form-group').removeClass('row');
```

Yes, it's a global JQuery command to remove the `row`. 😝

**Comment by zoidbergwill** [comment]
So I've finally had a chance to look at this. Sorry for taking so long.

The issue is this part in the [migration guide](https://raw.githubusercontent.com/twbs/bootstrap/v4-dev/docs/migration.md) from Bootstrap 4:

> - Horizontal forms overhauled:
>   - Dropped the `.form-horizontal` class requirement.
>   - `.form-group` no longer applies styles from the `.row` via mixin, so `.row` is now required for horizontal grid layouts (e.g., `<div class="form-group row">`).
>   - Added new `.form-control-label` class to vertically center labels with `.form-control`s.

I think I need to revert the commit of mine, so we don't need people to add hacks like that.

I don't know what the best solution is to fix this, but I guess we're gonna need to include backwards incompatible changes, and then recommend people add field classes for every field in a horizontal form, or add a `FormHelper` field for it, and document a bunch of stuff solely for Bootstrap 4.

**Comment by carltongibson** [comment]
OK. Awesome. 

I think adjusting so it's right and then adding a note to the Change Log so people know how to update is the best approach. 

(Bootstrap 4 support is beta at least as long as Bootstrap 4 is, and probably until we've had some feedback from real world usage to go with that too.)

**Comment by zoidbergwill** [comment]
So adding a `wrapper_class` to each field for a horizontal form is how people are gonna need to get horizontal forms working like [this](https://github.com/zoidbergwill/crispy-test-project/commit/65827192c6e25bc74b45d590a2500b6270ac4eed).

Not sure if we should document it somewhere?

**Comment by yunti** [comment]
Presumably you could set `wrapper_class` at the helper level rather than at every field in layout to keep things DRY?

**Comment by zoidbergwill** [comment]
The issue is it's a field level wrapper class, not form level. Unless we supported overriding the default field wrapper class at form level.
