### ISSUE TITLE
how to run the tests?

### ISSUE THREAD

**Issue by codepython** [django-crispy-forms/django-crispy-forms#619]
thanks.

**Comment by codepython** [comment]
_pytest.config.ConftestImportFailure: (local('/Users/git/python/django-crispy-forms/crispy_forms/tests/conftest.py'), (<class 'ImportError'>, ImportError("No module named 'django'",), <traceback object at 0x103309a88>))

**Comment by zoidbergwill** [comment]
How are you running the tests?

Are you using `make test`?

**Comment by zoidbergwill** [comment]
Hi @codepython

This is mentioned in the docs [here](https://github.com/django-crispy-forms/django-crispy-forms/blob/dev/docs/contributing.rst), so I'm closing this issue unless those instructions aren't working.

Thanks.
