### ISSUE TITLE
Bootstrap 4 support.

### ISSUE THREAD

**Issue by tutuca** [django-crispy-forms/django-crispy-forms#620]
There is some pressure to release the fourth version of Bootstrap [1].

Are there plans to update crispy forms template to match?
Is there some current effort ongoing?

[1]http://blog.getbootstrap.com/2016/09/05/bootstrap-4-alpha-4/

**Comment by zoidbergwill** [comment]
It is supported in the [latest version](https://github.com/maraujop/django-crispy-forms/blob/dev/CHANGELOG.md#changelog-for-django-crispy-forms), it just isn't mentioned in the docs much, if at all.

**Comment by carltongibson** [comment]
With #621 incoming, I think we can close this. (Docs can always be improved but at least it will be mentioned.)
