### ISSUE TITLE
Add William Martin Stewart as Co-Maintainer

### ISSUE THREAD

**Issue by carltongibson** [django-crispy-forms/django-crispy-forms#622]
@zoidbergwill has been a constant presence since I took-on supporting crispy-forms. Not least he's responsible for the Bootstrap 4 support. 

I'd like to add him as maintainer. He deserves it. 

@zoidbergwill: Would you be keen? It would be good to have you. It would be nice to clean up the remaining issues/PRs, modernise the docs and so on. What do you say? 🙂

@maraujop: If @zoidbergwill is keen, could you make the change? 

(Aside: maybe it's time for a crispy forms org?)

**Comment by zoidbergwill** [comment]
@carltongibson Awesome. Thank you.

Definitely. 🙏. Would love to help wherever I can.

**Comment by maraujop** [comment]
Hi both,

All I can say is that I totally trust your opinion on this Carlton and I'm more than happy to add William as a maintainer of crispy-forms. Thanks both for all your incredible work 👏 

I agree that this project should move to an organization, I should have probably moved this long time ago. I've learnt a lot about how not to maintain an open source project and burnout with it. I'm currently not using crispy-forms in any of my projects, I'm lately doing a lot of React Native and Javascript, but I would be happy to stay in the organization, maybe in the future I find some time or start using it.

To be honest, I consider using an open source project a major condition to be effective in maintaining it.

Shall I create the organization and add you guys with full powers? I've never done this before, so I'm not 100% sure how this goes.

Let me know, cheers
Miguel

**Comment by carltongibson** [comment]
> Shall I create the organization and add you guys with full powers? I've never done this before, so I'm not 100% sure how this goes.

Sounds great! Me neither... 😱

**Comment by carltongibson** [comment]
@maraujop — I'd ask that you definitely stay in the Org. I think we're OK 90% of the time but your knowledge of the project is too important to loose.

**Comment by carltongibson** [comment]
@maraujop Awesome! Thanks for setting us up. 👍

**Comment by maraujop** [comment]
Ok,

So we are now officially an organization and I'm really happy with it. Welcome aboard @zoidbergwill , enjoy the open source ride :)

Cheers,
Miguel

**Comment by zoidbergwill** [comment]
Awesome, thank you, both. 🙏

**Comment by zoidbergwill** [comment]
All we need now is a pretty organisation logo. 😋
