### ISSUE TITLE
@zoidbergwill How does this sound to you?

### ISSUE THREAD

**Issue by zoidbergwill** [django-crispy-forms/django-crispy-forms#629]

**Comment by zoidbergwill** [comment]
Now it looks like I'm talking to myself. 😋 

@carltongibson All of this sounds great to me.

I think using issues for project management is the only way to keep getting e-mails and stuff. :/

Since I got no e-mails about the project or card mentions. :/

**Comment by carltongibson** [comment]
OK. Great. 

No rush on anything but heading towards: 

1. Less open issues/PRs
2. Extracting Template Packs
3. Better docs. 

(Not much more to say — I'm going to close this as non-actionable 😀)

**Comment by zoidbergwill** [comment]
Sounds great to me. Better docs and less open issues both sound great, and will be easier with extracted template packs too.
