### ISSUE TITLE
Bootstrap3 help text template does not set display-inline if help_text_inline

### ISSUE THREAD

**Issue by gsvaldes** [django-crispy-forms/django-crispy-forms#634]
In `crispy_forms/templates/bootstrap3/layout/help_text.html`
the css class is not set to help-inline when help_text_inline is True
```
% if field.help_text %}
    {% if help_text_inline %}
        <span id="hint_{{ field.auto_id }}" class="help-block">{{ field.help_text|safe }}</span>
    {% else %}
        <p id="hint_{{ field.auto_id }}" class="help-block">{{ field.help_text|safe }}</p>
    {% endif %}
{% endif %}
```

However, this is the case in the Bootstrap 2 help_text template
`crispy_forms/templates/bootstrap/layout/help_text.html`
```
{% if field.help_text %}
    {% if help_text_inline %}
        <span id="hint_{{ field.auto_id }}" class="help-inline">{{ field.help_text|safe }}</span>
    {% else %}
        <p id="hint_{{ field.auto_id }}" class="help-block">{{ field.help_text|safe }}</p>
    {% endif %}
{% endif %}
```
I believe that the Bootstrap3 help_text template should match the one for Bootstrap 2.

**Comment by zoidbergwill** [comment]
Hi @gsvaldes 

Thanks for the report.

`help-inline` doesn't exist in Bootstrap 3 and [and their migration guide](https://getbootstrap.com/migration/#dropped) recommends using help-block.
