### ISSUE TITLE
Bootstrap 4 horizontal forms button is slightly off the line

### ISSUE THREAD

**Issue by RoboAndie** [django-crispy-forms/django-crispy-forms#636]
I was checking out the fix for issue #613 with the row class being applied on all form-groups in Bootstrap 4 templates. So far it looks good, but I've found one small issue. In horizontal forms, the submit button is slightly out of line - it should line up with the input fields, but it's a little off. It looks like the wrapper_class is not being applied to the form-group div that's wrapping the button.

Here's the helper code I'm using:

```
self.helper.wrapper_class = 'row'
self.helper.label_class = 'col-md-2'
self.helper.field_class = 'col-md-10'
self.helper.add_input(Submit('submit', 'Save'))
```

**Comment by carltongibson** [comment]
Hi @RoboAndie — Thanks for the report! 

> It looks like the wrapper_class is not being applied to the form-group div that's wrapping the button

Could you possibly post:

* a screenshot
* The actual generated HTML
* The expected HTML

That would make the next step a lot easier/quicker. Thanks!

**Comment by RoboAndie** [comment]
Absolutely!
Here's the screenshot:
<img width="983" alt="screen shot 2016-09-29 at 7 33 24 pm" src="https://cloud.githubusercontent.com/assets/1588659/18976931/b07d455c-867b-11e6-8333-2963eaf30828.png">

It's slight, but the "Save" button is just a little bit out of line - it should be lined up with the text boxes.

Here's the actual HTML:
```
<form method="post">  
    <div id="div_id_first_name" class="form-group row"> 
        <label for="id_first_name" class="form-control-label col-md-2">First name</label> 
        <div class="col-md-10"> 
            <input class="textinput textInput form-control" id="id_first_name" maxlength="50" name="first_name" type="text" value="Andrea">
        </div> 
    </div> 
    <div id="div_id_last_name" class="form-group row">
        <label for="id_last_name" class="form-control-label col-md-2">Last name</label> 
        <div class="col-md-10"> 
            <input class="textinput textInput form-control" id="id_last_name" maxlength="50" name="last_name" type="text" value="Rockley"> 
        </div> 
    </div> 
    <div id="div_id_email" class="form-group row"> 
        <label for="id_email" class="form-control-label col-md-2 requiredField">Email address<span class="asteriskField">*</span> </label> 
        <div class="col-md-10"> 
            <input class="emailinput form-control" id="id_email" maxlength="500" name="email" type="email" value="andrea.robertson25@gmail.com"> 
        </div> 
    </div> 
    <div class="form-group"> 
        <div class="aab col-md-2"></div> 
        <div class="col-md-10"> 
            <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit-id-submit"> 
        </div> 
    </div> 
</form>
```

All is okay, except for that last `<div class="form-group">`, which should have the "row" class applied, too.
```
    <div class="form-group row"> 
        <div class="aab col-md-2"></div> 
        <div class="col-md-10"> 
            <input type="submit" name="submit" value="Save" class="btn btn-primary" id="submit-id-submit"> 
        </div> 
    </div> 
```

**Comment by zoidbergwill** [comment]
Thanks for your report, @RoboAndie 

I'm gonna look into it.

**Comment by RoboAndie** [comment]
Okay, this is working for me, thanks!

It would be helpful if you could add the class to inputs, too. I'll keep watching for updates. 👍 

Thanks again!

**Comment by carltongibson** [comment]
See #732: I've asked for help finalising Bootstrap 4 support, and we'll do a new release in the autumn before Django 2.0, or sooner if we get lots of input.
