### ISSUE TITLE
guys check this out

### ISSUE THREAD

**Issue by koopg** [django-crispy-forms/django-crispy-forms#647]
http://stackoverflow.com/questions/40323795/strange-behavior-when-using-crispy-forms-in-template

can anyone please tell me why is it happening

**Comment by koopg** [comment]
when using 
I get my form display as i wanted and it have to be commented
else 
I am getting duplicate forms and submit button wont work ?

**Comment by zoidbergwill** [comment]
Hi @koopg Could you share code for easily reproducing this?

**Comment by carltongibson** [comment]
I'm going to close this. It's not an actionable issue as it stands. Happy to help if you can provide more info — but there really isn't enough to go on here.
