### ISSUE TITLE
Button with a dropdown.

### ISSUE THREAD

**Issue by AmmsA** [django-crispy-forms/django-crispy-forms#649]
### Description:
This is more of a question, just wondering if it's possible to do it in crispy form or if I need to make a custom widget.

In bootstrap4 (maybe bootstrap3), you can have a button with a drop down. See [here](http://v4-alpha.getbootstrap.com/components/input-group/#buttons-with-dropdowns).

Can I do an `IntegerField` that uses this input? I want to allow the user to put in his input, but with the option of choosing one of the default values shown in the dropdown list. Choosing one of the values of the dropdown automatically fills the input field.

**Comment by tomedelliott** [comment]
Bootstraps drop down is not a form input, so what you select using the input-group-addon would not be passed through to the form.

You can add the input-group-addon using crispy_forms.bootstrap [AppendedText](https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#bootstrap-layout-objects). You would then need a hidden input element and some javascript to pass the data from the drop down in to the hidden input.

**Comment by tomedelliott** [comment]
you could also use a select in the [input-group-addon](http://codepen.io/anon/pen/QGpvje)
