### ISSUE TITLE
How to use django crispy forms with django inline formsets?? (Solved)

### ISSUE THREAD

**Issue by ibarovic** [django-crispy-forms/django-crispy-forms#65]
Hello,

I was wondering if it is possible to use django crispy forms with django inline formsets, and if so how can that be accomplished?

I have two models related via a foreign key. I am using an inlineformset_factory for processing models inside a django view and for displaying (rendering in a template) I would like to use advantages of crispy forms.

I tried following in my template:

<pre><code>&lt; form method="post" action="" &gt;
       
   {% load crispy_forms_tags %}
   {% crispy form %}
   {% crispy formset %}

   &lt;input class="submit" type="submit" value="Submit data"&gt;

&lt;/form&gt;</code></pre>

There are a few problems with this:
1) There are two forms (form and formset) rendered inside another form which I don't like at all :-), like this:

<pre><code>&lt;form&gt;
    &lt;form name=”crispy_form”&gt;”data”&lt;/form&gt;
    &lt;form name=”crispy_formset”&gt;”data”&lt;/form&gt;
    &lt;input class="submit" type="submit" value="Submit data"&gt;
&lt;/form&gt;</code></pre>

2) ManagementForm data is not rendered (form-TOTAL_FORMS, form-INITIAL_FORMS and form-MAX_NUM_FORMS).

3) Submit button posts no data to server for processing because the outer form doesn't have any data. This problem can be resolved using javascript code to submit both forms but this is not the django way :-).

If necessary I could post a full example with models, forms, view, url and html template.
I am using django-crispy-forms version 1.1.2-0

Thank You

**Comment by CoutinhoElias** [comment]
@pcarpio ,

Where is your code?

**Comment by asm154** [comment]
Had been struggling with the same issue after adopting crispy forms and found an insanely easy fix:

<form method="post" action="" class="">
           {% crispy form %}
           
           {{ formset.management_form|crispy }}
           {% for form in formset %}
                <div class="form-inline">
                         {% crispy form %}
                </div>
</form>

That's it.  I set the helper attributes and layout at the form level.  Did get rid of self.helper.form_class in the attributes.  Did not set any individual field attributes to inline.  Setting the div class around the form did the trick.

**Comment by dsl-hunted** [comment]
Here’s the solution—take a look https://pythondev.space/questions/constructing-django-forms-for-displaying-form-fields-from-multiple-models-arranged-based-on-a-foreign-key
