### ISSUE TITLE
active tab

### ISSUE THREAD

**Issue by achillis1** [django-crispy-forms/django-crispy-forms#651]
* Package version: 1.6.1
* Django version: 1.10.2
* Python version: 3.4

### Description:

I'm using the bootstrap TabHolder layout in my form. The problem is it always opens the first tab as default. I tried the following code but it doesn't work. So I need to know how to set the 2nd tab as default when the page is open.

`TabHolder(
    Tab('tab1',
        Field('f1'),
    ),
    Tab('tab2',
        Field('f2'),
        css_class="active",
    ),
),`

**Comment by carltongibson** [comment]
This isn't really something we've got bandwidth to dig into I'm afraid. If you can look into it and identify a specific behaviour we could adjust then we could do something but as it stands it's not really an Issue we can address.
