### ISSUE TITLE
Support for bootstrap4-alpha5 left column labels for checkboxes.

### ISSUE THREAD

**Issue by darklow** [django-crispy-forms/django-crispy-forms#661]
Bootstrap4 now supports labels for checkbox (#658), which I find very useful thing. For example you can have label "Agreement" and near checkbox write add another label which is more explaining. In such way form design/layout isn't getting broken with gaps.

![image](https://cloud.githubusercontent.com/assets/445304/20827879/3836f0a0-b87d-11e6-83a3-5965d4738d6a.png)

In terms of consistency I think current label should go into left label column, then all fields would have consistency and no exceptions and label near checkbox input should be optional. By doing this we could also get rid of bunch of exceptions in field templates and managing offset for central column as well.

The questions are:
1. Do you agree, that main label go into left column?
2. If yes, then which variable we should use for label near checkbox?
3. Maybe other suggestions?

First idea that came to my mind is - we could use `help_text` as label near checkbox field. Although this would make an exception and help text for checkboxes would have different look. 
On the other hand do someone really need label near input AND help text right below?

**Comment by zoidbergwill** [comment]
That sounds great to me. Definitely think that text on the right is different from a label.

**Comment by carltongibson** [comment]
See #732: I've asked for help finalising Bootstrap 4 support, and we'll do a new release in the autumn before Django 2.0, or sooner if we get lots of input.

**Comment by zoidbergwill** [comment]
I think using `help_text` for now would be great.

**Comment by zoidbergwill** [comment]
I'd love to get this into the next release.

**Comment by carltongibson** [comment]
I'm going to close this off. If someone wants to put in a PR that's great, but short of that it's not a priority
