### ISSUE TITLE
Override form_class for specific field

### ISSUE THREAD

**Issue by bluesurfer** [django-crispy-forms/django-crispy-forms#663]
From the docs:

> The way you do horizontal forms in Bootstrap version 3 is setting some col-lg-X classes in labels and divs wrapping fields. This would mean a lot of hassle updating your layout objects for settings these classes, too much verbosity. Instead some FormHelper attributes have been added to help you easily achieve this. You will need to set only three attributes:
```helper.form_class = 'form-horizontal'
helper.label_class = 'col-lg-2'
helper.field_class = 'col-lg-8'
helper.layout = Layout(
    'email',
    'password',
    'remember_me',
    StrictButton('Sign in', css_class='btn-default'),
)
```

What if I want to use a different grid layout for a specific field? Let's say that I have a standard address form and want to wrap more than one one field with a different grid?

Something like this:
![image](https://cloud.githubusercontent.com/assets/4722772/20920637/03facdc6-bba1-11e6-8eba-12ef258e43bc.png)

Taken from here http://bootsnipp.com/snippets/featured/address-details-modal-form

**Comment by tomedelliott** [comment]
You should be able to do something like:
```python
helper.label_class = 'col-lg-2'
helper.field_class = 'col-lg-8'
helper.layout = Layout(
    'line1',
    'line2',
    'city',
    Field('state', css_class="col-lg-2"),
    Field('postcode', css_class="col-lg-2"),
    country,
    StrictButton('Sign in', css_class='btn-default'),
)
```

**Comment by bluesurfer** [comment]
That would just change the field's CSS class and it does not affect the row (fields are not inline)

**Comment by doulix** [comment]
I think I found an acceptable solution:

```
self.helper.layout = Layout(
    Div(
        Div('inlineField1',css_class='col-md-6',),
        Div('inlineField2',css_class='col-md-6',),
        css_class='row',
    ),
    'other_fields',
    ...,

    FormActions(
        Submit('submit', 'Submit'),
    ),
)```
