### ISSUE TITLE
Properly rendering fields with MultiWidget descendant

### ISSUE THREAD

**Issue by lorinkoz** [django-crispy-forms/django-crispy-forms#668]
Is there any workaround to make crispy-forms render properly the inner widgets of a MultiWidget descendant?

**Comment by carltongibson** [comment]
@lorinkoz Can you add more detail please? What are you expecting? What are you getting? (Screenshots &/or HTML)

General Rule of Thumb: Override the template. (Hard to be more specific as stands.)

**Comment by lorinkoz** [comment]
This is in some `forms.py`

    class SomeForm(forms.ModelForm):
       class Meta:
          model = SomeModel
          widgets = {
             'somefield': MyCustomMultiWidget
          }

`MyCustomMultiWidget` contains inner `CheckboxSelectMultiple` and `RadioSelect` widgets.
Then, in `some_template.html` using Bootstrap 3 template pack:

    {{ form.somefield|as_crispy_field }}

It renders nonsense.

I can't iterate over inner widgets because so far I believe `as_crispy_field` takes a field as parameter and not just a widget. So I think I'm missing something here. Could you please shed some light?

**Comment by carltongibson** [comment]
I'm going to close this as Out of Scope for the moment. Happy to consider documented, tested pull requests. 


If you can put together expected results vs actual, and ideas for changes you'd like to see made, we may have capacity to reconsider in the future. 

The answer for now may just be, where you're doing this: 

>             {{ form.somefield|as_crispy_field }}

render the field yourself. 

(Can you not achieve what you're looking for with a custom Layout object and template?)
