### ISSUE TITLE
Inlining other controls like radio buttons and checkboxes

### ISSUE THREAD

**Issue by mihirsevak** [django-crispy-forms/django-crispy-forms#673]
* Package version: latest
* Django version: 1.8
* Python version: 2.7.x

### Description:
I am using django crispy forms in my application and I am very happy with it. I am using it on bootstrap 3. Here is my question. Is there any way I can inline two textboxes the way I can inline radiobuttons and checkboxes using inline_radios() function?? 

By default all textboxes are rendered in vertical order but I want a few selected textboxes in horizontal order. I am wondering if there is some function or layout option/trick to accomplish this.

Please advise.
Thanks.

### Preferably also include:

-[ ] Example Django Crispy Forms code
-[ ] Screenshots
-[ ] Actual HTML generated
-[ ] Exepcted HTML

**Comment by carltongibson** [comment]
Look into Layouts [Docs](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html). Maybe a fieldset with a custom template...
