### ISSUE TITLE
Include Submit button automatically?

### ISSUE THREAD

**Issue by lggwettmann** [django-crispy-forms/django-crispy-forms#677]
Hey guys,

I made a template for an existing package with this Django code:
```
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Sign Up" class="btn btn-primary">
</form>
```

I'd like to use bootstrap templating of Crispy forms, but when I do this
```
<form method="POST">
    {% crispy form %}
    <input type="submit" value="Sign Up" class="btn btn-primary">
</form>
```
Crispy forms renders the submit button outside the form tags and the form is useless:
```
<form method="POST">
    <input type="hidden" name="csrfmiddlewaretoken" value="...">...
    <input ... name="first_name" type="text"> ...
    <input ... name="last_name" type="text">...
    <input ... name="email" type="email">...
    <input ... name="password1" type="password">
</form>
<input type="submit" value="Sign Up" class="btn btn-primary">
```

Do I miss a feature of Crispy forms? How do you solve this without writing a custom form for the 3rd party package. Thanks in advance.

**Comment by kevin-brown** [comment]
> How do you solve this without writing a custom form for the 3rd party package.

Instead rewriting the entire form, you can always subclass it and set up the rendering settings within it.

```python
class AuthenticationForm(DjangoAuthenticationForm):

    def __init__(self, *args, **kwargs):
        from crispy_forms import bootstrap, layout

        super().__init__(*args, **kwargs)

        self.helper = FormHelper(self)
```

No, it's not ideal. But yes, it works fairly well.

**Comment by lggwettmann** [comment]
Thanks, yeah I tried that, but it seems very complicated for that specific package. I need to create separate URL's and such and it's just super, super messy. I'm sure it's doable, though. :/

If I'm not the only one longing for an easy solution, perhaps it'd be an idea to add a feature which includes elements in the original form tag also in the rendered form tag automatically?

**Comment by carltongibson** [comment]
The `crispy` tag takes a `FormHelper` as an optional second argument. If you set `form_tag = False` on that helper (I think) you should get what you want. 

Review [`crispy` tag docs](http://django-crispy-forms.readthedocs.io/en/latest/crispy_tag_forms.html#crispy-tag-with-forms) — there are a lot of examples there. 

(I'm guessing you're getting two `form` elements rendered — the one in your template plus the one from `crispy`. Either remove you own ones and add a `Submit` element to the helper or disable the helper's `form_tag`)

**Comment by spnshguy** [comment]
Crispy form actually has an option to add a submit button in the form init.

heres an example:
def __init__(self, *args, **kwargs):
        super(YourForm, self).__init__(*args, **kwargs)
        self.helper.add_input(Submit('submit', 'Submit'))

**Comment by carltongibson** [comment]
I'm going to assume this is a usage issue. (Beyond the suggestions given there's not much to say based on the available info.)

**Comment by lggwettmann** [comment]
Thanks, guys. I created a generic Form with just one FormHelper which disables the form_tag like @carltongibson suggested. The power of the crispy forms tag shouldn't be underestimated ;)
