### ISSUE TITLE
django 1.11 l10n change

### ISSUE THREAD

**Issue by davidszotten** [django-crispy-forms/django-crispy-forms#683]
Came across this when trying to add django 1.11 (alpha) compat:

In https://github.com/django-crispy-forms/django-crispy-forms/issues/214#issuecomment-21688123 crispy-forms decides to follow django and not localize things

however, as of django 1.11, the lack of localization seems to have been "fixed": https://docs.djangoproject.com/en/dev/releases/1.11/#template-widget-incompatibilities-1-11

question is, what should crispy forms do?

**Comment by carltongibson** [comment]
@davidszotten Good question 🙂

> ... when trying to add django 1.11 (alpha) compat...

Did that result in a failing test case? If so can you open a PR showing that failure? That would be a good place to begin discussion.

**Comment by davidszotten** [comment]
there's an explicit check:

https://github.com/django-crispy-forms/django-crispy-forms/blob/dev/crispy_forms/tests/test_layout.py#L368

(the widget html has also changed the order of attrs, so i'm in the process of using something like `assretHtmlEquals` instead of the current string comparisons currently causing failures all over

will try to finish that off and raise pr

**Comment by carltongibson** [comment]
OK. Cool. 

I'm happy for you to open something half-formed if you want input. 

Thanks for the effort!

**Comment by davidszotten** [comment]
sure, though that's unlikely to add much to this particular question (l10n)

**Comment by carltongibson** [comment]
@davidszotten [commented on #684](https://github.com/django-crispy-forms/django-crispy-forms/pull/684#issuecomment-274319093):

> so if branching [on `django.VERSION`], do we also change the behaviour of the templates like https://github.com/django-crispy-forms/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap4/layout/radioselect.html#L11

We need to confirm the behaviour in Django 1.11 — it looks like all values are now localised. If so, replacing the `unlocalize` calls with a custom filter (that does the branching) [until 1.8 is EOL](https://www.djangoproject.com/download/#supported-versions) seems the best approach.

**Comment by carltongibson** [comment]
I'm going to close this. We'll be dropping <1.11 when we adopt Django 2.0, so it'll drop away.
