### ISSUE TITLE
issue with ajax validation

### ISSUE THREAD

**Issue by spnshguy** [django-crispy-forms/django-crispy-forms#689]
* crispy 1.6.0
* django 1.8
* python 3.4

This is more of a question for than an issue. I've read the doc and i followed the procedure for an ajax validation.

```
    form = UserForm(request.POST or None)
    if form.is_valid():
        form.instance.user = request.user
        form.save()
         # do something
    ctx = {}
    ctx.update(csrf(request))
    form_html = render_crispy_form(form, helper=form.helper,context=ctx)
    #return new form
```
In the ajax success, the doc says that we have to replace the old form with the new one. ex: 

    $(example_form).replaceWith(data['form_html']);

this works fine but what happens if instead of putting the form in the template like so: 

    {% crispy form %}

I render the form with each field like so 

    <div class="form-group custom_class">
            {{ form.first_name|as_crispy_field }}
            {{ form.first_name.errors }}
    </div>

if i replace the old form with the new one, I would lose any custom css that I set on my form. Is there a way to replace each field one by one instead of the whole form?

Thanks!

**Comment by carltongibson** [comment]
The `$(example_form).replaceWith(data['form_html']);` is Javascript executed in the browser with the returned HTML from your Django view. It does not change if you change the way you create that HTML. i.e. You can use either approach as you see fit. 

Usage questions are better suited to StackOverflow.
