### ISSUE TITLE
Crispy formset helper not passed to template

### ISSUE THREAD

**Issue by morinx** [django-crispy-forms/django-crispy-forms#696]
* Package version: 1.6.1
* Django version: 1.10.5 

### Description:

I'm trying to add crispy to a formset and a form in the same template, but cannot pass the helper to formset in the template.

I have included my code in stackoverflow but got no answers yet
http://stackoverflow.com/questions/42615357/cannot-pass-helper-to-django-crispy-formset-in-template

Any help is appreciated

**Comment by moreplavec** [comment]
I have same problem. Tried few hours and found even basic example is not working. I'm using django 1.11. Looks like this repository is not maintained anymore?

**Comment by durdenk** [comment]
Please provide your model form view and html code. I will try to reproduce it.

**Comment by carltongibson** [comment]
He repo is maintained. In fact we're at the lowest number of open issues we've been at for years. 

Happy to take input on this.

**Comment by morinx** [comment]
I'm closing this issue since it's a usage problem, and will provide the answer in the stackoverflow question later.
