### ISSUE TITLE
Is there any way to integrate django-crispy-forms in django admin

### ISSUE THREAD

**Issue by oscarmlage** [django-crispy-forms/django-crispy-forms#697]
* Package version: 1.6.1
* Django version: 1.10
* Python version: 2.7.13

### Description:

I would like to customize the 'admin/change_form.html', instead of use the basic django.contrib.admin view to draw the fields (they only can be grouped by fieldsets, not much more), would be posible to use crispy for that? I mean to define a form layout with tabs, fieldsets, fields per column etc... and draw it inside the change_form.html template in the admin?.

Sorry if it's not the right place to ask this question.

**Comment by carltongibson** [comment]
Hi @oscarmlage, 

In essence, Yes. 

The [Admin Docs](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/) are your friend. 

In particular you probably what to look at the [Custom template options](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#custom-template-options) section and the [ModelAdmin.form](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#django.contrib.admin.ModelAdmin.form) attribute.

**Comment by aventurella** [comment]
Just to add to this.. Here's the actual implementation you can use to render your crispy form:

**admin.py**
```python
from django.contrib import admin
from . import models
from .forms import MyCrispyForm

@admin.register(models.MyModel)
class MyModelAdmin(admin.ModelAdmin):
    form = MyCrispyForm
    add_form_template = "admin/my_form.html"
```

**forms.py**
```python
class MyCrispyForm(forms.ModelForm):


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'id-my-form'
        self.helper.form_class = 'my-form'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = MyModel
        fields = []
```

**admin/my_form.html**
```django
{% extends "admin/change_form.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% crispy adminform.form adminform.form.helper %}
{% endblock %}
```

**Comment by CSP197** [comment]
@aventurella - Is there any way to integrate django-crispy-forms into admin forms without using templates?
