### ISSUE TITLE
Add HTML to all default fields

### ISSUE THREAD

**Issue by alexisdeza** [django-crispy-forms/django-crispy-forms#700]
* Package version:1.2.1
* Django version:1.11
* Python version:3.5

### Description:

I want to add a range slider in each default field, but I'm with troubles to make the HTML using the filter and warp, I make a Form with form-horizontal, label with col-md-2, field class with col-md-2 numeric and want put another col-md-8 to the slider.
So
The package create a
```
<div class="form-group">
    <label class="col-xs-2"></label>
    <div class="control></div>
</div>
```

and I want something like
```
<div class="form-group">
    <label class="col-md-2"></label>
    <div class="col-md-8 slider"></div>
    <div class="control"></div>
</div>
```

**Comment by carltongibson** [comment]
See the docs [Overriding Layout Object Templates](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-layout-objects-templates)
