### ISSUE TITLE
Django 1.11 slow ChoiceField rendering

### ISSUE THREAD

**Issue by mdalpi** [django-crispy-forms/django-crispy-forms#703]
* Package version: 1.6.1
* Django version: 1.11
* Python version: 3.6.1

### Description:

I just upgrade to Django 1.11 and I noticed that in a specific form that we render timezones from `pytz.common_timezones` (currently 439 items) I'm getting error 503. After some tests, it seems that rendering `ChoiceFields` is extremely slow. If i trim the list down to a few items (<100) the form is displayed in a reasonable time. So I replaced the code for something like `forms.ChoiceField(choices=[('test', 'test')] * 100)` and the response time increases almost exponentially by the number os itens in the list.

Downgrade to 1.10.7 and everything is fast as always.

**Comment by carltongibson** [comment]
@mdalpi Thanks for the report. 

Since you have a test case, would it be possible for you to use `git bisect` to work out the change that's leading to this? That would be amazingly helpful.

**Comment by xbello** [comment]
@mdalpi Do you have the Django Debug Toolbar enabled while testing this? I had the same problem, and finally found that disabling DDT _solved_ the problem. See

https://github.com/jazzband/django-debug-toolbar/issues/910

**Comment by mdalpi** [comment]
@xbello You're right, it's DDT fault, thank you 😄

**Comment by faost** [comment]
@mdalpi or you can just disable ` 'debug_toolbar.panels.templates.TemplatesPanel'` from [DEBUG_TOOLBAR_PANELS setting](http://django-debug-toolbar.readthedocs.io/en/stable/configuration.html#debug-toolbar-panels)

**Comment by EugeneDae** [comment]
Wow, I was about to downgrade to 1.10 because of this. Indeed DDT is the culprit. Thanks for bringing this up @mdalpi and thanks @xbello for the solution!
