### ISSUE TITLE
bootstrap3/multifield.html missing from master (it is in dev)

### ISSUE THREAD

**Issue by jheasly** [django-crispy-forms/django-crispy-forms#713]
* Package version: 1.6.1
* Django version: 1.10.5
* Python version: 2.7.12

### Description:

At the bottom of http://django-crispy-forms.readthedocs.io/en/latest/layouts.html#fundamentals, there's a `MultiField` example and when you try to implement it, you get a Traceback complaining that there's no bootstrap3/multifield.html template:

```bash
... snip ... 
  File "/Users/jheasly/.virtualenvs/django110/lib/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: bootstrap3/multifield.html
```
 ... and in the `master` branch, that template is indeed missing. That template seems to only exist in the `dev` branch.

### Preferably also include:

-[ ] Example Django Crispy Forms code
-[ ] Screenshots
-[ ] Actual HTML generated
-[ ] Expected HTML

**Comment by carltongibson** [comment]
Multifield is [Uniform only](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html#uni-form-layout-objects)
