### ISSUE TITLE
Q: Is crispy-forms getting deprecated? (A: No)

### ISSUE THREAD

**Issue by bluesurfer** [django-crispy-forms/django-crispy-forms#723]
I am happily using `crispy-forms`: I have created my own template pack to render Bootstrap 4 custom forms and built some custom form layout. Everything is DRY and simple.

But now Django 1.11 has landed and with it comes the ability to customize widget templates. I am a little concerned about the future of `crispy-forms` in relation with these new features (I am questioning myself: is `crispy-forms` still worth it?). Furthermore, almost a year has passed since the last version update.

I am not criticising the work of the developers (everyone has other stuff to do) but since I am heavily using it I am asking if there are any plans for the future in relation with Django 1.11.

**Comment by carltongibson** [comment]
@bluesurfer Good question. 

At this stage there's no plan to wind up the project. A new release for Django 2.0 will come shortly. There's been lots of little additions but no great changes requiring a new release in the meantime. (If people want they can install from GitHub quite easily.) 

If template sets for Django get released then maybe Crispy Forms will no longer be needed. (But `Layouts` still offer a lot even then.)

With regard to Bootstrap 4 in particular, it's a bit difficult following a moving target — I don't use it myself — so all contributions to make the templates there great are appreciated. We started well but enthusiasm from the community dropped as each pre-release version brought breaking changes: the consensus seemed to be to wait until BS4 was finalised before doing too much more work. I'm very happy to have input on the BS4 templates from anyone who can step up there.

**Comment by carltongibson** [comment]
Also: 

* The project is mature and stable. We really don't need new releases very often. That's a good thing.
* The issue tracker is in a pretty good state: prior to Django 1.8 we had ≈150 open issues and ≈50 open pull requests. (The project was also not 1.8 compatible.) Currently we're at 32 issues (including this one) and 8 PRs. A good chunk of those are to do with BS4. Nothing in there is critical. 

All in all the project is in pretty good shape. Who knows how Django's template bases rendering evolves but Crispy Forms is still good.

**Comment by durdenk** [comment]
I never needed to modify crispy form's templates, the thing makes crispy forms best is the nested object layouts. I dont understand why django's template system would make this project deprecated.

I want to thank to conributors here, I'm not accustomed python and git enough to contribute right now, but I hope to contribute to project in the future.

**Comment by carltongibson** [comment]
@zmrenwu I suspect that will never happen. The general move is for Django to do less, rather than more. (But if you're keen putting a proposal to the Django Dev Mailing List may be worth a try.)

The _possible_ change is for Crispy Forms to leverage the new template rendering. But there's no great rush on that. Crispy Forms is mature and stable. It's not going anywhere. Maybe we arrive at a Version 2 at some point. Maybe... 🙂

**Comment by carltongibson** [comment]
See #732: I've asked for help finalising Bootstrap 4 support, and we'll do a new release in the autumn before Django 2.0, or sooner if we get lots of input.
