### ISSUE TITLE
Bootstrap 4: Prettier File Inputs

### ISSUE THREAD

**Issue by zoidbergwill** [django-crispy-forms/django-crispy-forms#734]
File inputs don't look too great

![image](https://user-images.githubusercontent.com/2572493/29567161-a03a5676-874c-11e7-9245-f859f28995e6.png)

They should look more like:

![image](https://user-images.githubusercontent.com/2572493/29567193-b3ad9d9e-874c-11e7-9368-477ec6672a70.png)

Ours:

```
<input type="file" name="photo" class="clearablefileinput" id="id_photo">
```

What it should be closer to:

```
<label class="custom-file">
  <input type="file" name="photo" id="id_photo" class="custom-file-input">
  <span class="custom-file-control"></span>
</label>
```

**Comment by csoni111** [comment]
I am new to this project and would like to contribute. As far as I have understood, `django-crispy-forms` does not handle the rendering of the field widget, `django` handles that. Now by default django renders the file widget as given above. So how do go on changing that?

**Comment by zoidbergwill** [comment]
So we provide the template that Django uses to render the field widget in [`field.html`](https://sourcegraph.com/github.com/django-crispy-forms/django-crispy-forms@86b2991e2d6fba84e106ea792076aedee97343a4/-/blob/crispy_forms/templates/bootstrap/field.html) for each template pack, and then do special things for things like [radio box selects](https://github.com/django-crispy-forms/django-crispy-forms/blob/86b2991e2d6fba84e106ea792076aedee97343a4/crispy_forms/templates/bootstrap/layout/radioselect.html).

We could do the same for file inputs using our [`is_file` template tag](https://github.com/django-crispy-forms/django-crispy-forms/blob/a4afab25159f229ebc667834609d5ab52d31a491/crispy_forms/templatetags/crispy_forms_field.py#L41). Checking if it's a file, and then using that custom HTML above for Bootstrap 4 instead of the `crispy_field` template tag, potentially in a `layout/fileinput.html` template and not the main `field.html` template.

Other wise we could make the `crispy_field` tag support it, which calls [`CrispyFieldNode.render`](https://github.com/django-crispy-forms/django-crispy-forms/blob/a4afab25159f229ebc667834609d5ab52d31a491/crispy_forms/templatetags/crispy_forms_field.py#L78), and already does some custom template pack stuff like [this](https://github.com/django-crispy-forms/django-crispy-forms/blob/a4afab25159f229ebc667834609d5ab52d31a491/crispy_forms/templatetags/crispy_forms_field.py#L132)

Do you feel like that is enough info to have a try at solving it? We could jump on gitter or something if you need to chat through anything.

**Comment by carltongibson** [comment]
I'm going to close this off as is. If a PR comes in helping here that's great.

**Comment by pvandegeer** [comment]
I managed to get a bootstrap 4 custom file input by subclassing the field method and providing a custom template:
`
class FileField(Field):
    template = "%s/layout/file_field.html"
`
Put the following template in your apps template folder in bootstrap4/layout/file_field.html (r change the path):
`
{% load crispy_forms_field %}
{% if field.is_hidden %}
    {{ field }}
{% else %}
        <div id="div_{{ field.auto_id }}" class="form-group{% if wrapper_class %} {{ wrapper_class }}{% endif %}">
            <div class="input-group">
                <div class="custom-file">
                  {% crispy_field field 'class' 'custom-file-input' %}
                  <label for="{{ field.id_for_label }}" class="custom-file-label">
                      {{ field.label|safe }}
                  </label>
                </div>
            </div>
        </div>
{% endif %}
`

Maybe this will help somebody create a fix.

**Comment by hmarlo** [comment]
Hey! I think that here is proper place to put this, even if its closed.

The template at `crispy_forms/templates/bootstrap4/layouts/field_file.html`, has this content on the branch `master`:

```html
{% load crispy_forms_field %}

<div class="custom-file {{ field_class }}">
    {% crispy_field field 'class' 'custom-file-input' %}
    <label class="custom-file-label" for="{{ field.id_for_label }}">Choose file</label>
</div>
```

Which is great, but needs `{% include 'bootstrap4/layout/help_text_and_errors.html' %}` at the end to show the errors. So it will become:

```
{% load crispy_forms_field %}

<div class="custom-file {{ field_class }}">
    {% crispy_field field 'class' 'custom-file-input' %}
    <label class="custom-file-label" for="{{ field.id_for_label }}">Choose file</label>
    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
</div>
```

I checked the `dev` branch and this file doesn't exist, even the branch is more recent than `master`. On the network insight graph it shows that is 28 behind `master` and 5 ahead. But belongs to another issue.

Should I open a new issue (and request) to add the fix? From which branch should I do it?

Thanks!

**Comment by ichef89** [comment]
Hey! Thanks for the code @hectormartinezdev I just have a style issue with the output
![Schermata 2020-05-01 alle 00 13 57](https://user-images.githubusercontent.com/64616760/80764922-0a971f80-8b42-11ea-9664-7c0fe2b375d6.png)

`<div class="custom-file ">
                  <label class="custom-file-label" for="id_image">Choose file</label>
                  Currently: <a href="/media/profile_pics/default.JPG">profile_pics/default.JPG</a><br>
Change:
<input type="file" name="image" accept="image/*" class="clearablefileinput form-control-file custom-file-input" id="id_image">
                </div>`

I don't want that it shows the "Currently" and "Change" but I don't know what to do with the source code...

`{% for field in p_form  %}
                <div class="custom-file {{ field_class }}">
                  <label class="custom-file-label" for="{{ field.id_for_label }}">Choose file</label>
                  {% crispy_field field 'class' 'custom-file-input' %}
                </div>
              {% endfor 
 %}`

Thanks for any help that anyone could provide..maybe it's obvious but I'm new to programming

**Comment by filippodaminato** [comment]
HI! I had the same problem today.
I solved it as follows:

**image_thumbnail.html**
```

{% load crispy_forms_field %}
<!-- PREVIEW IMAGE -->
<div class="fileupload fileupload-new" data-provides="fileupload">
    <div class="row">
        <div class="col-md-12">
            <img id="output" class="img-thumbnail img-fluid w-100" {% if field.value %} src="{{ field.value.url }}"  {% endif %} />
            {% if field.value %}
                <input type="checkbox" name="{{ field.name }}-clear" id="{{ field.name }}-clear_id">
                <label for="{{field.name}}-clear_id">Clear</label><br>
            {% endif %}
        </div>
    </div>
</div>
<!-- INPUT -->
<div class="input-group mb-3">
    <div class="custom-file">
      <input type="file" name="{{field.name}}" accept="image/*" class="custom-file-input" id="inputGroupFile01" onchange="loadFile(event)" aria-describedby="inputGroupFileAddon01">
      <label class="custom-file-label" id="inputFileLabel">Presentation Image</label>
    </div>
</div>
{% include 'bootstrap4/layout/help_text_and_errors.html' %}

<script>
    // preview image
    var loadFile = function(event) {
      var output = document.getElementById('output');
      output.src = URL.createObjectURL(event.target.files[0]);
      output.onload = function() {
        URL.revokeObjectURL(output.src)
      }   
      document.getElementById("inputFileLabel").innerHTML = "{{field.label_tag}" + event.target.files[0].name;
    };
</script>

```

**forms.py**

```

from crispy_forms.layout import Field

class CustomImageField(Field):
    template = 'layout/fields/image_thumbnail.html'

```

**forms.py**

```

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

class CreateProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ( ...., 'img_presentation', .... )

    def __init__(self, *args, **kwargs):
        super(CreateProductForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        
        self.helper.layout = Layout(
           ....
            Row(
                Column(CustomImageField('img_presentation'), css_class='form-group col-md-12 '),
                css_class='form-row'
            ),
           ....
           Submit('submit', 'Crea',css_class='btn btn-block btn-success')
        )

```

**Resutl 🎉**


![Screen Recording 2020-05-05 at 12 12 42](https://user-images.githubusercontent.com/29800038/81056533-00bb4680-8ecb-11ea-983b-405616531824.gif)

I hope that can be helpful to those in a similar situation

**Comment by smithdc1** [comment]
Both I think #1004 will fix this. Appreciate your views.

(I think it's complete apart from some finishing stone tests)

**Comment by clhefton** [comment]
I solved it by making a "browse button" template and using the `template=` parameter when creating the Field in the Form. It's very similar to the BaseInput template, but the `<input>` is within the `<label>` as it should be for a custom Browse button. 

https://stackoverflow.com/questions/32860363/how-to-make-bootstrap-file-browse-button-using-django-crispy-forms/65914798#65914798.
