### ISSUE TITLE
Bootstrap linting

### ISSUE THREAD

**Issue by zoidbergwill** [django-crispy-forms/django-crispy-forms#738]
It'd be awesome to run [bootlint]( https://github.com/twbs/bootlint) in our tests, to make sure we generate HTML according to bootstrap best practices.

It seems to only support Bootstrap 3 at the moment.

[Bootlint list of errors and warnings](https://github.com/twbs/bootlint/wiki)

Though maybe it'd be easier to script running this on the crispy-test-project as a start.

**Comment by carltongibson** [comment]
This sounds like it could be a good help. (The trouble with HTML is it's hard to verify...)

**Comment by carltongibson** [comment]
I'm going to close this off as is. It's not really actionable for us. If a PR comes in that's great.
