### ISSUE TITLE
Any plans for a new version?

### ISSUE THREAD

**Issue by millerdev** [django-crispy-forms/django-crispy-forms#742]
Are there any plans to release a new version of django-crispy-forms (maybe 1.6.2)? It would be nice to not have deprecation warnings on recent versions of Django. I only took a quick glance, and it looks like quite a bit has happened on the [dev](https://github.com/django-crispy-forms/django-crispy-forms/tree/dev) branch, but no new releases since almost a year ago. Is the dev branch considered stable?

**Comment by carltongibson** [comment]
@millerdev 

1. Yep. They'll be a new version before Django 2.0. (i.e. by December.) 
2. Yep. Crispy Forms is **Very Stable** — apart from the incoming Bootstrap 4 support — it's mature and (despite some action on `dev` there's not much really changed. 

On 2: we can merge any actual big fixes pretty quick — although, see 2: Crispy Forms is **Very Stable** at this point. (It's been through the mixer 🙂)

Feel free to install off of `dev` until the new release. Any input — especially on the incoming Bootstrap 4 support — **very welcome**!

**Comment by millerdev** [comment]
Good to hear that `dev` is very stable, as I believe the deprecation warnings have been addressed there. I'm asking because I'm a contributor to https://github.com/dimagi/commcare-hq, and I doubt we'd change our dependency to `dev` there since we prefer to depend on fixed versions rather than a moving HEAD. Looking forward to the new version when it's released. Thanks!

**Comment by carltongibson** [comment]
You can always pick an individual commit...

**Comment by carltongibson** [comment]
Version 1.7.0 is now available on PyPI
