### ISSUE TITLE
Bootstrap 4 custom checkboxes

### ISSUE THREAD

**Issue by fedelaport** [django-crispy-forms/django-crispy-forms#743]
* Package version: 1.6.2
* Django version: 1.11
* Python version: 3.6.2
* Template pack: bootstrap4

### Description:

I am trying to use the [bootstrap 4 custom checkboxes](https://getbootstrap.com/docs/4.0/components/forms/#custom-forms). I can't find a clear way to do with the crispy templates. What I am doing now is using my custom template `custom_bootstrap_checkbox.html`:
```
<label class="custom-control custom-checkbox mt-1">
  <input name="{{ field.name|safe }}" id="{{ field.auto_id|safe }}" type="checkbox" class="custom-control-input">
  <span class="custom-control-indicator"></span>
  <span class="custom-control-description text-muted">{{ field.label|safe }}</span>
</label>
```
And then, in the helper Layout, adding the field as:

`Field('field_name', template="pieces/custom_bootstrap_checkbox.html")`

Those custom checkboxes are already implemented?
Do you think this custom checkbox must be a default if using bootstrap4 ??
The html seems to be hard to fit into `template/bootstrap4/field.html`

**Comment by carltongibson** [comment]
This seems like a good user land solution. 

I’m not sure how we’d add this exactly. It would need some thinking about. Yes, field.html is a bit complex. A PR might want to restructure things slightly. ...

Any thoughts @zoidbergwill?

**Comment by carltongibson** [comment]
I don’t really see this as an Issue, since the user land solution is easy enough. Happy to see it closed if we’re not going to do anything about it.

**Comment by fedelaport** [comment]
Yes, you are right. It's easy enough, but there are several custom elements with the same html structure (file browser, select menu, radios and checkboxes). I think it is good idea to add the templates in a bootstrap4/customs/ folder or something, so users can parse the templates when building the layout.

**Comment by carltongibson** [comment]
Happy to see PRs improving support! We can always take input, where we might not have capacity to do something without it.

**Comment by zoidbergwill** [comment]
Yeah, I had to fiddle a bunch lately to get a pretty file browser too.

And +1 to tidying up `field.html`, it's really scary and complicated.

Maybe we should have a bigger issue to better support some of those elements that aren't supported DCF elements at the moment?
