### ISSUE TITLE
Release 1.6.1 does not include bootstrap3/multifield.html template

### ISSUE THREAD

**Issue by gamesbook** [django-crispy-forms/django-crispy-forms#744]
* Package version: 1.6.1
* Django version: 1.10
* Python version: 3.5
* Template pack: (Optional)

### Description:

I was trying to use MultiField within a Bootstrap 3 layout but got the TemplateDoesNotExist error:

```
Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.filesystem.Loader: /home/derek/dev/gitlab/myproject/code/myproject/templates/bootstrap3/multifield.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/derek/.virtualenvs/myproject/lib/python3.5/site-packages/django/contrib/auth/templates/bootstrap3/multifield.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /home/derek/.virtualenvs/myproject/lib/python3.5/site-packages/crispy_forms/templates/bootstrap3/multifield.html (Source does not exist)
```
which is correct; the template file is not there.

However, this was patched in  issue #428 and the template was available as from May 2016 (see: https://github.com/django-crispy-forms/django-crispy-forms/blob/dev/crispy_forms/templates/bootstrap3/multifield.html ).  The 1.6.1 version released on October 2016 does not, however, include this file - see the tar.gz file on pip (https://pypi.python.org/pypi/django-crispy-forms/1.6.1).

Is it possible to release 1.6.2 and add this file in - or was there a reason it was omitted?

**Comment by carltongibson** [comment]
Multi field is documented as being UniForm only. It was never added. See discussion on #428
