### ISSUE TITLE
Submit button philosophy

### ISSUE THREAD

**Issue by tsa-heroku** [django-crispy-forms/django-crispy-forms#745]
Sorry if this is a noob question. If I follow the docs correctly, they suggest I make my forms crispy by doing this in all of my form classes:

    def __init__(self, *args, **kwargs):
        super(ExampleForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

So, I removed a few lines of template boilerplate, and now I'm sticking this form boilerplate in all of my Python form classes. It seems I haven't gotten DRY-er and I'm also putting button text in my form class instead of in the template where it probably belongs.

Am I misunderstanding the methodology here? Should the crispy tag take some submit button parameters?

**Comment by carltongibson** [comment]
If you’re worried about repeating yourself, make a base form class.  Otherwise you’re we come to pass a helper to the crispy tag
