### ISSUE TITLE
<label> should not be used for multiple checkbox groups

### ISSUE THREAD

**Issue by pjmcdermott** [django-crispy-forms/django-crispy-forms#750]
* Package version: 1.6.1
* Django version: 1.11
* Python version: 3.5.2
* Template pack: bootstrap3

### Description:

Validation of my form HTML5 at [validator.nu](https://html5.validator.nu/) detected the following issue:

> VALIDATION TROUBLE
> 222.58-222.139: error: The “for” attribute of the “label” element must refer to a non-hidden form control.

This is in a Bootstrap 3 multiple inline checkbox created using `InlineCheckboxes()`.
```python
self.helper.layout = Layout(
            InlineCheckboxes('target_marketplaces'),
...
)
```

Looking at the HTML output from crispy (some code removed)

```HTML
<div id="div_id_target_marketplaces" class="form-group">
<label for="id_target_marketplaces"  class="control-label col-lg-2 requiredField">
Target marketplaces<span class="asteriskField">*</span>
</label>
<div class="controls col-lg-6">
<label class="checkbox-inline">
<input type="checkbox" name="target_marketplaces" id="id_target_marketplaces_1" value="0" >eBay United States</label>
<label class="checkbox-inline">
<input type="checkbox" name="target_marketplaces" id="id_target_marketplaces_2" value="2" >eBay Canada (English)
</label>
...
<p id="hint_id_target_marketplaces" class="help-block">Which eBay Marketplaces do you wish to target?</p>
</div>
</div>
````

I can see that the 'for' target for the first label ("id_target_marketplaces") indeed does not exist.

Comments on Stackoverflow:

- [Single label for two inputs](https://stackoverflow.com/questions/14854062/single-label-for-two-inputs) and
- [Two input fields inside one label](https://stackoverflow.com/questions/9004307/two-input-fields-inside-one-label)

indicate that a label should be associated with one, *and only one* form input, and suggest using a `<fieldset>` to group the checkbox elements and a `<legend>` for the label.

### Preferably also include:

- [x] Example Django Crispy Forms code
- [ ] Screenshots
- [x] Actual HTML generated
- [ ] Expected HTML

**Comment by pjmcdermott** [comment]
The following diff on `crispy_forms/templates/bootstrap3/layout/checkboxselectmultiple_inline.html` replaces the `<div>` with a `<fieldset>`, the `<label>` with a `<legend>`, and removes the "for" attribute.

```diff
4c4
<     <div id="div_{{ field.auto_id }}" class="form-group{% if form_show_errors and field.errors %} has-error{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
---
>     <fieldset id="div_{{ field.auto_id }}" class="form-group{% if form_show_errors and field.errors %} has-error{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
7c7
<             <label for="{{ field.auto_id }}"  class="control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
---
>             <legend  class="control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
9c9
<             </label>
---
>             </legend>
13c13
<     </div>
---
>     </fieldset>
```

This fixes the validation errors, but the styling is now different.

I presume something similar would need to be applied to the `checkboxselectmultiple_inline.html` files in the bootstrap and bootstrap4 directories.

**Comment by carltongibson** [comment]
I guess we could look at a PR making this change. Pending that I'm going to close this. Priority now is Django 2.0 and then Bootstrap 4...
