### ISSUE TITLE
update_attributes with css_class results in adding 'css_class' instead of 'class'

### ISSUE THREAD

**Issue by chapkovski** [django-crispy-forms/django-crispy-forms#754]
* Package version: 1.7.0
* Django version: 1.11
* Python version:3.6.1
* Template pack: (Optional)

### Description:
an attempt to update the class using _update_attributes_ results in adding 'css_class' instead of 'class:

```
          self.helper.layout = Layout(
     
            Field( 'comment', css_class="form-control"),
            ButtonHolder(
                Submit('submit', Create', css_class='btn btn-success')
            )
        )
     
        self.helper['comment'].update_attributes(css_class="hello")
```

and the result is:

```
<div class="controls">
  <textarea name="comment" 
          cols="40" rows="10" 
          class="form-control textarea" 
          css_class="hello" 
          id="id_comment"> </textarea> 
</div>
```

**Comment by zoidbergwill** [comment]
Thanks for filing a bug.

Just to clarify, you're doing

```
        self.helper['comment'].update_attributes(css_class="hello")
```

Should it be the following instead?

```
        self.helper['comment'].update_attributes(class="hello")
```

I'll take a look at reproducing this tomorrow.

**Comment by chapkovski** [comment]
no, we can't use word class, because it is a reserved keyword in python (https://docs.python.org/3/reference/lexical_analysis.html)

**Comment by zoidbergwill** [comment]
What template pack are you using? Or does this affect all template packs?

**Comment by zoidbergwill** [comment]
I can reproduce it with bootstrap 4.

We use `css_class` as an example in the docs but test it with other attributes being updated.

**Comment by zoidbergwill** [comment]
This PR should fix them: https://github.com/django-crispy-forms/django-crispy-forms/pull/764
