### ISSUE TITLE
AttributeError 'NoneType' object has no attribute 'wrap' when model has a field named template

### ISSUE THREAD

**Issue by bluesurfer** [django-crispy-forms/django-crispy-forms#762]
* Package version: 1.7.0
* Django version: 1.11.7
* Python version: 3.6.1

Given this `ModelForm` with a `Model` `Foo` having a field named `template`:

```
class FooForm(forms.ModelForm):
    class Meta:
        model = Foo
        fields = ['template',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper['template'].wrap(Field, css_class='col-form-label-lg')  # AttributeError
```
This raises a `AttributeError` when trying to access the field `template`. It seems that crispyforms is looking for the template attribute instead of the field one. 

Is this behaviour intended? Or am I doing something wrong?  Thanks.

**Comment by carltongibson** [comment]
Hi @bluesurfer. 

"Intended" probably not. "Expected" yes. 🙂

If you look at the `__getitem__` implementation: 

https://github.com/django-crispy-forms/django-crispy-forms/blob/e63d8934afe2fcfc677c459550f1136167497ee3/crispy_forms/helper.py#L79-L114

You'll see it first checks for the relevant attribute on the helper. We've got a `template` and it defaults to `None`: 

https://github.com/django-crispy-forms/django-crispy-forms/blob/e63d8934afe2fcfc677c459550f1136167497ee3/crispy_forms/helper.py#L215

That's what you're hitting. 

If you have similarly named fields you'll probably have to reconstruct the `LayoutSlice` (from the later logic in `__getitem__`) yourself. 

One option might be to name your form field differently (using `label` etc for appearances) and then override `clean` to convert back to the underlying field name you need, i.e. `template` here. (You'll have to experiment with that. 🙂)

I'm not sure there's anything we can realistically do about this one I'm afraid.
