### ISSUE TITLE
no crispy tags for Jinja2 template engine

### ISSUE THREAD

**Issue by Darkskope** [django-crispy-forms/django-crispy-forms#773]
* Package version: 1.7.0
* Django version: 2.0.2

### Description: Provision default jinja2 template tag implementation

django-crispy-forms does not come bundled out of the box with Jinja2 template tags support. it will greatly improve workflow efficiency if this implementation was provisioned.

I _**need help**_ writing a jinja extension that allows for the use of the crispy form tags

**Comment by carltongibson** [comment]
Jinja2 is not supported I'm afraid. We could consider a user PR that added Jinja2 support but there are no plans to add it. 

(Is there no Jinja2 helper that'll let you render a DTL fragment? — You could write one of those.)

**Comment by SadPencil** [comment]
@Darkskope Try this trick:

In the python file where your Jinja2 `environment()` function exists, add this line at the beginning,
```python3
from crispy_forms.templatetags.crispy_forms_filters import as_crispy_form
```
and change your `environment()` function by adding a line below.

```python3
def environment(**options):
    env = Environment(**options)
    env.globals.update({
        'static': staticfiles_storage.url,
        'url': reverse,
        'crispy': as_crispy_form, # this is the new line!
    })
    return env
```

And then, modify your template file, replace `{{ form | crispy }}` with `{{ crispy(form) }}`
_____

It works for me, with the following pip packages:
```
Django==3.1.2
django-crispy-forms==1.9.2
Jinja2==2.11.2
```

**Comment by jmoppel** [comment]
For other Django devs usingJinja2 templates, who might stumble across this issue... Crispy Forms works just fine for (at least) basic use with Jinja Templates out of the box. Below are the two use cases I needed for my project that worked without any issues.

### Crispy Filter

This is the solution that @SadPencil mentioned earlier/

Configuration: Add `as_crispy_form` to your filters in your jinja2's `environment`.
```python
from crispy_forms.templatetags.crispy_forms_filters import as_crispy_form

def environment(**options) -> Environment:

   # your jinja2 environment

    env.filters.update(
        {
           # your other jinja2 filters go here
            "crispy": as_crispy_form,
        }
    )

    return env
```

The syntax in your Jinja2 template is identical to Django's Template Language:
```html
<form method="post" class="my-class">
    {{ my_formset|crispy }}
</form>
```


### Crispy Template Tag
You can easily emulate the `{% crispy %}` Template Tag in Jinja by using a template function. `FormHelper`, `Layout`, etc. all worked fine.

Configuration:
```python
    env.globals.update(
        {
            # your other jinja2 template functions go here
            "crispy": render_crispy_form,
        }
    )
```
Rendering a form is very nice in your Jinja2 Template:
```html
<form method="post" class="my-class">
    {{ crispy(my_formset) }}
</form>
```

These are the items I needed for my project, which all worked without issue.
