### ISSUE TITLE
Is bootstrap4 supported ?

### ISSUE THREAD

**Issue by stuaxo** [django-crispy-forms/django-crispy-forms#774]
Hi,
   Bootstrap 4 is out properly now.   Does it work with crispy forms ?    I saw the PR, from a while back - but the documentation on RTD only talks about bootstrap 3.

Cheers
S

**Comment by MikeVelazcoMtz** [comment]
I'm currently using bootstrap 4 and this plugin and I can tell you that works.

Just in your `settings.py` set `CRISPY_TEMPLATE_PACK = 'bootstrap4'`

**Comment by michaelhjulskov** [comment]
#meeto :) it works okay. i had a little bug/issue with a checbox that was placed outside the form, but i fixed it by removint the checkbox from the form. so maybe there is still some small issues/bugs. Sorry i didnt report that in here.

**Comment by stuaxo** [comment]
I missed the bit about template packs - it should probably be updated now that bootstrap 4 has left alpha.
Also, all the places where bootstrap 3 is mentioned here -
http://django-crispy-forms.readthedocs.io/en/latest/

probably need updating to mention 4.

**Comment by carltongibson** [comment]
Version 1.7.1 is available on PyPI now. This finalises the support for BS4. (As ever there may be small issues.) 

Yes, docs need updating. Help there in the form of PRs always welcome.

**Comment by Serafiniert** [comment]
> Version 1.7.1 is available on PyPI now. This finalises the support for BS4.

Then you might want to update the github landing page.

> Django-crispy-forms supports several frontend frameworks, such as Twitter **Bootstrap (versions 2 and 3)**, Uni-form and Foundation.

**Comment by xarala221** [comment]
Hi Friend this is a good tutorial using django crispy forms and Bootstrap4.

https://simpleisbetterthancomplex.com/tutorial/2018/08/13/how-to-use-bootstrap-4-forms-with-django.html
