### ISSUE TITLE
.invalid-feedback hides entire field

### ISSUE THREAD

**Issue by deanpienaar** [django-crispy-forms/django-crispy-forms#779]
* Package version: 1.7.1
* Django version: 2.0.2
* Python version: 3.6.2
* Template pack: Bootstrap 4

### Description:

When a field is rendered with errors, the `.invalid-feedback` class is being applied to the entire form-group.

https://github.com/django-crispy-forms/django-crispy-forms/blob/8e5e182c798095600d926370f0f7c8d53c438737/crispy_forms/templates/bootstrap4/field.html#L12

It doesn't seem like this is the correct place for this class to go. It is already applied to the help text/label which seems correct as per [the Bootstrap docs](https://getbootstrap.com/docs/4.0/components/forms/#custom-styles).

This is currently making the entire field hidden

This:
![](https://puu.sh/zBHcy/58d9931e8d.png)

Should be:
![](https://puu.sh/zBHdH/f6b9a9fc72.png)

- [x] Example Django Crispy Forms code
- [x] Screenshots
- [ ] Actual HTML generated
- [ ] Expected HTML

**Comment by hendrikschneider** [comment]
When do you plan to release this fix with pip? I would like to avoid having the git repository in my requirements.txt file.

**Comment by carltongibson** [comment]
Version 1.7.2 is on PyPI now.
