### ISSUE TITLE
Add option to automatically populate field placeholders

### ISSUE THREAD

**Issue by dspacejs** [django-crispy-forms/django-crispy-forms#786]
Field labels can be disabled with `form_show_labels = False`, but there's no option to automatically populate the placeholders with each label's content.

[There's ways to work around this manually in a DRY-fashion](https://stackoverflow.com/a/23971724/4260047), but I think it'd be best to have this as an option so users don't have to write the functionality themselves. This is especially cumbersome when working with multiple forms that do this.

**Comment by carltongibson** [comment]
Closing as per PR #935
