### ISSUE TITLE
Invalid Filter 'Crispy'

### ISSUE THREAD

**Issue by pythoncreate** [django-crispy-forms/django-crispy-forms#795]
* Package version: 1.7.2
* Django version: 2.0.3
* Python version: 3.6
* Template pack: (Optional) Bootstrap 4

### Description:

I've followed all the instructions--edited the Settings.py file, loaded the crispy tags at the top of my layout form and edited my form to include the crispy filter.

When i visit my form page it's saying 'invalid filter--crispy'....any ideas?

**Comment by zoidbergwill** [comment]
Could you show us your `settings.py` and the related pieces of your `template`?

**Comment by pythoncreate** [comment]
ok, figured this out--i needed to load the tags on the actual form page and not the html layout page...thanks!
