### ISSUE TITLE
Upgrade Twine?

### ISSUE THREAD

**Issue by brainwane** [django-crispy-forms/django-crispy-forms#796]
* Package version: git master
* Django version: n/a
* Python version: n/a

I'm one of the maintainers of [Twine](http://twine.readthedocs.io/). I see your `requirements.txt` file [specifies version 1.5.0](https://github.com/django-crispy-forms/django-crispy-forms/blob/master/requirements.txt#L3). The new version of Twine is 1.10.0. If there's anything we can do to make your upgrade path easier, please mention it here or [file an issue](https://github.com/pypa/twine/issues/new)? Thanks!

**Comment by carltongibson** [comment]
Hiya @brainwane. Thanks. Yes. This is already done locally. (It's what I'm using to publish the package.) I just forgot to update the requirements. 

Fancy opening a PR?

**Comment by brainwane** [comment]
Thanks, @carltongibson - now that I'm reassured that the new version doesn't break anything for you, I've done so.
