### ISSUE TITLE
Error while using Testforms

### ISSUE THREAD

**Issue by ghost** [django-crispy-forms/django-crispy-forms#802]
* Package version: 1.7.2
* Django version: 1.11.11
* Python version: 2.7.14
* Template pack: (Optional)

### Description:
While try to run a test form an error shows up. 

It seems that a max-length attribute is missing at the tests/forms.py in the class CrispyEmptyChoiceTestModel

Adding a max-length attribute in django-crispy-forms/crispy_forms/tests/forms.py at line 133 solves the issue.

**Comment by carltongibson** [comment]
Hi @Siron55. Can you show me the traceback for that error please? (The test suite seems to be running OK...) 

> Adding a max-length attribute in django-crispy-forms/crispy_forms/tests/forms.py at line 133 solves the issue.

Fancy opening a PR?

**Comment by Siron55** [comment]
ERRORS:
crispy_forms.CrispyEmptyChoiceTestModel.fruit: (fields.E120) CharFields must define a 'max_length' attribute.

**Comment by carltongibson** [comment]
You see, I'm running the test suite here and not seeing that. So can you post the whole traceback, or otherwise provide some more info? 

Thanks.

**Comment by smithdc1** [comment]
Closing as current test suite is passing.
Happy to take a look if someone runs into this issue and can provide trace back / example project etc.

**Comment by kuttamuwa** [comment]
I got same error:
![resim](https://user-images.githubusercontent.com/26677935/97586843-c8289f80-1a0b-11eb-8a50-194cf58da451.png)

I thought that error comes from me and I couldn't track the error. However, when I digged in test class in crispy, I saw this:
![resim](https://user-images.githubusercontent.com/26677935/97590137-5ce0cc80-1a0f-11eb-80cf-67a1695515ce.png)

Just change the line to:
fruit = models.CharField(choices=[("apple", "Apple"), ("pear", "Pear")], null=True, blank=True,
                             max_length=100)

Case closed for me.

**Comment by smithdc1** [comment]
This is helpful. I think we need to stop packaging the tests. (Is this the right way if describing this)

Is moving the tests folder the right thing to do here. Most projects I see seem to have the tests folder alongside rather than within the package?

**Comment by kuttamuwa** [comment]
Thanks. Well, tests are useful to pass most of the situations depends on OS, Databases, versions of libraries crispy uses etc. 
For instance, if someone opens a case while installing crispy we know there is something of tests cannot accept, or opposite.. It is good place to start. I think they should be stay. However, it can be really hard to detect if they raise an error. So we just have to be more careful before packaging. Additionally, maybe it will be better idea as packaging tests running them once crispy been installed and that's it. They should not be run whenever user runs manage.py commands
