### ISSUE TITLE
Changing template for widget rendering not working 

### ISSUE THREAD

**Issue by esseti** [django-crispy-forms/django-crispy-forms#806]
* Package version:  1.7.2
* Django version: 2.0.3
* Python version: 3.6

### Description:

I'm trying to overide the templates for a widget. While with plain Django it works, with crispy forms it seems to ignore my settings. The new template is ignored.
I've had open a question on SO as well https://stackoverflow.com/questions/49538708/template-widget-in-django-2-0-crispy-form (before figuring out that it was a *crispy forms issues*)

#### Code
```
class MultiChoiceFilterWidget(forms.widgets.CheckboxSelectMultiple):
    template_name = 'web_admin/partial/checkbox.html'

class MyChoiceForm(ModelForm):
        class Meta:
            model = MyModel
            fields = ('theField',)
            widgets = {
                'theField': MultiChoiceFilterWidget,
            }
```

everything is set up properly

**Comment by zoidbergwill** [comment]
Hi @esseti 

Thanks for your bug report. I'll see if I can reproduce it.

**Comment by zoidbergwill** [comment]
So I've achieved a similar thing previously doing the following:

```
class GroupForm(ModelForm):
    deadline = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        )
    )
```

**Comment by zoidbergwill** [comment]
Would it be possible to make an example project that reproduces this issue? If it's easier, it can be a branch on https://github.com/django-crispy-forms/crispy-test-project

**Comment by carltongibson** [comment]
This looks to me like an incompatibility between Django's new template based widget rendering and Crispy Form's own rendering, which predates that by _some time_. 

* We need to look at levering the Django rendering directly. This would be a biggish overhaul, but worth it for the future. 
* For now I think you need to [specify the template at the layout object level](http://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-layout-objects-templates).

**Comment by esseti** [comment]
I'll try to create the example, but I'm rathere busy this week. 
I'll look into suggestion from @carltongibson asap, for time being, since my form is just 1 widget, i solved the situation by not using crispy for that form.

**Comment by martimarkov** [comment]
I think this is still an issue?

**Comment by smithdc1** [comment]
I would have thought so. I'm not aware of any changes in this area in the last 4 years.

Would be an interesting activity to unpick this and understand what is possible.

**Comment by smithdc1** [comment]
Is your issue with a checkbox / radio?

**Comment by smithdc1** [comment]
As of 2023 with Django 4.1, this seems to work for me. Happy to have a look if someone can reproduce this.

```python
class MyWidget(forms.widgets.TextInput):
    template_name = "bootstrap4/my_template.html"


class MessageForm(forms.Form):
    test_input = forms.CharField(widget=MyWidget)
    helper = FormHelper()
    helper.layout = Layout(
        "test_input",
    )
```

![image](https://user-images.githubusercontent.com/39445562/219468120-62a22cd6-2040-4537-b1aa-a914a6878353.png)
