### ISSUE TITLE
.col-form-label gets added also for vertical forms

### ISSUE THREAD

**Issue by webjunkie** [django-crispy-forms/django-crispy-forms#810]
* Package version: 1.7.2
* Django version: 2.0.4
* Python version: 3.6
* Template pack: Bootstrap 4

### Description:

`.col-form-label` seems to get added all the time to labels, even though according to the Bootstrap docs, it's only for horizontal forms. It's not a huge issue, just an unnecessary class in the markup. Could become a problem when one puts styles on it, that you don't want in vertical forms.

**Comment by marcosmadr** [comment]
Hey folks, I'll be working on this issue

**Comment by smithdc1** [comment]
Fixed by #814
