### ISSUE TITLE
'template' attribute named 'link_template' in Tab Layout object

### ISSUE THREAD

**Issue by maratumba** [django-crispy-forms/django-crispy-forms#812]
* Package version: 1.7.0
* Django version: 1.11.7
* Python version: 3.6.3
* Template pack: bootstrap3

### Description:
I'm not sure this is intentional but made it pretty hard to override the template in for `Tab`. Turns out the template attribute is named `link_template` in the source code:
```
class Tab(Container):
    """
    Tab object. It wraps fields in a div whose default class is "tab-pane" and
    takes a name as first argument. Example::
        Tab('tab_name', 'form_field_1', 'form_field_2', 'form_field_3')
    """
    css_class = 'tab-pane'
    link_template = '%s/layout/tab-link.html'

    def render_link(self, template_pack=TEMPLATE_PACK, **kwargs):
        """
        Render the link for the tab-pane. It must be called after render so css_class is updated
        with active if needed.
        """
        link_template = self.link_template % template_pack
        return render_to_string(link_template, {'link': self})
```

As a result, this doesn't work, even if you copy the original template to app dirs.
```
Tab(
  'D.DDD°',
  'latitude',
  'longitude',
  template='crispy_overrides/tab-link.html', # <- has to be 'link_template' for it to work
),
```

**Comment by zoidbergwill** [comment]
It looks like the template variable is used for the div template not the tab link template. Though overriding the div template should cause strange side effects too.

**Comment by zoidbergwill** [comment]
I'm gonna consider this working as intended, let me know if you think we should change something in the library for this though.
