### ISSUE TITLE
bootstrap 4 Appended Text not working as expected for select fields

### ISSUE THREAD

**Issue by ociule** [django-crispy-forms/django-crispy-forms#819]
* Package version: 1.7.2
* Django version: 1.11.13
* Python version: 3.6.5
* Template pack: bootstrap4

### Description:

When appending a bootstrap.AppendedText to a layout for a select field, I expect to get something like the second example shown here:

https://getbootstrap.com/docs/4.0/components/input-group/#custom-select

This shows bootstrap 4 supports appending text to select inputs.

Instead the html generated by crispy-forms is missing both the div .input-group-append and the enclosing div .input-group.

The bug seems to be in `crispy_forms/templates/bootstrap4/layout/prepended_appended_text.html` which I intend to fix.

###  Example Crispy Forms code to reproduce

```
def __init__(self):
  self.helper = FormHelper()

  self.fields['select'] = forms.ChoiceField(label="Sample Label", help_text="Some help text", choices=[(1, "Choice 1"), (2, "Choice 2")])  # Choice fields are rendered with a select widget

  self.helper.layout = Layout(
    AppendedText('select', 'Some appended text')
  )
```

**Comment by ociule** [comment]
There's a patch in pull request #820

There's a patch to cripsy-test-project that allows testing easily:

https://github.com/django-crispy-forms/crispy-test-project/pull/6

Hope this helps

**Comment by zoidbergwill** [comment]
Hey, @ociule 

Thanks for your contributions!

Sorry, I've recently started a new job and moved countries, so I've been neglecting my responsibilities on this project. Taking a look.
