### ISSUE TITLE
Unable to use {%% include 'filename.html' %%} inside HTML()

### ISSUE THREAD

**Issue by sureshvv** [django-crispy-forms/django-crispy-forms#825]
* Package version: 1.6.1
* Django version: 1.11.12
* Python version: 3.5.0
* Template pack: (Optional)

### Description:

I want to store the HTML in a template file and use the {% include %} statement inside the layout HTML function. 

###The error I get:

    django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 1: '%'. Did you forget to register or load this tag?

**Comment by carltongibson** [comment]
The tag syntax is `{% ... %}` not `{%% ... %%}`. 

Hence the `TemplateSyntaxError` on `%`: it's getting as far as `{%%` and error-ing on the second `%`.
