### ISSUE TITLE
is django 1.10 still supported by crispy-forms?

### ISSUE THREAD

**Issue by davidszotten** [django-crispy-forms/django-crispy-forms#833]
the readme implies it is, though not the tox config

(1.10 of django itself is no longer supported)

if we're dropping 1.10, all supported django versions now use template based widget rendering which might enable some code cleanup

**Comment by carltongibson** [comment]
It'll still work, but No, we're not running the tests. (Would happily merge a PR on the README.) 

Moving to using Django's native template rendering is a definite Yes. I have preliminary thoughts on it, but little time to push it forwards. Basically it would be the basis of a Crispy Forms 2.0. 

(Possible Step 1: have render_field take a field instance and defer to that if given...) 

If you fancy helping on that it would be super! (See point about time above.)

**Comment by davidszotten** [comment]
hi. not sure i'll have time for large refactorings but had a smaller bugfix that's easier with 1.11+

**Comment by davidszotten** [comment]
ah, had missed that we still support 1.8. are we happy to drop that now that it's out of even extended support?

**Comment by carltongibson** [comment]
This is the latest support as I see it: 

https://github.com/django-crispy-forms/django-crispy-forms/blob/f4b2cb552e1466b35d7366bc319657b32b74c90c/tox.ini#L3-L6

**Comment by davidszotten** [comment]
great, thanks for clarifying. (and apologies if i was confused by looking at an old master)
