### ISSUE TITLE
FormHelper.field_template does not work with template packs

### ISSUE THREAD

**Issue by robsdedude** [django-crispy-forms/django-crispy-forms#834]
* Package version: 1.7.2
* Django version: 2.0.4
* Python version: 3.5.2
* Template pack: 'bootstrap4' and 'bootstrap'

### Description:

I want to use the bootstrap template pack but overwrite the `field.html` template for customization (i.e. I want to hide the required asterisk only for select fields). However, setting the FormHelper's field_template attribute to "my_app/field.html" does not work. Looking into the the bootstrap templates I found that they do not consider field_template at all. This might be on purpose but it's not clear from reading the documentation.

So I'd suggest to either clarify in the docs what `field_template` does exactly or even better to make it behave as I expected: it overwrites where the template looks for the `field.html` template.

I managed to make it work by putting my custom `field.html` into `project_dir/my_app/templates/<template_pack_name>/field.html`.

**Comment by zoidbergwill** [comment]
I think supporting a custom `field_template` is a great idea, and expected behaviour, so I'd rather we fix that, instead of documenting the lack of support for it.

Would you be keen to contribute that?

I'd be happy to make a PR, or help you make one.

**Comment by robsdedude** [comment]
This is weird. Looking through the tests I found `test_form_helper.test_helper_custom_field_template` which should fail but it doesn't.

**Comment by robsdedude** [comment]
Ok, I got it. It only fails if not layout is given explicitly.
