### ISSUE TITLE
how to show initial value along with the label

### ISSUE THREAD

**Issue by sant527** [django-crispy-forms/django-crispy-forms#837]
I want the form label and the initial value to be shown 

eg:

Ingredient*( carrot )
_______________

`Div('ingredient', css_class='clearfix')` 

is it possible.

because i am using select jquery plugin and sometimes its difficult to know whats the initial value is

**Comment by smithdc1** [comment]
This sounds like a general django question. The [django docs](https://docs.djangoproject.com/en/2.2/ref/forms/fields/#label) have guidance on how to set label values (and initial values too)
