### ISSUE TITLE
Layout with foundation theme

### ISSUE THREAD

**Issue by Summer88** [django-crispy-forms/django-crispy-forms#846]
* Package version:
crispy-forms-foundation==0.7.0
django-crispy-forms==1.7.2

* Django version:
 2.1.4
* Python version:
3.5
* Template pack: 'foundation'

### Description:
To actually make the layout with 'foundation' theme package I've replace the first line in init:

`lib/python3.7/site-packages/crispy_forms/layout.py`
```

class Row(Div):
    """
    Layout object. It wraps fields in a div whose default class is "formRow". Example::

        Row('form_field_1', 'form_field_2', 'form_field_3')
    """

    def __init__(self, *args, **kwargs):
        self.css_class = 'formRow' if get_template_pack() == 'uni_form' else 'grid-x grid-margin-x' #'row'
        super(Row, self).__init__(*args, **kwargs)

```

Without this edit always a large-12 seems to be apllied to fields in form.
Could you integrate this edit in main branch?

**Comment by carltongibson** [comment]
Wouldn't this be better included in a subclass in `crispy-forms-foundation`? (We don't want to add `if` branches for each possible template pack...) 

(Closing on that basis but happy to discuss...)
