### ISSUE TITLE
Mixed HTTPS and HTTP content on https://django-crispy-forms.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by aaksarin** [django-crispy-forms/django-crispy-forms#850]
* Package version: latest

### Description:
Website with documentation [django-crispy-forms.readthedocs.io](django-crispy-forms.readthedocs.io) trying to load mixed content from HTTP and HTTPS sources at the same time. Mixed content blocked by default in at least in Chrome browser. Because of that users don't see Github Star button and flattr buttons.

> index.html:253 Mixed Content: The page at 'https://django-crispy-forms.readthedocs.io/en/latest/index.html' was loaded over HTTPS, but requested an insecure script 'http://api.flattr.com/js/0.6/load.js?mode=auto'. This request has been blocked; the content must be served over HTTPS.
> index.html:208 Mixed Content: The page at 'https://django-crispy-forms.readthedocs.io/en/latest/index.html' was loaded over HTTPS, but requested an insecure resource 'http://ghbtns.com/github-btn.html?user=maraujop&repo=django-crispy-forms&type=watch&count=true&size=large'. This request has been blocked; the content must be served over HTTPS.

**Comment by zoidbergwill** [comment]
Thanks for the report, @aaksarin.

I'll take a look, thanks. 🙏
