### ISSUE TITLE
Replace "row" with Bootstrap's "form-row"?

### ISSUE THREAD

**Issue by madneon** [django-crispy-forms/django-crispy-forms#857]
Shouldn't this:
https://github.com/django-crispy-forms/django-crispy-forms/blob/cd476927a756133c667c199bb12120f877bf6b7e/crispy_forms/layout.py#L375

be rather:
`self.css_class = 'formRow' if get_template_pack() == 'uni_form' else 'form-row'`

.. to support [Bootstrap's form-row](https://getbootstrap.com/docs/4.3/components/forms/#form-row)?

**Comment by nickperkins** [comment]
You can use both in forms. `form-row` reduces the gutters.

**Comment by carltongibson** [comment]
We're a bit stuck on the BS4 templates at the moment. We haven't got a maintainer who's actually using it. We're happy to include a fix for this issue and all the others if you (or someone) can step up. (Happy to provide guidance and that: it's just fixing the templates mostly...)

**Comment by smithdc1** [comment]
Closed by 904
