### ISSUE TITLE
Checkboxes Label prints when no value (Bootstrap4)

### ISSUE THREAD

**Issue by dwasyl** [django-crispy-forms/django-crispy-forms#861]
* Package version: 1.7.2
* Django version: 2.1.5
* Python version: 3.6
* Template pack: Bootstrap 4 (and likely others)

### Description:
In the Bootstrap4 version of `field.html`, [line 28(](https://github.com/django-crispy-forms/django-crispy-forms/blob/master/crispy_forms/templates/bootstrap4/field.html#L28)) checks for enabled labels and a checkbox field:
````
        {% if field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-check-label{% if field.field.required %} requiredField{% endif %}">
                {% crispy_field field 'class' 'form-check-input' %}
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
            {% include 'bootstrap4/layout/help_text_and_errors.html' %}
        {% else %}
            <div class="{{ field_class }}">
                {% crispy_field field %}
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            </div>
        {% endif %}
````

This means that if `label` is set to `False` (the suggested Django way of disabling a label), it still prints a label as 'False'. If the if statement is changed to:
`            {% if field|is_checkbox and form_show_labels and field.label %}`

It would be more consistent with earlier checks for label and create an easy way to disable labels on checkboxes.

**Comment by carltongibson** [comment]
We're a bit stuck on the BS4 templates at the moment. We haven't got a maintainer who's actually using it. We're happy to include a fix for this issue and all the others if you (or someone) can step up. (Happy to provide guidance and that: it's just fixing the templates mostly...)

**Comment by smithdc1** [comment]
Hi @dwasyl,

I tried to reproduce this error but I'm struggling to reproduce the exact issue (i.e. `false` appearing for checkbox)

In the crispy-test-project I amended the forms.py file by adding label=False to the fields. e.g. 

```
    checkboxes = forms.MultipleChoiceField(
        label=False,
        choices=(
            ('option_one',
             "Option one is this and that be sure to include why it's great"),
            ('option_two',
             'Option two can also be checked and included in form results'),
            ('option_three',
             'Option three can yes, you guessed it also be checked and included in form results')
        ),
        initial='option_one',
        widget=forms.CheckboxSelectMultiple,
        help_text="<strong>Note:</strong> Labels surround all the options for much larger click areas and a more usable form.",
    )


```
Just by setting the label to false I get the output below 

- default with label = false
- horizontal with no label attribute

This shows that it works correctly for all the inputs, except for boolean. Whilst I guess that is a 'bug' I don't think there is a 'use case' for a boolean field without a label?

I'm therefore going to close this issue, but we should take another look if you think boolean is an issue or if I've completely missed the point!

![screencapture-127-0-0-1-8000-bootstrap4-3-2019-10-10-20_28_20](https://user-images.githubusercontent.com/39445562/66600087-a65c4080-eb9c-11e9-985a-884a4e5054d1.png)
