### ISSUE TITLE
'BoundWidget' object has no attribute 'field'

### ISSUE THREAD

**Issue by 1000camels** [django-crispy-forms/django-crispy-forms#864]
* Package version: 1.7.2
* Django version: 2.1.7
* Python version: 3.7.2
* Template pack: (Optional)

### Description:

I am trying to set up crispy-forms for the first time and I am getting this error: 'BoundWidget' object has no attribute 'field'. I have included a dpaste below.

### Preferably also include:

http://dpaste.com/0FAT3TK

**Comment by carltongibson** [comment]
OK, so there's no info here: 

```
File "/Users/darcy/Dev/python/summitpsychologyservices/ENV/lib/python3.7/site-packages/crispy_forms/templatetags/crispy_forms_field.py" in is_checkbox
  17.     return isinstance(field.field.widget, forms.CheckboxInput)

Exception Type: AttributeError at /survey/1/
Exception Value: 'BoundWidget' object has no attribute 'field'
```

The question is why have you got a widget where we're expecting a field? 

Without much more info, there's no way of answering that question.

**Comment by smithdc1** [comment]
I'm closing this for now. Happy to re-open if more information becomes available and there is an issue to fix.
