### ISSUE TITLE
Checkbox validation broken (bootstrap4)

### ISSUE THREAD

**Issue by 0x4e3** [django-crispy-forms/django-crispy-forms#865]
* Package version: 1.7.2
* Django version: 1.11
* Python version: 3.6
* Template pack: bootstrap4

### Description:

`CrispyFieldNode` does not add 'is-invalid' class to the checkbox field with errors, so `span.invalid-feedback` stays invisible.

According to [bootstrap documentation](https://getbootstrap.com/docs/4.3/components/forms/#server-side), html must look like this:

```html
<div class="form-group">
    <div class="form-check">
      <input class="form-check-input is-invalid" type="checkbox" value="" id="invalidCheck3" required>
      <label class="form-check-label" for="invalidCheck3">
        Agree to terms and conditions
      </label>
      <div class="invalid-feedback">
        You must agree before submitting.
      </div>
    </div>
  </div>
```

but in `crispy_forms/templatetags/crispy_forms_field.py` (lines 132:140) I found this:

```python
            if (
                template_pack == 'bootstrap4'
                and not is_checkbox(field)
                and not is_file(field)
                and not is_multivalue(field)
            ):
                css_class += ' form-control'
                if field.errors:
                    css_class += ' is-invalid'
```
so checkboxes will never have `is-invalid` class and error message will stay invisible.

**Comment by mattaw** [comment]
There is another part to this bug:

crispy_forms/templates/bootstrap4/field.html line 30 puts the `<input>` inside the `<label>` 

https://github.com/django-crispy-forms/django-crispy-forms/blob/c8310b496028099956262495abbff74640beee9f/crispy_forms/templates/bootstrap4/field.html#L28-L33

Adding `is-invalid` css to the `<input>` will not cause the error to be displayed if the `<input>` is inside the `<label>`. 

According to the bootstrap4 example the correct location of the input is shown **before** the label:
https://getbootstrap.com/docs/4.0/components/forms/#server-side

**Comment by bryan-brancotte** [comment]
When using https://github.com/django-crispy-forms/crispy-test-project/pull/9 we see that it is not limited to checkbox, but also MultipleChoiceField rendered with CheckboxSelectMultiple and ChoiceField rendered with RadioSelect. You patch fixes the single CheckBox validation, here after the rendering using your patch.
![screencapture-127-0-0-1-8088-2019-04-10-16_32_19](https://user-images.githubusercontent.com/11556772/55887722-4b766c00-5bae-11e9-83a0-6b03637e7800.png)

**Comment by smithdc1** [comment]
The class for radio and checkbox need to use the custom bootstrap styles. The current radio / checkbox don't seem to be bootstrap style (the new ones look quite different)
 [demo @ codepen](https://codepen.io/david_smith/pen/yLBKeJG)

Old
![Capture2](https://user-images.githubusercontent.com/39445562/64562361-c225ba00-d344-11e9-92ad-48d396fe0a4d.PNG)

New
![Capture3](https://user-images.githubusercontent.com/39445562/64562362-c2be5080-d344-11e9-8d8f-182dac05ecd2.PNG)

**Reference material**
[Bootstrap Documentation](https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios-1)

Bootstrap version  = 4.3.1

Required classes:

**Radio**
Div : custom-control custom-radio
Input : custom-control-input _is-invalid_
Label : custom-control-label


**Checkbox**
Div : custom-control custom-checkbox
Input : custom-control-input _is-invalid_
Label : custom-control-label
