### ISSUE TITLE
On using the is-valid bootstrap4 class or not

### ISSUE THREAD

**Issue by bryan-brancotte** [django-crispy-forms/django-crispy-forms#871]
* Package version: github head
* Django version: 2.1
* Python version: 3.6.7
* Template pack: (Optional) bootstrap4

### Description:

Boostrap 4 allows to display even more explicitly which field validate or not after server-side validation [as you can see in the documentation](https://getbootstrap.com/docs/4.0/components/forms/#server-side)

Correct me if I am wrong, but we know that a forms.Form has received data when is_bound is True.

We would thus need to render the field with `is-valid` or `is-invalid` depending on the presense of field.erros, but only if the form is_bound.

For now I don't know how to get this information when rendering the field, so my question is twofold:
- Can we access the form object when rendering a field ?
- Is it worth it to use is-valid ?

**Comment by carltongibson** [comment]
For an unbound form field.errors should just be empty...

See how in bootstrap3 we're check `form.errors`, before adding the `has-error` class: 

```
{% if field.errors %} has-error{% endif %}
```

https://github.com/django-crispy-forms/django-crispy-forms/blob/cd476927a756133c667c199bb12120f877bf6b7e/crispy_forms/templates/bootstrap3/field.html#L12

A quick 👀 suggests that check is missing from bs4.

**Comment by bryan-brancotte** [comment]
Hi

In bootstrap4 template, the class is added in by a templatetags, not in the template compare to botstrap3. On that part it is ok:
https://github.com/django-crispy-forms/django-crispy-forms/blob/cd476927a756133c667c199bb12120f877bf6b7e/crispy_forms/templatetags/crispy_forms_field.py#L132-L139

For an unbound form field.errors is empty, but also for a bound form when this field is valid and another not. I managed to pass the `is_bound` status in the context in https://github.com/django-crispy-forms/django-crispy-forms/pull/872, but I am not sure that it is the best place to add it to the context
https://github.com/bryan-brancotte/django-crispy-forms/commit/b1cfd4e2812f3a90ab79422e33d4049dfc16715a#diff-3fd1f6039690e4857a9b576e95de827e

**Comment by eriktelepovsky** [comment]
After this commit all bootstrap form inputs have green border (is-valid class) when using django-filter.

**Comment by carltongibson** [comment]
@eriktelepovsky can you provide more context and or suggestions please, since it’s hard to know what to say just from your comment.

**Comment by eriktelepovsky** [comment]
Hi. Sure, sorry. I was using django-filter 2.1.0 and django-crispy-forms installed from github repository. Until yesterday, my filter form looked like it should:

![image](https://user-images.githubusercontent.com/2685808/63750285-79362600-c8ad-11e9-9c11-a6611ce80fe7.png)

After commit e4824e653235cd21c04e24f0ce869829c64669f6 the form inputs have green border because of CSS class is-valid:

![image](https://user-images.githubusercontent.com/2685808/63750483-daf69000-c8ad-11e9-861d-ce95ee5c8096.png)

It is a screenshot from the unsubmitted filter form (GET request).

I can confirm the issue using django-filter 2.2.0 as well.

Let me know if you need any other information.

**Comment by carltongibson** [comment]
Thanks @eriktelepovsky. 

So... 

It seems to me that adding the `is-valid` is in general correct. (We want to use the validation state that BS4 provides, yes?)

So, where we don't want that we need to have a fallback. The simplest thing might just be a bit of CSS. Remove the extra styling. Failing that a template override. Otherwise we're looking at controlling when the class is added (in a yet to be determined way, but in the form helper or layout).

**Comment by eriktelepovsky** [comment]
Hm. I like the feature in general, but does it means that everyone who uses BS4 and latest crispy-forms will have to override BS4 CSS or crispy templates now? Shouldn't be those CSS classes added only when the form is submitted and the validation was invoked? Either on server or client side.

**Comment by bryan-brancotte** [comment]
Thanks for the details @eriktelepovsky,

So crispy-forms  now adds BS4 `is-valid` to a field when the form have been validated [docs](https://docs.djangoproject.com/en/2.2/ref/forms/api/#django.forms.Form.is_bound) and the field is valid. What surprise me is that you get it without validating your page. My guess is that the form is always instanciated with something like 
```
my_dict = dict()
if request.GET:
    my_dict.update(request.GET)
form = MyForm (data=my_dict)
```
Providing `data` which are not to `None` result in having `form.is_bound == True` and thus the behavior you observe.

Can you confirm/infirme my guess before we can go any further ?

**Comment by eriktelepovsky** [comment]
Yes, it is the standard form initialization in django-filter:

https://django-filter.readthedocs.io/en/master/guide/usage.html#the-view

```
def product_list(request):
    f = ProductFilter(request.GET, queryset=Product.objects.all())
    return render(request, 'my_app/template.html', {'filter': f})
```

So, even if request.GET is empty dict (``{}``), it is passed to form constructor and the form is bound.

**django_filters.filterset**
```
class BaseFilterSet(object):
    def __init__(self, data=None, queryset=None, *, request=None, prefix=None):
        self.is_bound = data is not None
       
     ...

    @property
    def form(self):
        if not hasattr(self, '_form'):
            Form = self.get_form_class()
            if self.is_bound:
                self._form = Form(self.data, prefix=self.form_prefix)
            else:
                self._form = Form(prefix=self.form_prefix)
        return self._form
```

**Comment by bryan-brancotte** [comment]
Ok, I see. I don't think that django-filter should suggest any different than what it is doing now as the GET dict is always there. This digs one of my first question which was "Is it worth it to use is-valid ?". Considering that is-valid will be rendered for every from with GET data, I think we should consider removing the is-valid, and only keep the is-invalid.
Would it be ok with you @carltongibson @eriktelepovsky ?

**Comment by carltongibson** [comment]
@bryan-brancotte I'm happy with that. (Folks can add the CSS class themselves if they'd like it...) (Thanks for the input both!)

**Comment by eriktelepovsky** [comment]
Yes, I think it is the correct approach. Thanks guys.
