### ISSUE TITLE
Remove the dev branch

### ISSUE THREAD

**Issue by voidus** [django-crispy-forms/django-crispy-forms#874]
According to the discussion at https://github.com/django-crispy-forms/django-crispy-forms/pull/811 the dev branch is not used anymore except to build the RTD-docs.

If that was switched to master, the dev branch could be removed. This would be nice as the unused dev branch is a little confusing.

**Comment by smithdc1** [comment]
@carltongibson if I'm reading it right the docs are now building from master? Therefore we can either delete the Dev branch and close this, or close it anyway if you still want to keep it?

**Comment by carltongibson** [comment]
Yep. I'll double-check and then remove it.

**Comment by smithdc1** [comment]
ok, I've double checked RTD and it is running off master.

@bryan-brancotte you ok if I remove the dev branch. Also shall I tidy up any old branches which have been merged (in some cases many years ago).

**Comment by carltongibson** [comment]
Good stuff. (Never got round to this. 😬) 

TBH we stopped using this so long ago that if anything is still depending on it, we’re better off finding out the hard way and then fixing it quickly at this point.

**Comment by smithdc1** [comment]
ok - I've had a tidy 🤞 . So closing this issue.
