### ISSUE TITLE
django.core.urlresolvers not supported in Django 2.0

### ISSUE THREAD

**Issue by emilycharris** [django-crispy-forms/django-crispy-forms#882]
* Package version: 1.6.0
* Django version: 2.2.1
* Python version: 3.7.3
* Template pack: (Optional)

### Description:

I am upgrading Django and am getting an error when trying to start the server that django-crispy-forms uses django.core.urlresolvers that no longer used.  It seems it should not be imported from django.urls instead.

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [ ] Screenshots
```django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'crispy_forms.templatetags.crispy_forms_tags': No module named 'django.core.urlresolvers' ```
- [ ] Actual HTML generated
- [ ] Expected HTML

**Comment by carltongibson** [comment]
Hi latest version is 1.7.2. This should be fixed there. Can you update?

**Comment by emilycharris** [comment]
Thanks, confirmed.  I thought I'd pip installed the latest, but apparently not.

**Comment by carltongibson** [comment]
Super. Thanks for the follow-up. Good luck!
