### ISSUE TITLE
Using bootstrap4 causes a VariableDoesNotExist exception with html5_required missing when displaying a form

### ISSUE THREAD

**Issue by tomek-i** [django-crispy-forms/django-crispy-forms#891]
* Package version: 1.7.2
* Django version: 2.2.4
* Python version: 3.7.4
* Template pack: (Optional) Bootstrap4

### Description:
I tried to display a basic update form for my model, when I tried to test it and browsed to the endpoint, a VariableDoesNotExist Exception is thrown. I have to step through/continue the debugger to continue.

### Preferably also include:
Error:
![image](https://user-images.githubusercontent.com/3699937/63074441-9e9f6780-bf70-11e9-85d1-d23974054a08.png)

```
#MODEL
class Testmodel(models.Model):
    name = models.CharField('name', max_length=50)
    text = models.CharField('text', blank=True, max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

# VIEW / FORM
class TestmodelForm(ModelForm):

    class Meta:
        model = Testmodel
        fields = ('name', 'text')
        # TODO: need to add selection dropdown and date picker


def test_view(request, *args, **kwargs):
    if request.method == "POST":
        form = TestmodelForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.save()
            # TODO: add message or redirect ?!
    else:
        form = TestmodelForm()
    return render(request, 'profile.html', {'form': form})


## PROFILE.HTML
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Profile</h2>
<form method="post">
  {% csrf_token %}
   {{ form|crispy }}
  <button class="btn btn-primary" type="submit">Update</button>
</form>
{% endblock %}
```
Output:
![image](https://user-images.githubusercontent.com/3699937/63074535-1077b100-bf71-11e9-98d9-2ad9d7039236.png)

I think the required field should be marked with a red star and I assume its not and is related to the html5_required being missing?

Where and why is this key/variable missing? is this a bug? Am I doing something wrong?
I literally created a naked project to test this issue.

Also at stackexchange with bit more details: https://stackoverflow.com/questions/57454907/crispy-forms-throws-variabledoesnotexist-error-failed-lookup-for-key-html5-requ

EDIT:

I changed in the template how the form is called to:

```
{% crispy form %}
```
which doesn't cause the issue.

**Comment by nlittlejohns** [comment]
Did anyone find a solution to this problem? I'm rendering fields individually in my template and I hit this issue on every form. I'd prefer to avoid having to re-write all my templates using Form Helper and {% crispy form %} if I can avoid it.

**Comment by tomek-i** [comment]
Nah, I haven’t found any other solution to that.... maybe you could write a
context processor and just inject the variable into the template context.

I am not sure though what other implications that will carry but at least
it would make that variable available.


I, however, rewrote the templates.

**Comment by nlittlejohns** [comment]
thanks for your response! it seems as though VS Code's debugger has gotten even more aggressive of late, and my earlier workarounds no longer seem to work. I have to disable breakpoints on all exceptions to stop it complaining :-/

I guess I'll rewrite my templates at some point!

**Comment by Jack-Tran** [comment]
I had a similar problem where whenever I used `{{ form|crispy }}` the page would not load but when I switched to `{% crispy form %}` the page did load but now the submit button was not working. I had setup my `python manage.py runserver` through debugger in vscode and as nlittlejohns commented the debugger causes problems. Once i ran `python manage.py runserver` through the terminal. It seem to have resolved all problems.

**Comment by carltongibson** [comment]
This is a VS Code issue. The `VariableDoesNotExist` exception is internal to the template rendering. (It's not a bug...) 

A quick search seems to suggest putting `django: false` in the debugger launch config. 
(Don't know if that has other consequences...) 

Can I ask you folks to report this to VS Code, or the authors of whatever extensions you're using, since it should be addressed there.

**Comment by dehai** [comment]
it seams like a VS Code issue,  need change `"django": false`  on launch.json.

**Comment by Jack-Tran** [comment]
> it seams like a VS Code issue, need change `"django": false` on launch.json.

Thank you dehai, that fixed the problem.

**Comment by tomek-i** [comment]
I am not sure  if it does any more But this setting enables vs code to
debug page templates.

**Comment by rmControls** [comment]
Can anyone tell me what is the solution for this... ??

This question closed without proper solution...

**Comment by janinesroux** [comment]
I had similar problems, where my form was displayed and then subsequently overwritten. My issue was resolved when I noticed that the in the views:
[class OrderCreateView(CreateView):](url)
 self.request was defaulting to GET instead of POST. You can debug this by testing the condition 
`if self.request.POST:` 
(I has assumed incorrectly that a create view would always default to POST).
This resulted in Django trying to GET a record which doesn't exist yet.
in my case I changed my view logic and set the method in the forms.py form to [self.helper.form_method = 'POST'](url) in the form, and the error was resolved.
