### ISSUE TITLE
Consistency of approach for compatibility logic

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/django-crispy-forms#900]
A recent pull request (#895) added compatibility for Django 3.0 by adding the logic into the `compatibilty.py`. 

```
if django.VERSION < (3, 0):
    from django.utils.lru_cache import lru_cache
else:
    from functools import lru_cache

```

There are other examples in the project where this logic is within each file e.g. `helper.py`. 

```
try:
    from django.urls import reverse, NoReverseMatch
except ImportError:
    # Django < 1.10
    from django.core.urlresolvers import reverse, NoReverseMatch

```

Is there a preference in approach, and if so is there benefit in choosing one and implementing it consistently?

**Comment by carltongibson** [comment]
The latter is preferred. (But it's not a biggie 🙂)

In general `try` the new thing. If that fails fallback to the old. Happy to see any PRs here. 

I'll close this, since it's not really an issue per se (But, yes, happy to take those clean ups.)
