### ISSUE TITLE
FileField does not render using bootstrap

### ISSUE THREAD

**Issue by calinsinea** [django-crispy-forms/django-crispy-forms#902]
* Package version: 1.7.2
* Django version: 2.2.4
* Python version: 3.7.3
* Template pack: (Optional) Bootstrap4

I created a form with a forms.FileField and setup the template pack to bootstrap4 but the field is rendered using django FileField.

```
class CreateCompanyUsersFromCsv(forms.Form):
    csv = forms.FileField(widget=forms.FileInput(attrs={'accept':'application/xml'}),)

    @property
    def helper(self):
        helper = FormHelper(self)
        helper.add_input(Submit("submit", "Submit", css_class="btn-primary"))
        helper.form_action = reverse_lazy('company_users_create_csv', kwargs=self.initial)
        helper.form_method = "POST"
        return helper
```

<img width="235" alt="Screen Shot 2019-09-24 at 17 32 15" src="https://user-images.githubusercontent.com/55737649/65495750-368a5c80-def2-11e9-81e1-c577868c7fa8.png">

**Comment by smithdc1** [comment]
Looks like #809 implemented this feature? Timeline wise that pr was added after release 1.7.2

**Comment by calinsinea** [comment]
Hi thanks, do you know by chance when is the next release, the last release was last year

**Comment by carltongibson** [comment]
We're preparing a new release for before Django 3.0, so now-ish. Follow #906
