### ISSUE TITLE
Fix RTD publication

### ISSUE THREAD

**Issue by bryan-brancotte** [django-crispy-forms/django-crispy-forms#914]
Thanks to @smithdc1 for noticing that https://django-crispy-forms.readthedocs.io/en/latest/ is not up-o-date.

@carltongibson, you seemed to be interested in fixing it, so I assign it to you.

**Comment by bryan-brancotte** [comment]
For information, the doc in building fine with latest sphinx 2.2.0, and in RTD the last proposed version is 1.2.1

**Comment by carltongibson** [comment]
OK, I triggered a manual build for `latest`. I'll have to look into the webhook... :)

stable built correctly from the 1.8 tag.

**Comment by bryan-brancotte** [comment]
The built seems to have failed when looking at https://readthedocs.org/projects/django-crispy-forms/builds/ :(

**Comment by carltongibson** [comment]
OK, the error there was quite helpful. Django wasn't installed in the venv. 

Fixed in 2717d69be6ae0845bbfc472f525ef34bbb21af8d

Latest built OK. Stable will need to wait until we tag 1.8.1, but should resolve. Thanks @bryan-brancotte!

**Comment by carltongibson** [comment]
But of course that broke the travis build. Sigh. 🙂

I shall fix that tomorrow.

**Comment by bryan-brancotte** [comment]
Thanks to you @carltongibson
