### ISSUE TITLE
Broken link on https://pypi.org/project/django-crispy-forms/

### ISSUE THREAD

**Issue by uri-rodberg** [django-crispy-forms/django-crispy-forms#927]
There is a link to http://github.com/djang-crispy-forms/django-crispy-forms which is 404.

**Comment by carltongibson** [comment]
Fixed in 649a407eb20d04ce345dc0bbfebf205589cc6f47

**Comment by uri-rodberg** [comment]
@carltongibson It's not deployed to https://pypi.org/project/django-crispy-forms/
