### ISSUE TITLE
Docs Layout

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/django-crispy-forms#928]
Looking at the [documentation](https://django-crispy-forms.readthedocs.io/en/latest/) I'm think the layout could be improved. 

How about:

1. Installation - see #924 
2. Usage - "You can use | crispy, or you can use `formhelper`, and here is an example of what you get". i.e. [CrispyFiler](https://django-crispy-forms.readthedocs.io/en/latest/filters.html) and the fundamentals of [CrispyTags](https://django-crispy-forms.readthedocs.io/en/latest/crispy_tag_forms.html)
3. Layout - "Now you understand the basics of laying out a form, here are the other options available"
4. Updating on the go "you can even update layouts 'on the go"
5. Helper - "and here are some other configuration options for the helper" (probably put the second half of crispy tags here)
6. Formsets
7. FAQs
8. API
9. Development - include creating own packs

Thoughts?

**Comment by carltongibson** [comment]
Hi @smithdc1. Sorry for the slow follow-up. 

Short answer, Yes. :)

I'll close this as issue though...  small PRs taking on each point separately is the way to go. 

Super. 💪
