### ISSUE TITLE
Multi-Select & Radio Button Style Issues 

### ISSUE THREAD

**Issue by inr211** [django-crispy-forms/django-crispy-forms#929]
Hello! After our team updated to django-crispy-forms 1.8.0, we ran into styling issues around multi-select and radio fields. Those fields all turned green, even though the fields around them remained unchanged. 

![67322833-9ff48f80-f4df-11e9-9f73-59f08362430a](https://user-images.githubusercontent.com/3311562/67891869-d9ee1300-fb29-11e9-8bc2-194fa4ca6e14.png)

We saw the following [commit](https://github.com/django-crispy-forms/django-crispy-forms/pull/872) that added Boostrap 4's is-valid css class to crispy form fields. However, right after, we saw the following [commit](https://github.com/django-crispy-forms/django-crispy-forms/pull/894) removing the is-valid css from `crispy_form_fields`. It seems like multi-select checkboxes and radio select were not included in the revert. Was this done on purpose? If so, what is the recommended way for working around the `is-valid` styling?

Thanks!

**Comment by smithdc1** [comment]
Hi, this doesn't look quite right does it! You are quite right that there was an attempt to implement is-valid but quickly realised it wasn't quite so straight forward. I'm on the road right now so whilst i cant take a proper look right now here are some thoughts.

https://github.com/django-crispy-forms/django-crispy-forms/blob/92b9a8abfc203d2f332822ed16234730d89213a2/crispy_forms/templates/bootstrap4/layout/radioselect.html#L8

This line here is giving you the is-valid for radios. So the form is being generated with is-bound being true. 

I suspect we have the same code for multiple checkbox as well.

Do you think you would be in a position to raise a pr with a fix and we can try and get it in 1.8.1 for you? (Due soon TM)

**Comment by inr211** [comment]
Sounds good. I've opened a Pull Request with my proposed fix.

**Comment by smithdc1** [comment]
Closed by #930
