### ISSUE TITLE
Setting input type in Field()

### ISSUE THREAD

**Issue by NewDimension** [django-crispy-forms/django-crispy-forms#937]
* Package version: 1.8.0 
* Template pack: Bootstrap 4 

### Description:

Crispy forms sets defined attribute at the end of the template as seen [here.](https://github.com/django-crispy-forms/django-crispy-forms/blob/master/crispy_forms/templates/bootstrap4/layout/baseinput.html) Which means that passing `type="date"` to Field() adds a redundant `type` property which gets  ignored by the browser.

### Example
```
        self.helper.layout = Layout(
            Fieldset(
                '',  # Legend
                Field('date_field', type="date"),
            ),
        )
```
### Workaround
The standard way of setting attrs in Meta.widgets enables us to override a field's input type.

### Question
Would it make sense to move attrs to the beginning of the template so our values take precedence? Foregoing the need for an attrs dict per the stated benefit of Field()

**Comment by smithdc1** [comment]
Hi @NewDimension ,

The <input> fields are generated by [Django](https://docs.djangoproject.com/en/2.2/ref/forms/api/#django.forms.BoundField) not baseinput (I have made this mistake also). 

So I think this is working as intended, happy to take a PR on the docs if you think this could be made more clear?
