### ISSUE TITLE
crispy_addon option to show placeholder text

### ISSUE THREAD

**Issue by bgeneto** [django-crispy-forms/django-crispy-forms#939]
* Package version: 1.8.0
* Django version: 2.2.7
* Python version: 3.7
* Template pack: bootstrap4

### Description:

Unfortunately `crispy_addon` has no option to show a placeholder. 

When one sets `form_show_labels` option to `False`, it would be nice to have an option to show the placeholder instead, for example, `form_show_placeholders` or `placeholder='Text'` in `crispy_addon`. 

If all you have is a template (no forms.py or views.py) to work with, like when replacing a Django's default template (e.g. django/contrib/admin/templates/registration/password_reset_form.html and several other admin templates) it would be fantastic if you have an option to autoset and autoshow the placeholder... maybe it could be done without an explicit option to `crispy_addon` with PR #935 by just setting `auto_populate_placeholders = True`. 

Without this feature one has to write a form class just to show the placeholder text :-(

**Comment by smithdc1** [comment]
Yes, I guess if 935 gets merged we could add an additional option here.

https://github.com/django-crispy-forms/django-crispy-forms/blob/e149dafa9a474ac41f98dd5ef78b382cbc21e824/crispy_forms/templatetags/crispy_forms_field.py#L177

**Comment by smithdc1** [comment]
Closed as per #935
