### ISSUE TITLE
Bootstrap 4 Checkbox Alignment (Non-Horizontal Form)

### ISSUE THREAD

**Issue by dwasyl** [django-crispy-forms/django-crispy-forms#941]
* Package version: 1.8.0
* Django version: 2.26
* Python version: 3.6
* Template pack: Bootstrap4

### Description:

The new bootstrap4 template pack checks for checkboxes and then creates a wrapper div for the `form-group` property. This works well, except on a regular form where elements have `wrapper_class`s specified with columns. The `wrapper_class` on regular form elements is applied directly to the input's div wrapper so a `wrapper_class` that specifies a col (i.e. `col-12`) would be on the same element, `form-group` and `col` have complimentary padding that applies when used together. It's only a 5px difference, but it's noticeable.

However, on checkboxes due to the extra wrapper div, the `wrapper_class` classes are applied to the inner div and not the same div that specifies `form-group`. This causes checkbox elements to be further indented than any other form element.

As a fix, being able to specific additional classes on the separate checkbox `form-group` line would solve the problem.
Line 7 of the `field.html` template makes the difference here (`<div class="form-group{% if 'form-horizontal' in form_class %} row{% endif %}">`).

**Comment by smithdc1** [comment]
Hi @dwasyl, thanks for investigating this. Do you think you would be in a position to raise a Pull Request with a proposed fix for this?

**Comment by dwasyl** [comment]
@smithdc1 potentially, I'm not entirely sure what the best structural approach is here. Creating an entirely new `checkbox_outer_wrapper_css` seems too tag/template specific. The checkbox behaviour is odd since it's not obvious that they are treated differently from everything else, but I understand why it's done that way. Another way, and likely my preference, would be to move the `wrapper_css` to the outer div on checkboxes, but that could impact existing code/implementations.

What do you think? Any other ideas?

**Comment by smithdc1** [comment]
Hi @dwasyl, 

On a second look at this I wonder if the solution is a bit easier. 

It sounds like your problem the same as #800. If so, does #878 solve your problem? :crossed_fingers: 

I am hoping to review pr 878 this evening to see if I can recreate the issue and confirm the pr fixes it.

**Comment by smithdc1** [comment]
Hi @dwasyl, I've reviewed the other PR. Let me know your thoughts. 
Thanks

**Comment by dwasyl** [comment]
@smithdc1 I took a look at the PR and it doesn't do the trick. I got around it by removing some of the `Row()`s from my code, but the way checkboxes are rendered there's no way to put anything on wrapping `div`.

**Comment by smithdc1** [comment]
Ok. Glad you managed to find a solution :+1:
