### ISSUE TITLE
Reponsive columns are broken.

### ISSUE THREAD

**Issue by dmptrluke** [django-crispy-forms/django-crispy-forms#963]
* Package version: 1.8.1
* Django version: 3.0.2
* Python version: 3.8
* Template pack: Bootstrap 4

### Description:

I think #916 broke things. Forcing the CSS class 'col' makes incorrect assumptions that break any kind of responsive columns. If one is using responsive columns eg `css_class='col-md-6'` to only break into columns on desktop, it no longer works. It's easy to do it backwards (eg, only display columns on mobile) but I do not think anyone would do that.

Bootstrap is designed to work upwards, starting with the smallest size by default and applying responsive rules as the screen size increases. That default should not be to display as columns with no ability to override it.

**Comment by dmptrluke** [comment]
Suggest fix would be to simply not include the automatic `col` class if a user defines their own `css_class`. A smarter fix would be to detect if a user is has specifically used `col_*` as a custom class.

**Comment by smithdc1** [comment]
Hi @dmptrluke 

Here are a few notes. 

This layout

```
        Row(
            Column('text_input_a','text_input_b'),
            Column('text_input_c'),
        ),


```
In Version 1.7.2
Demo link [here](https://focused-spence-52c9a0.netlify.com/)
Notes: form is mis-aligned and right up against screen edge on mobile. Stacks on very small screens.

```
<div class="row">
    <div class="formColumn">
       ...
        </div>
    </div>
```


In 1.8.1
Demo link [here](https://crispy-forms-project.herokuapp.com/)
Notes : better alignment, but doesn't stack even on very small screens.

```
<div class="form-row ">
    <div class="col ">
      ...
        </div>
    </div>
```

It's getting late now so don't have time to look at this much further tonight. As a note for the future it's probably this line here that needs changing. @dmptrluke Appreciate your thoughts on what this could be. 

https://github.com/django-crispy-forms/django-crispy-forms/blob/74852560ef5219e9c293cc1472b1a993676166ff/crispy_forms/templates/bootstrap4/layout/column.html#L1


In the meantime you can override the template pack column.html template to remove the additional `col`

**Comment by dmptrluke** [comment]
A decent default that would pretty much remove the need for defining custom classes would be `col-md`. This would display as stacked on mobile phones, and columns on anything bigger.
