### ISSUE TITLE
Template does not exist at /template_name/ bootsrap4/uniform.html

### ISSUE THREAD

**Issue by Abkgit01** [django-crispy-forms/django-crispy-forms#984]
* Package version:
* Django version:
* Python version:
* Template pack: (Optional)

### Description:

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### Preferably also include:

- [ ] Example Django Crispy Forms code
- [ ] Screenshots
- [ ] Actual HTML generated
- [ ] Expected HTML

**Comment by smithdc1** [comment]
Hi when I get an error like that it's usually because the settings.py file hasn't been setup properly. 

See some guidance notes here.

https://django-crispy-forms.readthedocs.io/en/latest/install.html
