### ISSUE TITLE
A couple of questions on testing and templates. 

### ISSUE THREAD

**Issue by smithdc1** [django-crispy-forms/django-crispy-forms#996]
I'm doing some work to improve test coverage. Whilst I need #975 to merge first (my tests fail on only Django versions 2.0 & 2.1 for some reason 🤷‍♂ ) the work raised a few questions. 

1. Should we add [spaceless](https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#spaceless) to the templates? 

I think this would remove the whitespace / linebreaks as seen in the example here. 
```
                '<form  method="post" > <div  class="test" class="form-group"> <div class=""> <input type="submit"\n   '
                ' name="Save"\n    value="Save"\n    \n        class="btn btn-primary btn-primary"\n        '
                'id="submit-id-save"\n    \n    \n    /> </div>\n</div> </form>'
```

2. How should we write tests. 

Having looked at Django tests recently I appreciated that the full expected html was included in the tests, it made it clearer what was intended to happen by reading the test alone. Currently we have some tests written like the example below. Guess how many inputs there are in this piece of html (9 and 8 are both incorrect, iirc). 

https://github.com/django-crispy-forms/django-crispy-forms/blob/c6bc2678d32b3644960fbac615e52517e1bbcea6/crispy_forms/tests/test_form_helper.py#L53

As an example one of my new tests is:

```
    def test_uneditablefield(self, settings):
        test_form = SampleForm()
        test_form.helper = FormHelper()
        test_form.helper.layout = Layout(UneditableField("is_company"))
        html = render_crispy_form(test_form)
        if settings.CRISPY_TEMPLATE_PACK == "bootstrap":
            expected = (
                '<form  method="post" > <div id="div_id_is_company" class="control-group"> '
                '<div class="control-label">company</div> <div class="controls"> '
                '<span  class="uneditable-input"></span> </div>\n</div> </form>'
            )
            assert html.strip() == expected
```

Is this more readable? Need to be cautious not to 'dump' lots of html into the tests. Maybe `contains_partial` can help here. 

Appreciate your thoughts.

**Comment by carltongibson** [comment]
We shouldn’t need spaceless because we should be able to use Django’s assertHTMLEqual()

I’d be open to BS4 or pyquery if that would make assertions more sane. 

More or less, I’ve not got the perfect answer here. Some of the tests are a bit cumbersome to say the least. Whatever works and is maintainable. 

Your example here looks fine. 🙂

**Comment by smithdc1** [comment]
Thanks for the response. Super helpful! :+1:
